---
permalink: sg6000/optional-changing-raid-mode-sg6000-only.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: 스토리지 및 복구 요구 사항을 수용하기 위해 어플라이언스에서 다른 RAID 모드로 변경할 수 있습니다. 어플라이언스 스토리지 노드를 구축하기 전에만 모드를 변경할 수 있습니다. 
---
= 선택 사항: RAID 모드 변경(SG6000만 해당)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 및 복구 요구 사항을 수용하기 위해 어플라이언스에서 다른 RAID 모드로 변경할 수 있습니다. 어플라이언스 스토리지 노드를 구축하기 전에만 모드를 변경할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* StorageGRID에 연결할 수 있는 모든 클라이언트를 사용 중입니다.
* 클라이언트에 가 있습니다 xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저].


어플라이언스를 스토리지 노드로 구축하기 전에 다음 볼륨 구성 옵션 중 하나를 선택할 수 있습니다.

* * DDP *: 이 모드는 데이터 드라이브 8개마다 2개의 패리티 드라이브를 사용합니다. 모든 어플라이언스에 대한 기본 권장 모드입니다. RAID6와 비교하여 DDP는 시스템 성능을 향상하고, 드라이브 장애 후 리빌드 시간을 줄이고, 관리를 간소화합니다.
* * DDP16 *: 이 모드는 데이터 드라이브 16개마다 2개의 패리티 드라이브를 사용하므로 DDP에 비해 스토리지 효율성이 높습니다. RAID6와 비교했을 때 DDP16은 시스템 성능이 향상되고 드라이브 장애 후 리빌드 시간이 줄어들며 관리가 용이하며 스토리지 효율성이 비슷합니다. DDP16 모드를 사용하려면 구성에 최소 20개의 드라이브가 있어야 합니다. DDP16은 드로어 손실 방지 기능을 제공하지 않습니다.
* * RAID6 *: 이 모드는 16개 이상의 데이터 드라이브마다 2개의 패리티 드라이브를 사용합니다. RAID 6 모드를 사용하려면 구성에 최소 20개의 드라이브가 포함되어 있어야 합니다. RAID6는 DDP와 비교할 때 어플라이언스의 스토리지 효율성을 높일 수 있지만 대부분의 StorageGRID 환경에서는 권장되지 않습니다.



IMPORTANT: 볼륨이 이미 구성되었거나 StorageGRID가 이전에 설치된 경우 RAID 모드를 변경하면 볼륨이 제거되고 교체됩니다. 해당 볼륨의 모든 데이터가 손실됩니다.

.단계
. 브라우저를 열고 어플라이언스의 컴퓨팅 컨트롤러에 대한 IP 주소 중 하나를 입력합니다.
+
(* https://_Controller_IP_:8443*`)

+
'_Controller_IP_'는 3개의 StorageGRID 네트워크 중 어느 한 곳의 컴퓨팅 컨트롤러(스토리지 컨트롤러가 아님)의 IP 주소입니다.

+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. 고급 * > * RAID 모드 * 를 선택합니다.
. RAID 모드 구성 * 페이지의 모드 드롭다운 목록에서 원하는 RAID 모드를 선택합니다.
. 저장 * 을 클릭합니다.


http://mysupport.netapp.com/info/web/ECMP1658252.html["NetApp E-Series 시스템 문서 사이트"^]
