---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: SG6000-CN 컨트롤러가 최적의 상태로 작동하지 않거나 오류가 발생한 경우 교체해야 할 수 있습니다. 
---
= SG6000-CN 컨트롤러를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SG6000-CN 컨트롤러가 최적의 상태로 작동하지 않거나 오류가 발생한 경우 교체해야 할 수 있습니다.

.필요한 것
* 교체할 컨트롤러와 부품 번호가 동일한 교체 컨트롤러가 있습니다.
* 컨트롤러에 연결된 각 케이블을 식별하는 라벨이 있습니다.
* 데이터 센터에서 물리적으로 교체할 컨트롤러를 가지고 있습니다.
+
xref:locating-controller-in-data-center.adoc[데이터 센터에서 컨트롤러를 찾습니다]



.이 작업에 대해
SG6000-CN 컨트롤러를 교체할 때 어플라이언스 스토리지 노드에 액세스할 수 없습니다. SG6000-CN 컨트롤러가 충분히 작동하는 경우 이 절차를 시작할 때 제어된 종료를 수행할 수 있습니다.


NOTE: StorageGRID 소프트웨어를 설치하기 전에 컨트롤러를 교체하는 경우 이 절차를 완료한 후 즉시 StorageGRID 어플라이언스 설치 프로그램에 액세스하지 못할 수 있습니다. 어플라이언스와 동일한 서브넷에 있는 다른 호스트에서 StorageGRID 어플라이언스 설치 프로그램에 액세스할 수 있지만 다른 서브넷에 있는 호스트에서는 액세스할 수 없습니다. 이 조건은 15분 내에 해결되어야 하며(원래 컨트롤러의 ARP 캐시 항목이 시간 초과될 때), 또는 로컬 라우터 또는 게이트웨이에서 수동으로 이전의 ARP 캐시 항목을 삭제하여 즉시 조건을 지울 수 있습니다.

.단계
. SG6000-CN 컨트롤러가 제어된 종료를 허용하기 위해 충분히 작동하는 경우 SG6000-CN 컨트롤러를 종료합니다.
+
xref:shutting-down-sg6000-cn-controller.adoc[SG6000-CN 컨트롤러를 종료합니다]

. 다음 두 가지 방법 중 하나를 사용하여 SG6000-CN 컨트롤러의 전원이 꺼져 있는지 확인합니다.
+
** 컨트롤러 전면에 있는 전원 표시등 LED가 꺼져 있습니다.
** BMC 인터페이스의 전원 제어 페이지는 컨트롤러가 꺼져 있음을 나타냅니다.


. 컨트롤러에 연결된 StorageGRID 네트워크가 DHCP 서버를 사용하는 경우 DNS/네트워크 및 IP 주소 설정을 업데이트합니다.
+
.. SG6000-CN 컨트롤러 전면에서 MAC 주소 레이블을 찾아 관리 네트워크 포트의 MAC 주소를 확인합니다.
+

NOTE: MAC 주소 레이블에는 BMC 관리 포트의 MAC 주소가 나열됩니다. + 관리자 네트워크 포트의 MAC 주소를 확인하려면 레이블의 16진수에 * 2 * 를 추가해야 합니다. 예를 들어 레이블의 MAC 주소가 * 09 * 로 끝나는 경우 관리 포트의 MAC 주소는 * 0B * 로 끝납니다. 레이블의 MAC 주소가 * (_y_) FF * 로 끝나는 경우 관리 포트의 MAC 주소는 * (_y_+1) 01 * 로 끝납니다. Windows에서 계산기를 열고, Programmer 모드로 설정하고, Hex를 선택하고, MAC 주소를 입력한 다음, * + 2 = * 를 입력하여 이 계산을 쉽게 수행할 수 있습니다.

.. 제거한 컨트롤러의 DNS/네트워크 및 IP 주소를 대체 컨트롤러의 MAC 주소와 연관시킬 것을 네트워크 관리자에게 요청합니다.
+

IMPORTANT: 교체 컨트롤러에 전원을 켜기 전에 원래 컨트롤러의 모든 IP 주소가 업데이트되었는지 확인해야 합니다. 그렇지 않으면 컨트롤러가 부팅될 때 새 DHCP IP 주소를 가져오며 StorageGRID에 다시 연결되지 않을 수 있습니다. 이 단계는 컨트롤러에 연결된 모든 StorageGRID 네트워크에 적용됩니다.

+

NOTE: 원래 컨트롤러가 정적 IP 주소를 사용하는 경우 새 컨트롤러는 제거된 컨트롤러의 IP 주소를 자동으로 채택합니다.



. SG6000-CN 컨트롤러 분리 및 교체:
+
.. 케이블에 레이블을 지정한 다음 케이블과 모든 SFP+ 또는 SFP28 트랜시버를 분리합니다.
+

IMPORTANT: 성능 저하를 방지하려면 케이블을 비틀거나 접거나 끼거나 밟지 마십시오.

.. 캐비닛 또는 랙에서 장애가 발생한 컨트롤러를 분리합니다.
.. 캐비닛 또는 랙에 교체용 컨트롤러를 설치합니다.
.. 케이블 및 SFP+ 또는 SFP28 트랜시버를 교체합니다.
.. 컨트롤러 전원을 켜고 컨트롤러 LED 및 부팅 코드를 모니터링합니다.


. 어플라이언스 스토리지 노드가 그리드 관리자에 표시되고 경보가 나타나지 않는지 확인합니다.
. Grid Manager에서 * nodes * 를 선택하고 노드 컨트롤러의 BMC IP 주소가 올바른지 확인합니다.
+
노드 컨트롤러 IP 주소가 유효하지 않거나 예상 범위에 없는 경우 복구 및 유지 관리 지침에 설명된 대로 IP 주소를 다시 구성하십시오.

+

NOTE: 초기 설치 중에 SNMP 트랩 대상 또는 e-메일 알림 설정과 같은 추가 사용자 지정을 적용한 경우 구성을 기록 및 확인하고 필요한 경우 다시 적용해야 합니다.

+
xref:../maintain/index.adoc[복구 및 유지 관리]



.관련 정보
xref:sg6000-cn-installing-into-cabinet-or-rack.adoc[SG6000-CN: 캐비닛 또는 랙에 설치합니다]

xref:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.adoc[SG6000-CN 컨트롤러의 상태 표시등 및 단추를 봅니다]

xref:viewing-boot-up-codes-for-sg6000-cn-controller.adoc[SG6000-CN 컨트롤러의 부팅 코드를 봅니다]
