---
permalink: sg6000/reviewing-appliance-network-connections-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, network connections, network connection, network, connection, grid, admin, client, bmc, management, SANtricity System Manager, SANtricity 
summary: StorageGRID 어플라이언스를 설치하기 전에 어플라이언스에 연결할 수 있는 네트워크를 이해해야 합니다. 
---
= 어플라이언스 네트워크 연결 검토(SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 어플라이언스를 설치하기 전에 어플라이언스에 연결할 수 있는 네트워크를 이해해야 합니다.

StorageGRID 어플라이언스를 StorageGRID 시스템에 스토리지 노드로 구축할 경우 다음 네트워크에 연결할 수 있습니다.

* * StorageGRID * 용 그리드 네트워크: 그리드 네트워크는 모든 내부 StorageGRID 트래픽에 사용됩니다. 그리드에서 모든 사이트 및 서브넷의 모든 노드 간에 연결을 제공합니다. 그리드 네트워크가 필요합니다.
* StorageGRID*용 관리자 네트워크: 관리자 네트워크는 시스템 관리 및 유지 보수에 사용되는 폐쇄된 네트워크입니다. 관리 네트워크는 일반적으로 사설 네트워크이며 사이트 간에 라우팅할 필요가 없습니다. 관리 네트워크는 선택 사항입니다.
* * StorageGRID용 클라이언트 네트워크: * 클라이언트 네트워크는 S3 및 Swift를 포함한 클라이언트 애플리케이션에 대한 액세스를 제공하는 데 사용되는 개방형 네트워크입니다. 클라이언트 네트워크는 그리드에 대한 클라이언트 프로토콜 액세스를 제공하므로 그리드 네트워크를 격리하고 보호할 수 있습니다. 클라이언트 네트워크는 선택 사항입니다.
* * SANtricity 시스템 관리자용 관리 네트워크 * (선택 사항): 이 네트워크는 스토리지 컨트롤러의 SANtricity 시스템 관리자에 대한 액세스를 제공하므로 스토리지 컨트롤러 쉘프의 하드웨어 구성 요소를 모니터링하고 관리할 수 있습니다. 이 관리 네트워크는 StorageGRID용 관리 네트워크와 같을 수도 있고 독립 관리 네트워크일 수도 있습니다.
+
옵션 SANtricity System Manager 네트워크가 연결되지 않은 경우 일부 SANtricity 기능을 사용하지 못할 수 있습니다.

* * SG6000-CN 컨트롤러용 BMC 관리 네트워크 * (선택 사항): 이 네트워크는 SG6000-CN의 베이스보드 관리 컨트롤러에 대한 액세스를 제공하여 SG6000-CN 컨트롤러의 하드웨어 구성요소를 모니터링하고 관리할 수 있도록 합니다. 이 관리 네트워크는 StorageGRID용 관리 네트워크와 같을 수도 있고 독립 관리 네트워크일 수도 있습니다.
+
선택적 BMC 관리 네트워크가 연결되지 않은 경우 일부 지원 및 유지 관리 절차를 수행하기가 더 어려워집니다. 지원 목적으로 필요한 경우를 제외하고 BMC 관리 네트워크를 연결하지 않은 상태로 둘 수 있습니다.




NOTE: StorageGRID 네트워크에 대한 자세한 내용은 _Grid Primer_를 참조하십시오.

xref:gathering-installation-information-sg6000.adoc[설치 정보 수집(SG6000)]

xref:cabling-appliance-sg6000.adoc[케이블 어플라이언스(SG6000)]

xref:port-bond-modes-for-sg6000-cn-controller.adoc[SG6000-CN 컨트롤러의 포트 결합 모드]

xref:../network/index.adoc[네트워크 지침]
