---
permalink: audit/system-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, system, ECOC, ETAF, GNRG, GNUR, GTED, GTST, GTSU, IDEL, LKCU, LLST, OLST, ORLM, SADD, SADE, SVRF, SVRU, SYSD, SYST, SYSU, VLST 
summary: '시스템 감사 범주에 속하는 감사 메시지에 익숙해야 합니다. 이러한 이벤트는 감사 시스템 자체, 그리드 노드 상태, 시스템 전체 작업 활동(그리드 작업\) 및 서비스 백업 작업과 관련된 이벤트로, 잠재적인 문제를 해결할 수 있습니다.' 
---
= 시스템 감사 메시지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 감사 범주에 속하는 감사 메시지에 익숙해야 합니다. 이러한 이벤트는 감사 시스템 자체, 그리드 노드 상태, 시스템 전체 작업(그리드 작업) 및 서비스 백업 작업과 관련된 이벤트로, 잠재적인 문제를 해결할 수 있습니다.

|===
| 코드 | 메시지 제목 및 설명입니다 | 을 참조하십시오 


 a| 
ECMC
 a| 
누락된 삭제 코딩 데이터 조각: 누락된 삭제 코딩 데이터 조각이 감지되었음을 나타냅니다.
 a| 
xref:ecmc-missing-erasure-coded-data-fragment.adoc[ECMC: 삭제 코딩 데이터 조각이 없습니다]



 a| 
ECOC
 a| 
손상된 삭제 코딩 데이터 조각: 손상된 삭제 코딩 데이터 조각이 감지되었음을 나타냅니다.
 a| 
xref:ecoc-corrupt-erasure-coded-data-fragment.adoc[ECOC: 손상된 삭제 코딩 데이터 조각]



 a| 
ETAF
 a| 
보안 인증 실패: 전송 계층 보안(TLS)을 사용한 연결 시도가 실패했습니다.
 a| 
xref:etaf-security-authentication-failed.adoc[ETAF: 보안 인증 실패]



 a| 
GNRG
 a| 
GNDS 등록: StorageGRID 시스템에서 자체적으로 갱신되거나 등록된 서비스.
 a| 
xref:gnrg-gnds-registration.adoc[GNRG: GNDS 등록]



 a| 
GNUR
 a| 
GNDS 등록 취소: StorageGRID 시스템에서 서비스 등록이 취소되었습니다.
 a| 
xref:gnur-gnds-unregistration.adoc[GNUR:GNDS 등록 취소]



 a| 
GTED
 a| 
그리드 작업 종료: CMN 서비스가 그리드 작업 처리를 완료했습니다.
 a| 
xref:gted-grid-task-ended.adoc[GTED: 그리드 작업이 종료되었습니다]



 a| 
GTSt
 a| 
그리드 작업 시작됨: CMN 서비스가 그리드 작업 처리를 시작했습니다.
 a| 
xref:gtst-grid-task-started.adoc[GTSt: 그리드 작업이 시작되었습니다]



 a| 
GTSU
 a| 
Grid Task Submitted(그리드 작업 제출됨): CMN 서비스로 GRID 작업이 제출되었습니다.
 a| 
xref:gtsu-grid-task-submitted.adoc[GTSU: 그리드 작업 제출됨]



 a| 
IDEL
 a| 
ILM 시작 삭제: ILM이 개체 삭제 프로세스를 시작할 때 이 감사 메시지가 생성됩니다.
 a| 
xref:idel-ilm-initiated-delete.adoc[IDEL: ILM 삭제 시작]



 a| 
LKCU
 a| 
덮어쓴 개체 정리. 이 감사 메시지는 덮어쓴 개체를 자동으로 제거하여 저장 공간을 확보할 때 생성됩니다.
 a| 
xref:lkcu-overwritten-object-cleanup.adoc[LKCU: 덮어쓴 개체 정리]



 a| 
LLST
 a| 
위치 손실: 이 감사 메시지는 위치가 손실될 때 생성됩니다.
 a| 
xref:llst-location-lost.adoc[LLST: 위치가 손실되었습니다]



 a| 
OLST
 a| 
개체 손실: 요청된 개체를 StorageGRID 시스템 내에 찾을 수 없습니다.
 a| 
xref:olst-system-detected-lost-object.adoc[OLST: 시스템에서 손실된 개체를 감지했습니다]



 a| 
ORLM
 a| 
개체 규칙 충족: ILM 규칙에 지정된 대로 개체 데이터가 저장됩니다.
 a| 
xref:orlm-object-rules-met.adoc[ORLM: 개체 규칙이 충족되었습니다]



 a| 
추가
 a| 
보안 감사 비활성화: 감사 메시지 로깅이 꺼졌습니다.
 a| 
xref:sadd-security-audit-disable.adoc[추가: 보안 감사 비활성화]



 a| 
사드
 a| 
보안 감사 활성화: 감사 메시지 로깅이 복원되었습니다.
 a| 
xref:sade-security-audit-enable.adoc[Sade: 보안 감사 활성화]



 a| 
SVRF
 a| 
오브젝트 저장소 확인 실패: 콘텐츠 블록이 확인 검사에 실패했습니다.
 a| 
xref:svrf-object-store-verify-fail.adoc[SVRF: Object Store Verify Fail(SVRF: 오브젝트 저장소 확인 실패)]



 a| 
SVRU
 a| 
오브젝트 저장소 알 수 없음 확인: 오브젝트 저장소에서 예기치 않은 오브젝트 데이터가 감지되었습니다.
 a| 
xref:svru-object-store-verify-unknown.adoc[SVRU: Object Store Verify Unknown]



 a| 
시스템
 a| 
노드 중지: 종료가 요청되었습니다.
 a| 
xref:sysd-node-stop.adoc[SYSD:노드 중지]



 a| 
시스템
 a| 
노드 중지: 서비스가 정상 중지를 시작했습니다.
 a| 
xref:syst-node-stopping.adoc[시스템:노드 중지 중]



 a| 
시스템
 a| 
노드 시작: 서비스가 시작되었고 이전 종료의 특성이 메시지에 표시됩니다.
 a| 
xref:sysu-node-start.adoc[SYSU: 노드 시작]



 a| 
VLST
 a| 
사용자가 시작한 볼륨 손실: '/proc/cMSI/Volume_lost' 명령이 실행되었습니다.
 a| 
xref:vlst-user-initiated-volume-lost.adoc[VLST: 사용자가 시작한 볼륨이 손실되었습니다]

|===
xref:lkcu-overwritten-object-cleanup.adoc[LKCU: 덮어쓴 개체 정리]
