---
permalink: audit/using-audit-explain-tool.html 
sidebar: sidebar 
keywords: storagegrid, audit, tool, audit-explain, audit explain, translate audit messages, translate messages, translate audit message, translate message 
summary: 감사 설명 도구를 사용하여 감사 로그의 감사 메시지를 읽기 쉬운 형식으로 변환할 수 있습니다. 
---
= 감사 설명 도구를 사용합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
감사-설명 도구를 사용하여 감사 로그의 감사 메시지를 읽기 쉬운 형식으로 변환할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 특정 액세스 권한이 있어야 합니다.
* "passwords.txt" 파일이 있어야 합니다.
* 기본 관리 노드의 IP 주소를 알아야 합니다.


기본 관리 노드에서 사용할 수 있는 감사 설명 도구는 감사 로그에 감사 메시지를 간단히 요약해 줍니다.


IMPORTANT: 감사-설명 도구는 주로 문제 해결 작업 중에 기술 지원 부서에서 사용하기 위한 것입니다. '감사 설명' 쿼리를 처리하면 StorageGRID 작업에 영향을 줄 수 있는 많은 CPU 성능이 소모될 수 있습니다.

이 예는 감사 설명 도구의 일반적인 출력을 보여줍니다. 이러한 4개의 SPUT 감사 메시지는 계정 ID 924847777680322627870이 있는 S3 테넌트가 S3 PUT 요청을 사용하여 "bucket1"이라는 이름의 버킷을 생성하고 해당 버킷에 3개의 오브젝트를 추가할 때 생성되었습니다.

[listing]
----
SPUT S3 PUT bucket bucket1 account:92484777680322627870 usec:124673
SPUT S3 PUT object bucket1/part1.txt tenant:92484777680322627870  cbid:9DCB157394F99FE5 usec:101485
SPUT S3 PUT object bucket1/part2.txt tenant:92484777680322627870  cbid:3CFBB07AB3D32CA9 usec:102804
SPUT S3 PUT object bucket1/part3.txt tenant:92484777680322627870  cbid:5373D73831ECC743 usec:93874
----
감사-설명 도구는 일반 감사 로그 또는 압축 감사 로그를 처리할 수 있습니다. 예를 들면 다음과 같습니다.

[listing]
----
audit-explain audit.log
----
[listing]
----
audit-explain 2019-08-12.txt.gz
----
감사-설명 도구는 동시에 여러 파일을 처리할 수도 있습니다. 예를 들면 다음과 같습니다.

[listing]
----
audit-explain audit.log 2019-08-12.txt.gz 2019-08-13.txt.gz
----
[listing]
----
audit-explain /var/local/audit/export/*
----
마지막으로, 감사-설명 도구는 파이프에서 입력을 받아 "grep" 명령이나 다른 방법을 사용하여 입력을 필터링하고 미리 처리할 수 있습니다. 예를 들면 다음과 같습니다.

[listing]
----
grep SPUT audit.log | audit-explain
----
[listing]
----
grep bucket-name audit.log | audit-explain
----
감사 로그는 매우 크고 구문 분석 속도가 느릴 수 있으므로 전체 파일 대신 파트에 대해 보고 실행할 부분을 필터링하여 시간을 절약할 수 있습니다.


NOTE: 감사 설명 도구는 압축된 파일을 파이프 입력 파일로 받아들이지 않습니다. 압축된 파일을 처리하려면 파일 이름을 명령줄 인수로 제공하거나 "zcat" 도구를 사용하여 먼저 파일의 압축을 풉니다. 예를 들면 다음과 같습니다.

[listing]
----
zcat audit.log.gz | audit-explain
----
사용 가능한 옵션을 보려면 도움말(-h) 옵션을 사용하십시오. 예를 들면 다음과 같습니다.

[listing]
----
 $ audit-explain -h
----
.단계
. 기본 관리자 노드에 로그인합니다.
+
.. 'ssh admin@_primary_Admin_Node_IP_' 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.


. 다음 명령을 입력합니다. 여기서 '/var/local/audit/export/audit.log'는 분석할 파일의 이름과 위치를 나타냅니다.
+
'$audit-exit/var/local/audit/export/audit.log'

+
감사-설명 도구는 지정된 파일 또는 파일의 모든 메시지에 대해 사람이 읽을 수 있는 해석을 인쇄합니다.

+

NOTE: 선 길이를 줄이고 가독성을 높이기 위해 타임스탬프가 기본적으로 표시되지 않습니다. 타임스탬프를 보려면 timestamp("-t") 옵션을 사용합니다.



xref:sput-s3-put.adoc[SPUT: S3 PUT]
