---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid-116
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - version-number: '11.6'
    url: "/storagegrid-116"
  - version-number: '12.0'
    url: "/storagegrid"
  - version-number: '11.9'
    url: "/storagegrid-119"
  - version-number: '11.8'
    url: "/storagegrid-118"
  - version-number: '11.7'
    url: "/storagegrid-117"
  - version-number: '11.5'
    url: "/storagegrid-115"
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: StorageGRID 11.6 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/release-notes/index.html"
  - title: 시작하십시오
    entries:
    - section: primer
    - section: network
  - title: 어플라이언스 하드웨어를 설치하고 유지 관리합니다
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: 소프트웨어 설치 및 업그레이드
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: 시스템 관리를 수행합니다
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: StorageGRID를 사용합니다
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: StorageGRID 모니터링 및 유지 관리
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: StorageGRID를 활성화합니다
    url: "/storagegrid-enable.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
