---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api 
summary: StorageGRID 11.6은 그리드 관리 API 버전 3을 사용합니다. 버전 3은 버전 2를 사용하지 않지만 버전 1과 버전 2는 계속 지원됩니다. 
---
= Grid Management API 변경
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.6은 그리드 관리 API 버전 3을 사용합니다. 버전 3은 버전 2를 사용하지 않지만 버전 1과 버전 2는 계속 지원됩니다.


IMPORTANT: StorageGRID 11.6에서 관리 API 버전 1 및 버전 2를 계속 사용할 수 있지만, 이러한 API 버전에 대한 지원은 StorageGRID의 향후 릴리스에서 제거됩니다. StorageGRID 11.6으로 업그레이드한 후, 'Put/grid/config/management' API를 사용하여 더 이상 사용되지 않는 v1 및 v2 API를 비활성화할 수 있다.

자세한 내용은 를 참조하십시오 xref:../admin/using-grid-management-api.adoc[Grid Management API를 사용합니다].



== 전용 API 작업을 위해 Swagger 문서에 액세스할 수 있습니다

이제 Grid Manager에서 전용 API에 대한 Swagger 문서에 액세스할 수 있습니다. 사용 가능한 작업을 보려면 Grid Manager 도움말 아이콘을 선택하고 * API Documentation * 을 선택합니다. 그런 다음 StorageGRID 관리 API 페이지에서 * 전용 API 설명서 * 로 이동 * 을 선택합니다.

StorageGRID 프라이빗 API는 사전 통지 없이 변경될 수 있습니다. StorageGRID 전용 엔드포인트도 요청의 API 버전을 무시합니다.



== 알람 기반 API는 더 이상 사용되지 않습니다

11.6 릴리스는 모든 알람 기반 API를 중단합니다. 다음 API는 이러한 변경의 영향을 받습니다.

* Get/Grid/alarms: fully deprecated
* 'Get/Grid/Health/Topology': 완전히 사용되지 않습니다
* Get/Grid/Health: 응답의 alarm-counts 섹션은 더 이상 사용되지 않습니다




== S3 액세스 키를 가져올 수 있습니다

이제 그리드 관리 API를 사용하여 테넌트 사용자용 S3 액세스 키를 가져올 수 있습니다. 예를 들어, 다른 S3 공급자의 액세스 키를 StorageGRID로 마이그레이션하거나 이 기능을 사용하여 그리드 간에 사용자 자격 증명을 동일하게 유지할 수 있습니다.


IMPORTANT: 이 기능을 활성화하면 테넌트 루트 암호 변경 권한이 있는 Grid Manager 사용자는 테넌트 데이터에 대한 모든 액세스 권한을 갖습니다. 테넌트 데이터를 보호하기 위해 사용 후 즉시 이 기능을 비활성화합니다.



== 신규 고객 운영

세 가지 새로운 '그리드/계정' API 작업이 추가되었습니다.

* 'POST/gridentsport/account-enable-s3-key-import': 이 요청은 S3 자격 증명 가져오기 기능을 활성화합니다. 이 기능을 사용하려면 루트 액세스 권한이 있어야 합니다.
* 'POST/gridi./accountsstsstimer/{id}si./{user_id}sihifacer/s3-access-keys': 이 요청은 테넌트 계정에서 지정된 사용자에 대한 S3 자격 증명을 가져옵니다. 루트 액세스 또는 테넌트 루트 암호 변경 권한이 있어야 하며 사용자 ID와 테넌트 계정 ID를 알고 있어야 합니다.
* 'POST/gridentsport/account-disable-s3-key-import': 이 요청은 S3 자격 증명 가져오기 기능을 비활성화합니다. 이 기능을 해제하려면 루트 액세스 권한이 있어야 합니다.




== 패치 메소드는 사용되지 않습니다

이제 패치 방법이 더 이상 사용되지 않으며 향후 릴리스에서 제거될 것입니다. 필요한 경우 패치 작업을 사용하여 리소스를 수정하는 대신 PUT 작업을 수행하여 리소스를 교체합니다.



== 그리드/로그/수집 엔드포인트에 추가

'grid/logs/collect' 끝점에 4개의 boolean 값이 추가되었습니다.

* "applicationLogs": 기술 지원 부서에서 문제 해결을 위해 가장 자주 사용하는 응용 프로그램별 로그입니다. 수집된 로그는 사용 가능한 애플리케이션 로그의 하위 집합입니다. 기본값은 true입니다.
* auditLogs: 정상적인 시스템 작동 중에 생성된 감사 메시지가 포함된 로그입니다. 기본값은 true입니다.
* 네트워크 추적: 네트워크 디버깅에 사용되는 로그입니다. 기본값은 false 입니다.
* 'prometheusDatabase': 모든 노드의 서비스에서 시계열 지표. 기본값은 false 입니다.




== 새로운 버전의 i.node-details/gridi./service-ids 엔드포인트

새로운 's./gridi./service-ids' 엔드포인트는 노드 UUID를 연관된 노드 이름, 서비스 ID 및 서비스 유형에 매핑하는 기능을 제공합니다.



== 그리드 노드 콘솔 암호를 검색할 수 있습니다

이제 'POST'(POST) 인수와 모눈인/노드-콘솔-비밀번호'를 사용하여 그리드 노드 및 관련 콘솔 비밀번호 목록을 검색할 수 있습니다.
