---
permalink: upgrade/docker-image-availability-check-error-messages.html 
sidebar: sidebar 
keywords: upgrade, error message, docker image availability 
summary: '업그레이드 프로세스를 시작하려고 할 때 "다음 문제는 Docker 이미지 가용성 검사 유효성 검사 제품군으로 확인되었습니다"라는 오류 메시지가 나타날 수 있습니다. 업그레이드를 완료하기 전에 모든 문제를 해결해야 합니다.' 
---
= "Docker 이미지 가용성 검사" 오류 메시지
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 프로세스를 시작하려고 할 때 ""다음 문제는 Docker 이미지 가용성 검사 검증 제품군으로 확인되었습니다."라는 오류 메시지가 나타날 수 있습니다. 업그레이드를 완료하기 전에 모든 문제를 해결해야 합니다.

식별된 문제를 해결하는 데 필요한 변경 사항을 잘 모르는 경우 기술 지원 부서에 문의하십시오.

[cols="1a,1a,1a"]
|===
| 메시지 | 원인 | 해결 방법 


 a| 
업그레이드 버전을 확인할 수 없습니다. 업그레이드 버전 정보 파일 '{file_path}'이(가) 예상 형식과 일치하지 않습니다.
 a| 
업그레이드 패키지가 손상되었습니다.
 a| 
업그레이드 패키지를 다시 업로드하고 다시 시도하십시오. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
업그레이드 버전 정보 파일 "{file_path}"을(를) 찾을 수 없습니다. 업그레이드 버전을 확인할 수 없습니다.
 a| 
업그레이드 패키지가 손상되었습니다.
 a| 
업그레이드 패키지를 다시 업로드하고 다시 시도하십시오. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
"{node_name}"에 현재 설치된 릴리스 버전을 확인할 수 없습니다.
 a| 
노드의 중요 파일이 손상되었습니다.
 a| 
기술 지원 부서에 문의하십시오.



 a| 
"{node_name}"에 버전을 나열하려고 시도하는 중 연결 오류가 발생했습니다
 a| 
노드가 오프라인이거나 연결이 끊어졌습니다.
 a| 
모든 노드가 온라인 상태이고 운영 관리 노드에서 연결할 수 있는지 확인한 후 다시 시도하십시오.



 a| 
노드 "{node_name}의 호스트에 로드된 StorageGRID "{upgrade_version}" 이미지가 없습니다. 업그레이드를 진행하기 전에 이미지와 서비스를 호스트에 설치해야 합니다.
 a| 
업그레이드 RPM 또는 DEB 패키지가 노드가 실행 중인 호스트에 설치되지 않았거나 이미지를 가져오는 중입니다.

* 참고: * 이 오류는 Linux에서 컨테이너로 실행되는 노드에만 적용됩니다.
 a| 
노드가 실행 중인 모든 Linux 호스트에 RPM 또는 DEB 패키지가 설치되었는지 확인합니다. 서비스 및 이미지 파일 모두에 대해 버전이 올바른지 확인합니다. 몇 분 정도 기다린 후 다시 시도하십시오.

을 참조하십시오 xref:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.adoc[Linux: 모든 호스트에 RPM 또는 DEB 패키지를 설치합니다].



 a| 
노드 "{node_name}"을(를) 확인하는 동안 오류가 발생했습니다
 a| 
예기치 않은 오류가 발생했습니다.
 a| 
몇 분 정도 기다린 후 다시 시도하십시오.



 a| 
사전 점검을 실행하는 동안 오류가 발생했습니다. '{error_string}'
 a| 
예기치 않은 오류가 발생했습니다.
 a| 
몇 분 정도 기다린 후 다시 시도하십시오.

|===