---
permalink: upgrade/obtaining-required-materials-for-software-upgrade.html 
sidebar: sidebar 
keywords: upgrade, requirements, rhel, red hat, linux, centOS, ubuntu, debian 
summary: 소프트웨어 업그레이드를 시작하기 전에 업그레이드를 성공적으로 완료할 수 있도록 필요한 모든 자료를 확보해야 합니다. 
---
= 소프트웨어 업그레이드에 필요한 자료를 확보합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
소프트웨어 업그레이드를 시작하기 전에 업그레이드를 성공적으로 완료할 수 있도록 필요한 모든 자료를 확보해야 합니다.

[cols="1a,3a"]
|===
| 항목 | 참고 


 a| 
StorageGRID 업그레이드 파일
 a| 
<<Download the StorageGRID upgrade files>> 서비스 랩톱으로 이동합니다.



 a| 
서비스 노트북
 a| 
서비스 랩톱의 구성 요소:

* 네트워크 포트
* SSH 클라이언트(예: PuTTY)




 a| 
xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저]
 a| 
브라우저 지원은 일반적으로 각 StorageGRID 릴리스에 대한 변경 사항을 적용합니다. 브라우저가 새 StorageGRID 버전과 호환되는지 확인합니다.



 a| 
복구 패키지(".zip") 파일
 a| 
<<Download the Recovery Package>> 업그레이드하기 전에 파일을 안전한 위치에 저장하십시오. 복구 패키지 파일을 사용하면 오류가 발생할 경우 시스템을 복원할 수 있습니다.



 a| 
"passwords.txt" 파일
 a| 
이 파일은 복구 패키지 .zip 파일의 일부인 해당 패키지에 포함되어 있습니다. 최신 버전의 복구 패키지를 구해야 합니다.



 a| 
프로비저닝 암호
 a| 
StorageGRID 시스템을 처음 설치할 때 암호가 생성되고 문서화됩니다. 프로비저닝 암호는 passwords.txt 파일에 나열되지 않습니다.



 a| 
관련 문서
 a| 
* xref:../release-notes/index.adoc[릴리스 정보] StorageGRID 11.6용. 업그레이드를 시작하기 전에 이 내용을 주의 깊게 읽으십시오.
* 에 대한 지침 xref:../admin/index.adoc[StorageGRID 관리].
* Linux 배포를 업그레이드하는 경우 Linux 플랫폼에 대한 StorageGRID 설치 지침:
+
** xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS를 설치합니다]
** xref:../ubuntu/index.adoc[Ubuntu 또는 Debian을 설치합니다]


* 기타 StorageGRID 문서(필요 시)


|===


== StorageGRID 업그레이드 파일을 다운로드합니다

노드가 설치된 위치에 따라 하나 이상의 파일을 다운로드해야 합니다.

* 모든 플랫폼 *: '.upgrade' 파일


Linux 호스트에 노드가 배포된 경우 업그레이드를 시작하기 전에 설치할 RPM 또는 DEB 아카이브도 다운로드해야 합니다.

* * Red Hat Enterprise Linux 또는 CentOS *: 추가 RPM 파일(".zip" 또는".tgz")
* * Ubuntu 또는 Debian *: 추가 DEB 파일(".zip" 또는".tgz")


.단계
. 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^].
. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 * GO * 를 선택합니다.
+
StorageGRID 소프트웨어 버전의 형식은 11._x. y _ 입니다. StorageGRID 핫픽스의 형식은 11._x.x.x.z _ 입니다.

. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. Caution/MustRead 문이 나타나면 해당 문을 읽고 확인란을 선택합니다.
+
이 설명은 릴리스에 필요한 핫픽스가 있는 경우에 나타납니다.

. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
+
선택한 버전의 다운로드 페이지가 나타납니다. 이 페이지에는 세 개의 열이 있습니다.

+
** StorageGRID를 설치합니다
** StorageGRID를 업그레이드합니다
** StorageGRID 어플라이언스에 대한 지원 파일


. Upgrade StorageGRID * 열에서 '.upgrade' 아카이브를 선택하여 다운로드합니다.
+
모든 플랫폼에는 '.upgrade' 아카이브가 필요합니다.

. Linux 호스트에 노드가 배포된 경우 RPM 또는 DEB 아카이브도 '.tgz' 또는 '.zip' 형식으로 다운로드합니다. 서비스 랩톱에서 Windows를 실행 중인 경우 '.zip' 파일을 선택합니다.
+
** Red Hat Enterprise Linux 또는 CentOS +'s torageGRID-Webscale-_version_-RPM-_UniqueID_.zip" +'torageGRID-Webscale-_version_-RPM-_UniqueID_.tgz'
** Ubuntu 또는 Debian+'torageGRID-Webscale-_version_-deb-_UniqueID_.zip"+'torageGRID-Webscale-_version_-deb-_UniqueID_.tgz"
+

NOTE: SG100 또는 SG1000에는 추가 파일이 필요하지 않습니다.







== 복구 패키지를 다운로드합니다

복구 패키지 파일을 사용하면 오류가 발생할 경우 StorageGRID 시스템을 복원할 수 있습니다. 그리드 토폴로지를 StorageGRID 시스템으로 변경하거나 소프트웨어를 업그레이드하기 전에 현재 복구 패키지 파일을 다운로드합니다. 그런 다음 그리드 토폴로지를 변경한 후 또는 소프트웨어를 업그레이드한 후 복구 패키지의 새 복사본을 다운로드합니다.

.무엇을 &#8217;필요로 할거야
* 를 사용하여 그리드 관리자에 로그인해야 합니다 xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저].
* 프로비저닝 암호가 있어야 합니다.
* 특정 액세스 권한이 있어야 합니다.


.단계
. 유지보수 * > * 시스템 * > * 복구 패키지 * 를 선택합니다.
. 프로비저닝 암호를 입력하고 * 다운로드 시작 * 을 선택합니다.
+
다운로드가 즉시 시작됩니다.

. 다운로드가 완료되면 다음을 수행합니다.
+
.. '.zip' 파일을 엽니다.
.. GPT-backup 디렉토리와 내부 .zip 파일이 포함되어 있는지 확인합니다.
.. 안쪽 '.zip' 파일의 압축을 풉니다.
.. 비밀번호.txt 파일을 열 수 있는지 확인합니다.


. 다운로드한 복구 패키지 파일('.zip')을 두 개의 안전하고 서로 다른 위치에 복사합니다.
+

IMPORTANT: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 보안을 유지해야 합니다.


