---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 11.6 
summary: 이번 StorageGRID 릴리즈에는 다음과 같은 기능이 도입되었습니다. 
---
= StorageGRID 11.6의 새로운 기능
:icons: font
:imagesdir: ../media/


[role="lead"]
이번 StorageGRID 릴리즈에는 다음과 같은 기능이 도입되었습니다.



== 사용 편의성 향상

Grid Manager 사용자 인터페이스는 사용자 환경을 개선하기 위해 크게 재설계되었습니다.

* 새로운 사이드바가 이전 사용자 인터페이스의 풀다운 메뉴를 대체합니다.
* 관련 옵션을 함께 유지하기 위해 여러 메뉴가 재구성되었습니다. 예를 들어, * 구성 * 메뉴에는 인증서, 키 관리 서버, 프록시 설정 및 신뢰할 수 없는 클라이언트 네트워크 옵션에 대한 새로운 * 보안 * 섹션이 포함되어 있습니다.
* 머리글 표시줄의 * 검색 * 필드를 사용하면 그리드 관리자 페이지로 빠르게 이동할 수 있습니다.
* 노드 * 페이지의 요약 테이블은 사용된 개체 데이터 및 사용된 개체 메타데이터와 같은 모든 사이트 및 노드에 대한 상위 수준의 정보를 제공하며 새로운 검색 필드를 포함합니다. 경고 아이콘은 활성 경고가 있는 노드 옆에 표시됩니다.
* 새로운 마법사는 관리 그룹, 관리 사용자, 테넌트, 로드 밸런서 엔드포인트, 고가용성(HA) 그룹에 대한 워크플로우 등 더욱 복잡한 구성을 안내합니다.
* 모든 UI 페이지는 업데이트된 글꼴, 단추 스타일 및 표 형식으로 다시 스타일을 지정했습니다.
+

NOTE: 기능 변경이 없는 한 StorageGRID 11.6 문서 사이트의 스크린샷은 새로운 그리드 관리자 페이지 스타일을 반영하도록 업데이트되지 않았습니다.



다음을 참조하십시오.

* xref:../admin/index.adoc[StorageGRID 관리]
* xref:../monitor/index.adoc[모니터링하고 문제를 해결합니다]




== 여러 VLAN 인터페이스

이제 관리 노드 및 게이트웨이 노드에 대한 VLAN(가상 LAN) 인터페이스를 생성할 수 있습니다. HA 그룹 및 로드 밸런서 끝점에서 VLAN 인터페이스를 사용하여 클라이언트 트래픽을 격리하고 파티셔닝하여 보안, 유연성 및 성능을 확보할 수 있습니다.

* 새로운 * VLAN 인터페이스 생성 * 마법사는 VLAN ID를 입력하고 하나 이상의 노드에서 상위 인터페이스를 선택하는 과정을 안내합니다. 상위 인터페이스는 그리드 네트워크, 클라이언트 네트워크 또는 VM 또는 베어 메탈 호스트에 대한 추가 트렁크 인터페이스가 될 수 있습니다. 을 참조하십시오 xref:../admin/configure-vlan-interfaces.html[VLAN 인터페이스를 구성합니다].
* 이제 노드에 추가 트렁크 또는 액세스 인터페이스를 추가할 수 있습니다. 트렁크 인터페이스를 추가하는 경우 VLAN 인터페이스를 구성해야 합니다. 액세스 인터페이스를 추가할 경우 인터페이스를 HA 그룹에 직접 추가할 수 있으며, VLAN 인터페이스를 구성할 필요가 없습니다. 다음을 참조하십시오.
+
** * Linux(노드 설치 전) *: <<Installation enhancements>>
** * Linux(노드 설치 후) *: xref:../maintain/linux-adding-trunk-or-access-interfaces-to-node.adoc[Linux: 노드에 트렁크 또는 액세스 인터페이스를 추가합니다]
** * VMware(노드 설치 후) *: xref:../vmware/collecting-information-about-your-deployment-environment.adoc[배포 환경에 대한 정보를 수집합니다]






== Azure AD를 사용하여 ID 페더레이션을 수행할 수 있습니다

이제 그리드 관리자 또는 테넌트 관리자에 대한 ID 페더레이션을 구성할 때 Azure Active Directory(Azure AD)를 ID 소스로 선택할 수 있습니다. 을 참조하십시오 xref:../admin/using-identity-federation.adoc[ID 페더레이션을 사용합니다].



== Azure AD 및 PingFederate를 SSO에 사용할 수 있습니다

이제 그리드에 대한 SSO(Single Sign-On)를 구성할 때 Azure AD 또는 PingFederate를 SSO 유형으로 선택할 수 있습니다. 그런 다음 sandbox 모드를 사용하여 각 StorageGRID 관리 노드에 대한 Azure AD 엔터프라이즈 애플리케이션 또는 PingFederate 서비스 공급자(SP) 연결을 구성 및 테스트할 수 있습니다. 을 참조하십시오 xref:../admin/configuring-sso.adoc[Single Sign-On 구성].



== 중앙 집중식 인증서 관리

* 새 인증서 페이지(* 구성 * > * 보안 * > * 인증서 *)는 모든 StorageGRID 보안 인증서에 대한 정보를 단일 위치로 통합합니다. 새 페이지에서 StorageGRID 글로벌, 그리드 CA 및 클라이언트 인증서를 관리하거나 로드 밸런서 엔드포인트, 테넌트 및 ID 통합에 사용되는 인증서 등의 다른 인증서에 대한 정보를 볼 수 있습니다. 을 참조하십시오 xref:../admin/using-storagegrid-security-certificates.adoc[보안 인증서 정보].
* 이 변경의 일환으로 다음 글로벌 인증서의 이름이 변경되었습니다.
+
** 관리 인터페이스 서버 인증서 * 는 이제 * 관리 인터페이스 인증서 * 입니다.
** 이제 * 오브젝트 스토리지 API 서비스 엔드포인트 서버 인증서 * (스토리지 API 서버 인증서라고도 함)가 * S3 및 Swift API 인증서 * 입니다.
** 내부 CA 인증서 *, * 시스템 CA 인증서 *, * CA 인증서 * 및 * 기본 CA 인증서 * 는 이제 항상 * 그리드 CA 인증서 * 라고 합니다.






== 기타 그리드 관리자 기능 향상

* * 고가용성(HA) 그룹에 대한 업데이트 *. 이제 마법사가 HA 그룹 생성 프로세스를 안내합니다. 을 참조하십시오 xref:../admin/configure-high-availability-group.html[고가용성 그룹을 구성합니다].
+
** 그리드 네트워크(eth0) 또는 클라이언트 네트워크(eth2)에서 인터페이스를 선택하는 것 외에도 이제 VLAN 인터페이스 또는 노드에 추가한 액세스 인터페이스를 선택할 수 있습니다.
** 이제 인터페이스의 우선 순위 순서를 지정할 수 있습니다. 기본 인터페이스를 선택하고 각 백업 인터페이스의 순서를 지정할 수 있습니다.
** S3, Swift, 관리 또는 테넌트 클라이언트가 다른 서브넷의 HA 그룹에 대한 VIP 주소에 액세스할 경우 이제 게이트웨이의 IP 주소를 제공할 수 있습니다.


* * 밸런서 엔드포인트를 로드하기 위한 업데이트 *. 로드 밸런서 끝점을 만드는 과정을 안내하는 새 마법사도 있습니다. 을 참조하십시오 xref:../admin/configuring-load-balancer-endpoints.adoc[로드 밸런서 엔드포인트를 구성합니다].
+
** 이제 엔드포인트를 생성한 후 이 세부 정보를 추가하는 대신 끝점을 처음 생성할 때 클라이언트 유형(S3 또는 Swift)을 선택합니다.
** 이제 별도의 인증서를 업로드하거나 생성하는 대신 로드 밸런서 끝점에 글로벌 * StorageGRID S3 및 Swift 인증서 * 를 사용할 수 있습니다.
+

NOTE: 이 글로벌 인증서는 이전에 사용되지 않는 CLB 서비스 및 스토리지 노드에 연결하는 데 사용되었습니다. 로드 밸런서 끝점에 글로벌 인증서를 사용하려면 S3 및 Swift API 인증서 페이지에 사용자 지정 인증서를 업로드해야 합니다.







== 새로운 테넌트 관리자 기능

* * 새로운 실험 S3 콘솔 *. 테넌트 관리자의 Bucket 페이지에서 링크로 사용할 수 있는 새로운 실험 S3 콘솔을 통해 S3 테넌트 사용자는 버킷의 오브젝트를 보고 관리할 수 있습니다. 을 참조하십시오 xref:../tenant/use-s3-console.adoc[Experimental S3 Console을 사용합니다].



IMPORTANT: 실험적인 S3 콘솔은 완전히 테스트되지 않았으며 대량의 오브젝트 관리 또는 운영 환경에서 사용하기 위한 것이 아닙니다. 테넌트는 소수의 오브젝트 또는 개념 증명 또는 비운영 그리드를 사용하는 경우에만 S3 콘솔을 사용해야 합니다.

* * 여러 S3 버킷을 삭제할 수 있습니다 *. 이제 테넌트 사용자는 한 번에 둘 이상의 S3 버킷을 삭제할 수 있습니다. 삭제할 각 버킷은 비어 있어야 합니다. 을 참조하십시오 xref:../tenant/deleting-s3-bucket.adoc[S3 버킷을 삭제합니다].
* * 테넌트 계정 권한 업데이트 *. 테넌트 계정 권한이 있는 그룹에 속하는 관리자 사용자는 이제 기존 트래픽 분류 정책을 볼 수 있습니다. 이전에는 이러한 메트릭을 보려면 사용자에게 루트 액세스 권한이 있어야 했습니다.




== 새로운 업그레이드 및 핫픽스 프로세스

* StorageGRID 업그레이드 * 페이지가 다시 설계되었습니다(* 유지보수 * > * 시스템 * > * 소프트웨어 업데이트 * > * StorageGRID 업그레이드 *).
* StorageGRID 11.6으로의 업그레이드가 완료된 후 그리드 관리자를 사용하여 향후 릴리스로 업그레이드하고 해당 릴리스에 대한 핫픽스를 동시에 적용할 수 있습니다. StorageGRID 업그레이드 페이지에는 권장 업그레이드 경로가 표시되며 올바른 다운로드 페이지로 직접 연결됩니다.
* AutoSupport 페이지의 새 * 소프트웨어 업데이트 확인 * 확인란을 사용하여 이 기능을 제어할 수 있습니다(* 지원 * > * 도구 * > * AutoSupport *). 시스템에 WAN 액세스 권한이 없는 경우 사용 가능한 소프트웨어 업데이트 확인을 비활성화할 수 있습니다. 을 참조하십시오 xref:../admin/configure-autosupport-grid-manager.adoc#disable-checks-for-software-updates[AutoSupport & GT 구성, 소프트웨어 업데이트 확인 비활성화].
+

NOTE: StorageGRID 11.6으로 업그레이드하려면 스크립트를 사용하여 동시에 핫픽스를 업그레이드하고 적용할 수도 있습니다. 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["NetApp 기술 자료: StorageGRID에 대한 주요 업그레이드 및 핫픽스 스크립트를 모두 실행하는 방법"^].

* 이제 나중에 업그레이드를 완료해야 하는 경우 SANtricity OS 업그레이드를 일시 중지하고 일부 노드의 업그레이드를 건너뛸 수 있습니다. 스토리지 어플라이언스에 대한 지침을 참조하십시오.
+
** xref:../sg5600/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5600.adoc[그리드 관리자(SG5600)를 사용하여 스토리지 컨트롤러의 SANtricity OS 업그레이드]
** xref:../sg5700/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5700.adoc[그리드 관리자(SG5700)를 사용하여 스토리지 컨트롤러에서 SANtricity OS 업그레이드]
** xref:../sg6000/upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.adoc[SG6000(Grid Manager)를 사용하여 스토리지 컨트롤러에서 SANtricity OS 업그레이드]






== 외부 syslog 서버 지원

* 이제 감사 메시지와 StorageGRID 로그의 하위 집합을 원격으로 저장하고 관리하려는 경우 외부 syslog 서버를 구성할 수 있습니다(* 구성 * > * 모니터링 * > * 감사 및 syslog 서버 *). 외부 syslog 서버를 구성한 후 감사 메시지와 특정 로그 파일을 로컬, 원격 또는 둘 다 저장할 수 있습니다. 감사 정보의 대상을 구성하면 관리 노드의 네트워크 트래픽을 줄일 수 있습니다. 을 참조하십시오 xref:../monitor/configure-audit-messages.adoc[감사 메시지 및 로그 대상을 구성합니다].
* 이 기능과 관련하여 로그 페이지(* support*>* Tools*>* Logs*)의 새 확인란을 사용하면 특정 응용 프로그램 로그, 감사 로그, 네트워크 디버깅에 사용되는 로그 및 Prometheus 데이터베이스 로그 등 수집할 로그 유형을 지정할 수 있습니다. 을 참조하십시오 xref:../monitor/collecting-log-files-and-system-data.adoc[로그 파일 및 시스템 데이터를 수집합니다].




== S3 를 선택합니다

이제 S3 테넌트가 개별 오브젝트에 SelectObjectContent 요청을 발급하도록 선택적으로 허용할 수 있습니다. S3 Select를 사용하면 데이터베이스와 관련 리소스를 배치하지 않고도 대량의 데이터를 효율적으로 검색할 수 있습니다. 또한, 데이터를 검색하는 데 드는 비용과 대기 시간도 줄어듭니다. 을 참조하십시오 xref:../admin/manage-s3-select-for-tenant-accounts.adoc[관리 S3 테넌트 계정에 대해 선택] 및 xref:../s3/use-s3-select.adoc[S3 Select를 사용합니다].

S3 선택 작업에 대한 Grafana 차트도 추가되었습니다. 을 참조하십시오 xref:../monitor/reviewing-support-metrics.adoc[지원 메트릭을 검토합니다].



== S3 오브젝트 잠금 기본 버킷 보존 기간

S3 오브젝트 잠금을 사용하는 경우 이제 버킷의 기본 보존 기간을 지정할 수 있습니다. 기본 보존 기간은 고유한 보존 설정이 없는 버킷에 추가된 모든 객체에 적용됩니다. 을 참조하십시오 xref:../s3/using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다].



== Google Cloud Platform 지원

이제 GCP(Google Cloud Platform)를 클라우드 스토리지 풀 및 CloudMirror 플랫폼 서비스의 엔드포인트로 사용할 수 있습니다. 을 참조하십시오 xref:../tenant/specifying-urn-for-platform-services-endpoint.adoc[플랫폼 서비스 끝점의 URN을 지정합니다] 및 xref:../ilm/creating-cloud-storage-pool.adoc[클라우드 스토리지 풀을 생성합니다].



== AWS C2S 지원

이제 CloudMirror 복제에 AWS C2S(Commercial Cloud Services) 엔드포인트를 사용할 수 있습니다. 을 참조하십시오 xref:../tenant/creating-platform-services-endpoint.adoc[플랫폼 서비스 끝점을 만듭니다].



== 기타 S3 변경

* * 다중 파트 개체에 대한 객체 및 헤드 객체 지원 *. 이전에는 StorageGRID가 객체 가져오기 또는 헤드 객체 요청에서 'PARTNUMBER' 요청 매개 변수를 지원하지 않았습니다. 이제 가져오기 및 헤드 요청을 발급하여 다중 파트 개체의 특정 부분을 검색할 수 있습니다. Get 및 Head Object 는 또한 X-amz-MP-parts-count 응답 요소를 지원하여 개체에 포함된 파트 수를 나타냅니다.
* * "사용 가능한" 정합성 보장 컨트롤로 변경 *. 이제 "사용 가능한" 정합성 제어는 "새 쓰기 후 읽기" 정합성 보장 수준과 동일하게 작동하지만 헤드 및 GET 작업에 대한 최종 일관성을 제공합니다. "사용 가능한" 일관성 제어는 스토리지 노드를 사용할 수 없는 경우 "새 쓰기 후 읽기"보다 헤드 및 GET 작업에 더 높은 가용성을 제공합니다. 헤드 및 GET 작업에 대한 Amazon S3 정합성 보장과 다릅니다.
+
xref:../s3/index.adoc[S3을 사용합니다]





== 성능 향상

* * 스토리지 노드는 20억 개의 오브젝트를 지원할 수 있습니다 *. 스토리지 노드의 기본 디렉토리 구조는 확장성 및 성능 향상을 위해 최적화되었습니다. 이제 스토리지 노드는 추가 하위 디렉토리를 사용하여 최대 20억 개의 복제된 객체를 저장하고 성능을 최대화합니다. StorageGRID 11.6으로 업그레이드하면 노드 하위 디렉토리가 수정되지만 기존 객체가 새 디렉토리에 재배포되지 않습니다.
* * 고성능 어플라이언스 * 에서 ILM 기반 삭제 성능이 향상되었습니다. ILM 삭제 작업을 수행하는 데 사용되는 리소스 및 처리량은 이제 각 StorageGRID 어플라이언스 노드의 크기와 기능에 맞게 조정됩니다. SG5600 어플라이언스의 경우 처리량은 StorageGRID 11.5의 처리량과 동일합니다. SG5700 어플라이언스의 경우 ILM 삭제 성능이 소개선되었습니다. RAM이 더 많고 CPU가 더 많은 SG6000 어플라이언스의 경우 ILM이 더 빠르게 처리됩니다. 이러한 성능 향상은 All-Flash SGF6024 어플라이언스에서 특히 두드러집니다.
* * 최적화된 스토리지 볼륨 워터마크 *. 이전 릴리즈에서는 모든 스토리지 노드의 모든 스토리지 볼륨에 세 개의 스토리지 볼륨 워터마크가 적용되었습니다. 이제 StorageGRID는 스토리지 노드의 크기와 볼륨의 상대적 용량을 기준으로 각 스토리지 볼륨에 대해 이러한 워터마크를 최적화할 수 있습니다. 을 참조하십시오 xref:../admin/what-storage-volume-watermarks-are.adoc[스토리지 볼륨 워터마크란 무엇입니까].
+
최적화된 배경무늬는 모든 신규 및 대부분의 업그레이드된 StorageGRID 11.6 시스템에 자동으로 적용됩니다. 최적화된 워터마크는 이전 기본 설정보다 큽니다.

+
사용자 지정 워터마크를 사용하는 경우 업그레이드 후 * 읽기 전용 로우 워터마크 무시 * 알림이 트리거될 수 있습니다. 이 알림을 통해 사용자 지정 배경무늬 설정이 너무 작지 여부를 알 수 있습니다. 을 참조하십시오 xref:../monitor/troubleshoot-low-watermark-alert.adoc[낮은 읽기 전용 배경무늬 재정의 알림 문제 해결].

+
이 변경의 일환으로 두 가지 Prometheus 메트릭이 추가되었습니다.

+
** 'toragegrid_storage_volume_minimum_optimized_soft_readonly_watermark'
** 'toragegrid_storage_volume_maximum_optimized_soft_readonly_watermark'


* * 허용되는 최대 메타데이터 공간이 증가되었습니다 *. 스토리지 노드에 허용되는 최대 메타데이터 공간은 용량이 더 큰 노드의 경우 3.96TB(2.64TB)로 증가했으며, 이는 4TB가 넘는 메타데이터에 대해 실제 예약된 공간이 있는 노드입니다. 이 새로운 값을 통해 더 많은 오브젝트 메타데이터를 특정 스토리지 노드에 저장할 수 있으며 StorageGRID 메타데이터 용량을 최대 50% 늘릴 수 있습니다.
+

NOTE: 아직 그렇게 하지 않은 경우 스토리지 노드의 RAM이 충분하고 볼륨 0에 충분한 공간이 있으면 이 작업을 수행할 수 있습니다 xref:../upgrade/increasing-metadata-reserved-space-setting.adoc[설치 또는 업그레이드 후 메타데이터 예약 공간 설정을 수동으로 최대 8TB까지 늘립니다].

+
** xref:../admin/managing-object-metadata-storage.adoc#allowed-metadata-space[오브젝트 메타데이터 스토리지 및 GT 관리, 허용되는 메타데이터 공간]
** xref:../upgrade/increasing-metadata-reserved-space-setting.adoc[메타데이터 예약 공간 증가 설정을 사용합니다]






== 유지 관리 절차 및 지원 도구의 개선 사항

* * 노드 콘솔 암호를 변경할 수 있습니다 *. 이제 그리드 관리자를 사용하여 노드 콘솔 암호를 변경할 수 있습니다(* 구성 * > * 액세스 제어 * > * 그리드 암호 *). 이러한 암호는 SSH를 사용하여 노드에 "admin"으로 로그인하거나 VM/물리적 콘솔 연결의 루트 사용자에게 로그인하는 데 사용됩니다. 을 참조하십시오 xref:../admin/change-node-console-password.adoc[노드 콘솔 암호를 변경합니다].
* * 새 개체 존재 확인 마법사 *. 이제 포그라운드 확인 절차를 대체하는 사용하기 쉬운 개체 존재 확인 마법사(* maintenance*>* Tasks*>* Object existence check*)를 사용하여 개체 무결성을 확인할 수 있습니다. 새로운 절차를 완료하는 데 걸리는 시간은 1/3로, 동시에 여러 노드를 확인할 수 있습니다. 을 참조하십시오 xref:../monitor/verifying-object-integrity.html[개체 무결성을 확인합니다].
* * EC 재조정 및 EC 수리 작업에 대한 "예상 완료 시간" 차트 *. 이제 현재 EC 재조정 또는 EC 수리 작업의 예상 완료 시간 및 완료 비율을 볼 수 있습니다.
* * 복제된 데이터 복구에 대한 예상 완료율 *. 이제 'show-replicated-repair-status' 옵션을 'repair-data' 명령에 추가하여 복제된 복구에 대한 예상 완료율을 확인할 수 있습니다.
+

IMPORTANT: StorageGRID 11.6의 기술 미리 보기에는 '복제된-수리-상태' 옵션이 제공됩니다. 이 기능은 개발 중이며 반환된 값이 잘못되었거나 지연될 수 있습니다. 수리가 완료되었는지 확인하려면 복구 절차에 설명된 대로 * Awaiting-all *, * repair attemptated(XRPA *) 및 * Scan Period - Estimated(XSCM) * 를 계속 사용합니다.

* 이제 진단 페이지(* 지원 * > * 도구 * > * 진단 *)의 결과가 심각도별로 정렬된 다음 알파벳순으로 정렬됩니다.
* Prometheus 및 Grafana가 수정된 인터페이스 및 차트를 사용하여 최신 버전으로 업데이트되었습니다. 이 변경의 일환으로 일부 메트릭의 레이블이 변경되었습니다.
+
** node_network_up의 레이블을 사용한 사용자 지정 쿼리가 있는 경우 대신 node_network_info의 레이블을 사용해야 합니다.
** NODE_NETWORK 메트릭의 레이블 이름 "interface"를 사용했다면 대신 DEVICE 레이블을 사용해야 합니다.


* 이전에는 Prometheus 메트릭이 31일 동안 관리 노드에 저장되었습니다. 이제 Prometheus 데이터에 예약된 공간이 가득 찰 때까지 메트릭이 저장되므로 기간별 메트릭을 사용할 수 있는 시간이 크게 증가할 수 있습니다.
+
'/var/local/mysql_ibdata/' 볼륨이 용량에 도달하면 가장 오래된 메트릭이 먼저 삭제됩니다.





== 설치 개선 사항

* 이제 Red Hat Enterprise Linux를 설치하는 동안 Podman을 컨테이너로 사용할 수 있습니다. 이전에는 StorageGRID에서 Docker 컨테이너만 지원했습니다.
* StorageGRID용 API 스키마는 이제 RedHat Enterprise Linux/CentOS, Ubuntu/Debian 및 VMware 플랫폼의 설치 아카이브에 포함됩니다. 아카이브를 추출한 후 '/Extras/API-schemas' 폴더에서 스키마를 찾을 수 있습니다.
* 이제 베어 메탈 배포를 위한 노드 구성 파일의 'BLOCK_DEVICE_RANGEDB' 키는 2자리 숫자가 아니라 3자리 숫자가 되어야 합니다. 즉, block_device_RANGEDB_nn 대신 block_device_RANGEDB_nnn을 지정해야 합니다.
+
기존 배포와의 호환성을 위해 업그레이드된 노드에는 2자리 키가 계속 지원됩니다.

* 베어 메탈 배포를 위해 새 'interfaces_target_nnnn' 키의 인스턴스를 노드 구성 파일에 선택적으로 추가할 수 있습니다. 각 키는 베어 메탈 호스트의 물리적 인터페이스에 대한 이름과 설명을 제공하며, 이 이름은 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시됩니다.
+
** xref:../rhel/creating-node-configuration-files.adoc[Red Hat Enterprise Linux 또는 CentOS 배포용 노드 구성 파일을 생성합니다]
** xref:../ubuntu/creating-node-configuration-files.adoc[Ubuntu 또는 Debian 배포용 노드 구성 파일을 만듭니다]






== 새 경고

StorageGRID 11.6에 대해 다음과 같은 새 경고가 추가되었습니다.

* 감사 로그가 인메모리 대기열에 추가되고 있습니다
* Cassandra 테이블 손상
* EC 재조정 실패
* EC 복구 실패
* EC 복구가 중단되었습니다
* S3 및 Swift API에 대한 글로벌 서버 인증서 만료
* 외부 syslog CA 인증서 만료
* 외부 syslog 클라이언트 인증서 만료
* 외부 syslog 서버 인증서 만료
* 외부 syslog 서버 전달 오류입니다
* 테넌트의 ID 페더레이션 동기화 실패
* 레거시 CLB 로드 밸런서 활동이 감지되었습니다
* 로그가 디스크 대기열에 추가되고 있습니다
* 읽기 전용 로우 워터마크가 무시됩니다
* tmp 디렉토리 여유 공간이 부족합니다
* 개체 존재 여부를 확인하지 못했습니다
* 개체 존재 검사가 중단되었습니다
* S3 PUT 오브젝트 크기가 너무 큽니다


를 참조하십시오 xref:../monitor/alerts-reference.adoc[경고 참조].



== 감사 메시지의 변경

* ORLM: 개체 규칙이 감사 메시지를 충족했습니다. 새 * BUID * 필드가 ORLM: 개체 규칙에 추가되었습니다. BUID * 필드에는 내부 작업에 사용되는 버킷 ID가 표시됩니다. 새 필드는 메시지 상태가 PRGD인 경우에만 나타납니다.
* 새 * SGRP * 필드가 다음 감사 메시지에 추가되었습니다. SGRP * 필드는 인제스트된 위치와 다른 사이트에서 객체가 삭제된 경우에만 표시됩니다.
+
** IDEL: ILM 삭제 시작
** OVWR: 개체 덮어쓰기
** SDEL: S3 삭제
** WDEL: Swift 삭제




을 참조하십시오 xref:../audit/index.adoc[감사 로그를 검토합니다].



== StorageGRID 설명서 변경 사항

StorageGRID 11.6 설명서 사이트의 모양과 느낌이 수정되었으며 이제 GitHub를 기본 플랫폼으로 사용합니다.

NetApp은 콘텐츠에 대한 피드백을 감사하며 제품 문서의 모든 페이지에서 제공되는 새로운 "문서 변경 요청" 기능을 이용하도록 권장합니다. 또한 문서 플랫폼은 GitHub 사용자를 위한 임베디드 콘텐츠 기여 기능을 제공합니다.

이 문서를 살펴보고 이 문서에 기고하십시오. 편집, 변경 요청 또는 피드백 전송만 가능합니다.
