---
permalink: sg100-1000/configuring-snmp-settings-for-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, SNMP, configure, setup, set up 
summary: 하드웨어에 대한 SNMP 구성에 익숙한 경우 BMC 인터페이스를 사용하여 서비스 어플라이언스에 대한 SNMP 설정을 구성할 수 있습니다. 보안 커뮤니티 문자열을 제공하고, SNMP 트랩을 활성화하고, 최대 5개의 SNMP 대상을 지정할 수 있습니다. 
---
= 서비스 어플라이언스에 대한 SNMP 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어에 대한 SNMP 구성에 익숙한 경우 BMC 인터페이스를 사용하여 서비스 어플라이언스에 대한 SNMP 설정을 구성할 수 있습니다. 보안 커뮤니티 문자열을 제공하고, SNMP 트랩을 활성화하고, 최대 5개의 SNMP 대상을 지정할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* BMC 대시보드에 액세스하는 방법을 알고 있습니다.
* SNMPv1-v2c 장비에 대한 SNMP 설정을 구성한 경험이 있습니다.



NOTE: 이 절차에서 만든 BMC 설정은 어플라이언스에 장애가 발생하여 교체해야 하는 경우 유지되지 않을 수 있습니다. 하드웨어 교체 후 필요한 경우 쉽게 다시 적용할 수 있도록 적용한 모든 설정에 대한 기록이 있어야 합니다.

.단계
. BMC 대시보드에서 * 설정 * > * SNMP 설정 * 을 선택합니다.
. SNMP 설정 페이지에서 * SNMP V1/V2 * 활성화 를 선택한 다음 읽기 전용 커뮤니티 문자열과 읽기/쓰기 커뮤니티 문자열을 제공합니다.
+
읽기 전용 커뮤니티 문자열은 사용자 ID 또는 암호와 같습니다. 침입자가 네트워크 설정에 대한 정보를 얻지 못하게 하려면 이 값을 변경해야 합니다. 읽기-쓰기 커뮤니티 문자열은 인증되지 않은 변경으로부터 장치를 보호합니다.

. 필요에 따라 * 트랩 사용 * 을 선택하고 필요한 정보를 입력합니다.
+

IMPORTANT: IP 주소를 사용하여 각 SNMP 트랩의 대상 IP를 입력합니다. 정규화된 도메인 이름은 지원되지 않습니다.

+
서비스 어플라이언스가 비정상 상태일 때 SNMP 콘솔에 즉시 알림을 보내도록 하려면 트랩을 활성화합니다. 트랩은 링크 상승/하강 상태, 특정 임계값을 초과하는 온도 또는 높은 트래픽을 나타낼 수 있습니다.

. 필요에 따라 * 테스트 트랩 전송 * 을 클릭하여 설정을 테스트합니다.
. 설정이 올바르면 * 저장 * 을 클릭합니다.

