---
permalink: sg100-1000/replacing-services-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, Replacing, replace, remove, removing, removal, install, installing, installation 
summary: 제품이 최적의 상태로 작동하지 않거나 고장 난 경우 교체해야 할 수 있습니다. 
---
= 서비스 어플라이언스를 교체하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
제품이 최적의 상태로 작동하지 않거나 고장 난 경우 교체해야 할 수 있습니다.

.필요한 것
* 교체 중인 제품과 동일한 부품 번호를 가진 교체용 제품이 있습니다.
* 제품에 연결된 각 케이블을 식별할 수 있는 라벨이 있습니다.
* 있습니다 xref:locating-controller-in-data-center.adoc[제품을 물리적으로 위치했습니다].
* 제품이 다 되었습니다 xref:placing-appliance-into-maintenance-mode.adoc[유지보수 모드로 전환되었습니다].


.이 작업에 대해
어플라이언스를 교체하는 동안에는 StorageGRID 노드에 액세스할 수 없습니다. 제품이 충분히 작동하는 경우 이 절차를 시작할 때 제어된 종료를 수행할 수 있습니다.


NOTE: StorageGRID 소프트웨어를 설치하기 전에 어플라이언스를 교체하는 경우 이 절차를 완료한 후 StorageGRID 어플라이언스 설치 프로그램에 즉시 액세스하지 못할 수 있습니다. 어플라이언스와 동일한 서브넷에 있는 다른 호스트에서 StorageGRID 어플라이언스 설치 프로그램에 액세스할 수 있지만 다른 서브넷에 있는 호스트에서는 액세스할 수 없습니다. 이 상태는 15분 이내에(원래 어플라이언스의 ARP 캐시 항목이 시간 초과될 때) 저절로 해결되거나 로컬 라우터 또는 게이트웨이에서 수동으로 이전 ARP 캐시 항목을 삭제하여 즉시 상태를 지울 수 있습니다.

.단계
. 제품이 유지보수 모드로 전환되면 제품을 종료하십시오.
+
.. 그리드 노드에 로그인합니다.
+
... 'ssh admin@_grid_node_ip_' 명령을 입력합니다
... "passwords.txt" 파일에 나열된 암호를 입력합니다.
... 루트로 전환하려면 다음 명령을 입력합니다
... "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



.. 제품을 종료한다: + ` * shutdown -h now * '


. 다음 두 가지 방법 중 하나를 사용하여 제품의 전원이 꺼져 있는지 확인하십시오.
+
** 제품 전면에 있는 전원 표시등 LED가 꺼져 있습니다.
** BMC 인터페이스의 전원 제어 페이지에는 어플라이언스가 꺼져 있음을 나타냅니다.


. 어플라이언스에 연결된 StorageGRID 네트워크가 DHCP 서버를 사용하는 경우 DNS/네트워크 및 IP 주소 설정을 업데이트합니다.
+
.. 어플라이언스 전면에서 MAC 주소 레이블을 찾아 관리 네트워크 포트의 MAC 주소를 확인합니다.
+

NOTE: MAC 주소 레이블에는 BMC 관리 포트의 MAC 주소가 나열됩니다.

+
관리 네트워크 포트의 MAC 주소를 확인하려면 레이블의 16진수에 * 2 * 를 추가해야 합니다. 예를 들어 레이블의 MAC 주소가 * 09 * 로 끝나는 경우 관리 포트의 MAC 주소는 * 0B * 로 끝납니다. 레이블의 MAC 주소가 * (_y_) FF * 로 끝나는 경우 관리 포트의 MAC 주소는 * (_y_+1) 01 * 로 끝납니다. Windows에서 계산기를 열고, Programmer 모드로 설정하고, Hex를 선택하고, MAC 주소를 입력한 다음, * + 2 = * 를 입력하여 이 계산을 쉽게 수행할 수 있습니다.

.. 제거한 어플라이언스의 DNS/네트워크 및 IP 주소를 대체 어플라이언스의 MAC 주소와 연관시킬 것을 네트워크 관리자에게 요청하십시오.
+

IMPORTANT: 교체 어플라이언스에 전원을 공급하려면 먼저 원래 어플라이언스의 모든 IP 주소가 업데이트되었는지 확인해야 합니다. 그렇지 않으면 장치가 부팅될 때 새 DHCP IP 주소를 받게 되며 StorageGRID에 다시 연결할 수 없게 됩니다. 이 단계는 어플라이언스에 연결된 모든 StorageGRID 네트워크에 적용됩니다.

+

NOTE: 원래 어플라이언스가 고정 IP 주소를 사용하는 경우 새 어플라이언스는 제거된 어플라이언스의 IP 주소를 자동으로 채택합니다.



. 다음 방법으로 제품을 분리하고 교체하십시오.
+
.. 케이블에 레이블을 지정한 다음 케이블과 모든 네트워크 트랜시버를 분리합니다.
+

IMPORTANT: 성능 저하를 방지하려면 케이블을 비틀거나 접거나 끼거나 밟지 마십시오.

.. 캐비닛 또는 랙에서 고장난 어플라이언스를 제거합니다.
.. 장애가 발생한 어플라이언스에서 2개의 전원 공급 장치, 8개의 냉각 팬 및 2개의 SSD를 교체 어플라이언스로 전송합니다.
+
이러한 구성 요소 교체에 대한 지침을 따릅니다.

.. 캐비닛 또는 랙에 교체용 어플라이언스를 설치합니다.
.. 케이블 및 광학 트랜시버를 교체합니다.
.. 제품의 전원을 켜고 어플라이언스 LED 및 부팅 코드를 모니터링합니다.
+
BMC 인터페이스를 사용하여 부팅 상태를 모니터링합니다.



. 어플라이언스 노드가 그리드 관리자에 표시되고 경고가 나타나지 않는지 확인합니다.


.관련 정보
xref:installing-appliance-in-cabinet-or-rack-sg100-and-sg1000.adoc[캐비닛 또는 랙에 어플라이언스 설치(SG100 및 SG1000)]

xref:viewing-status-indicators-on-sg100-and-sg1000-appliances.adoc[SG100 및 SG1000 어플라이언스의 상태 표시기를 봅니다]

xref:viewing-boot-up-codes-for-appliance-sg100-and-sg1000.adoc[어플라이언스의 부팅 코드를 봅니다]
