---
permalink: sg100-1000/sg100-and-sg1000-applications.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, applications, how to use, services 
summary: 게이트웨이 서비스를 제공하는 다양한 방법과 일부 그리드 관리 서비스의 이중화를 위해 StorageGRID 서비스 어플라이언스를 구성할 수 있습니다. 
---
= SG100 및 SG1000 응용 프로그램
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
게이트웨이 서비스를 제공하는 다양한 방법과 일부 그리드 관리 서비스의 이중화를 위해 StorageGRID 서비스 어플라이언스를 구성할 수 있습니다.

어플라이언스는 다음과 같은 방법으로 배포할 수 있습니다.

* 새 그리드 또는 기존 그리드를 게이트웨이 노드로 추가합니다
* 새 그리드에 기본 또는 비 기본 관리 노드로 추가하거나 기존 그리드에 비 기본 관리 노드로 추가합니다
* 게이트웨이 노드 및 관리 노드(기본 또는 비기본)로 동시에 작동합니다


이 어플라이언스를 사용하면 고가용성(HA) 그룹과 S3 또는 Swift 데이터 경로 연결을 위한 지능형 로드 밸런싱을 손쉽게 사용할 수 있습니다.

다음 예에서는 제품의 기능을 극대화하는 방법을 설명합니다.

* 2개의 SG100 또는 2개의 SG1000 어플라이언스를 사용하여 게이트웨이 노드로 구성하여 게이트웨이 서비스를 제공하십시오.
+

IMPORTANT: SG100 및 SG1000 서비스 어플라이언스를 같은 사이트에 배포하지 마십시오. 성능을 예측할 수 없습니다.

* 일부 그리드 관리 서비스의 이중화를 제공하려면 SG100 또는 SG1000 어플라이언스 2개를 사용하십시오. 각 어플라이언스를 관리자 노드로 구성하여 이 작업을 수행합니다.
* 2개의 SG100 또는 2개의 SG1000 어플라이언스를 사용하여 하나 이상의 가상 IP 주소를 통해 액세스되는 고가용성 로드 밸런싱 및 트래픽 셰이핑 서비스를 제공합니다. 이 작업을 수행하려면 관리 노드 또는 게이트웨이 노드의 조합으로 어플라이언스를 구성하고 두 노드를 동일한 HA 그룹에 추가합니다.
+

IMPORTANT: 동일한 HA 그룹에서 관리 노드와 게이트웨이 노드를 사용하는 경우 CLB(연결 로드 밸런서) 포트와 관리 노드 전용 포트는 페일오버되지 않습니다. HA 그룹 구성에 대한 지침은 StorageGRID 관리 지침을 참조하십시오.

+

NOTE: CLB 서비스는 더 이상 사용되지 않습니다.



SG100과 SG1000 서비스 어플라이언스를 StorageGRID 스토리지 어플라이언스와 함께 사용하면 외부 하이퍼바이저 또는 컴퓨팅 하드웨어에 종속되지 않고 어플라이언스 전용 그리드를 구축할 수 있습니다.

xref:../admin/index.adoc[StorageGRID 관리]
