---
permalink: harden/hardening-guidelines-for-storagegrid-nodes.html 
sidebar: sidebar 
keywords: hardening guidelines, nodes, security 
summary: StorageGRID 노드는 VMware 가상 머신, Linux 호스트의 컨테이너 엔진 내부 또는 전용 하드웨어 어플라이언스에 구축할 수 있습니다. 각 플랫폼 유형과 각 노드 유형에는 강화 모범 사례가 포함되어 있습니다. 
---
= StorageGRID 노드에 대한 강화 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 노드는 VMware 가상 머신, Linux 호스트의 컨테이너 엔진 내부 또는 전용 하드웨어 어플라이언스에 구축할 수 있습니다. 각 플랫폼 유형과 각 노드 유형에는 강화 모범 사례가 포함되어 있습니다.



== 방화벽 구성

시스템 강화 프로세스의 일환으로 외부 방화벽 구성을 검토하고 트래픽이 IP 주소 및 해당 IP 주소가 반드시 필요한 포트에서만 허용되도록 수정해야 합니다.

StorageGRID는 자동으로 관리되는 내부 방화벽을 사용합니다. 이 내부 방화벽은 일부 일반적인 위협에 대한 추가 보호 계층을 제공하지만 외부 방화벽의 필요성을 제거하지 않습니다.

StorageGRID에서 사용하는 모든 내부 및 외부 포트 목록은 해당 플랫폼의 설치 가이드를 참조하십시오.



== 가상화, 컨테이너 및 공유 하드웨어

모든 StorageGRID 노드의 경우 신뢰할 수 없는 소프트웨어와 동일한 물리적 하드웨어에서 StorageGRID를 실행하지 마십시오. StorageGRID와 맬웨어가 모두 동일한 물리적 하드웨어에 존재할 경우 하이퍼바이저 보호를 통해 맬웨어가 StorageGRID로 보호되는 데이터에 액세스하지 못할 것이라고 가정하지 마십시오. 예를 들어 멜트다운 및 스펙터 공격은 최신 프로세서의 중요한 취약점을 악용하고 프로그램이 동일한 컴퓨터의 메모리에 있는 데이터를 훔칠 수 있도록 합니다.



== 사용하지 않는 서비스를 비활성화합니다

모든 StorageGRID 노드에 대해 사용하지 않는 서비스에 대한 액세스를 비활성화하거나 차단해야 합니다. 예를 들어 CIFS 또는 NFS에 대한 감사 공유에 대한 클라이언트 액세스를 구성하지 않을 경우 이러한 서비스에 대한 액세스를 차단하거나 해제합니다.



== 설치하는 동안 노드를 보호합니다

노드가 설치될 때 신뢰할 수 없는 사용자가 네트워크를 통해 StorageGRID 노드에 액세스하도록 허용하지 마십시오. 노드가 그리드에 가입될 때까지 완전히 보안되지 않습니다.



== 관리 노드에 대한 지침

관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 그리드 관리자 또는 테넌트 관리자에 로그인할 때 관리 노드에 연결됩니다.

다음 지침에 따라 StorageGRID 시스템의 관리 노드를 보호합니다.

* 인터넷에 있는 클라이언트와 같이 신뢰할 수 없는 클라이언트의 모든 관리 노드를 보호합니다. 신뢰할 수 없는 클라이언트가 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크의 관리 노드에 액세스할 수 있는지 확인합니다.
* StorageGRID 그룹은 그리드 관리자 및 테넌트 관리자 기능에 대한 액세스를 제어합니다. 각 사용자 그룹에 역할에 필요한 최소 권한을 부여하고 읽기 전용 액세스 모드를 사용하여 사용자가 구성을 변경하지 못하도록 합니다.
* StorageGRID 로드 밸런서 끝점을 사용할 때는 신뢰할 수 없는 클라이언트 트래픽에 관리자 노드 대신 게이트웨이 노드를 사용합니다.
* 신뢰할 수 없는 테넌트가 있는 경우 테넌트 관리자 또는 테넌트 관리 API에 대한 직접 액세스 권한을 허용하지 마십시오. 대신 신뢰할 수 없는 테넌트가 테넌트 관리 API와 상호 작용하는 테넌트 포털 또는 외부 테넌트 관리 시스템을 사용하도록 합니다.
* 선택적으로 관리 프록시를 사용하여 관리 노드에서 NetApp 지원으로 AutoSupport 통신을 더 많이 제어할 수 있습니다. StorageGRID 관리 지침에 있는 관리자 프록시 생성 단계를 참조하십시오.
* 필요에 따라 제한된 8443 및 9443 포트를 사용하여 Grid Manager 및 Tenant Manager 통신을 분리합니다. 추가 보호를 위해 공유 포트 443을 차단하고 테넌트 요청을 포트 9443으로 제한합니다.
* 선택적으로 그리드 관리자 및 테넌트 사용자에 대해 별도의 관리 노드를 사용합니다.


자세한 내용은 StorageGRID 관리 지침을 참조하십시오.



== 스토리지 노드 지침

스토리지 노드: 오브젝트 데이터 및 메타데이터를 관리하고 저장합니다. 다음 지침에 따라 StorageGRID 시스템의 스토리지 노드를 보호합니다.

* 신뢰할 수 없는 클라이언트가 스토리지 노드에 직접 연결하도록 허용하지 않습니다. 게이트웨이 노드 또는 타사 로드 밸런서가 제공하는 로드 밸런서 끝점을 사용합니다.
* 신뢰할 수 없는 테넌트에 대해 아웃바운드 서비스를 활성화하지 마십시오. 예를 들어, 신뢰할 수 없는 테넌트의 계정을 생성할 때 테넌트가 자신의 ID 소스를 사용하도록 허용하지 않고 플랫폼 서비스의 사용을 허용하지 않습니다. StorageGRID 관리 지침에 있는 테넌트 계정 생성 단계를 참조하십시오.
* 신뢰할 수 없는 클라이언트 트래픽에 타사 로드 밸런서를 사용합니다. 타사 로드 밸런싱은 더 많은 제어 기능과 공격에 대한 추가적인 보호 계층을 제공합니다.
* 필요한 경우 스토리지 프록시를 사용하여 스토리지 노드에서 외부 서비스로의 클라우드 스토리지 풀 및 플랫폼 서비스 통신을 보다 효과적으로 제어할 수 있습니다. StorageGRID 관리 지침에 있는 스토리지 프록시 생성 단계를 참조하십시오.
* 선택적으로 클라이언트 네트워크를 사용하여 외부 서비스에 연결합니다. 그런 다음 * 구성 * > * 네트워크 * > * 신뢰할 수 없는 클라이언트 네트워크 * 를 선택하고 스토리지 노드의 클라이언트 네트워크를 신뢰할 수 없음을 표시합니다. 스토리지 노드는 더 이상 클라이언트 네트워크에서 들어오는 트래픽을 허용하지 않지만 플랫폼 서비스에 대한 아웃바운드 요청은 계속 허용합니다.




== 게이트웨이 노드에 대한 지침

게이트웨이 노드는 클라이언트 애플리케이션이 StorageGRID에 연결하는 데 사용할 수 있는 선택적 로드 밸런싱 인터페이스를 제공합니다. 다음 지침에 따라 StorageGRID 시스템의 게이트웨이 노드를 보호합니다.

* 게이트웨이 노드에서 CLB 서비스를 사용하는 대신 로드 밸런서 끝점을 구성하고 사용합니다. StorageGRID 관리에 대한 지침은 로드 밸런싱 관리 단계를 참조하십시오.
+

NOTE: CLB 서비스는 더 이상 사용되지 않습니다.

* 신뢰할 수 없는 클라이언트 트래픽에 대해 클라이언트와 게이트웨이 노드 또는 스토리지 노드 간에 타사 로드 밸런서를 사용합니다. 타사 로드 밸런싱은 더 많은 제어 기능과 공격에 대한 추가적인 보호 계층을 제공합니다. 타사 로드 밸런서를 사용하는 경우에도 내부 로드 밸런서 엔드포인트를 통과하도록 네트워크 트래픽을 선택적으로 구성하거나 스토리지 노드로 직접 보내도록 구성할 수 있습니다.
* 부하 분산 엔드포인트를 사용하는 경우 선택적으로 클라이언트가 클라이언트 네트워크를 통해 접속하도록 합니다. 그런 다음 * 구성 * > * 네트워크 * > * 신뢰할 수 없는 클라이언트 네트워크 * 를 선택하고 게이트웨이 노드의 클라이언트 네트워크를 신뢰할 수 없음을 표시합니다. 게이트웨이 노드는 로드 밸런서 끝점으로 명시적으로 구성된 포트의 인바운드 트래픽만 허용합니다.




== 하드웨어 어플라이언스 노드에 대한 지침입니다

StorageGRID 하드웨어 어플라이언스는 StorageGRID 시스템에서 사용하도록 특별히 설계되었습니다. 일부 어플라이언스는 스토리지 노드로 사용할 수 있습니다. 다른 어플라이언스를 관리 노드 또는 게이트웨이 노드로 사용할 수 있습니다. 어플라이언스 노드를 소프트웨어 기반 노드와 결합하거나 완전히 엔지니어링된 모든 어플라이언스 그리드를 구축할 수 있습니다.

StorageGRID 시스템에서 하드웨어 어플라이언스 노드를 보호하려면 다음 지침을 따르십시오.

* 어플라이언스가 스토리지 컨트롤러 관리에 SANtricity System Manager를 사용하는 경우 신뢰할 수 없는 클라이언트가 네트워크를 통해 SANtricity System Manager에 액세스하지 못하도록 합니다.
* 어플라이언스에 BMC(베이스보드 관리 컨트롤러)가 있는 경우 BMC 관리 포트가 낮은 수준의 하드웨어 액세스를 허용한다는 점에 유의하십시오. BMC 관리 포트는 안전하고 신뢰할 수 있는 내부 관리 네트워크에만 연결합니다. 이러한 네트워크를 사용할 수 없는 경우 기술 지원 부서에서 BMC 연결을 요청하지 않는 한 BMC 관리 포트는 연결되지 않거나 차단된 상태로 둡니다.
* 어플라이언스가 IPMI(Intelligent Platform Management Interface) 표준을 사용하여 이더넷을 통한 컨트롤러 하드웨어의 원격 관리를 지원하는 경우 포트 623에서 신뢰할 수 없는 트래픽을 차단합니다.
* 어플라이언스의 스토리지 컨트롤러에 FDE 또는 FIPS 드라이브가 포함되어 있고 드라이브 보안 기능이 활성화된 경우 SANtricity를 사용하여 드라이브 보안 키를 구성하십시오.
* FDE 또는 FIPS 드라이브가 없는 어플라이언스의 경우 KMS(Key Management Server)를 사용하여 노드 암호화를 활성화합니다.


StorageGRID 하드웨어 어플라이언스의 설치 및 유지보수 지침을 참조하십시오.

.관련 정보
* xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS를 설치합니다]
* xref:../ubuntu/index.adoc[Ubuntu 또는 Debian을 설치합니다]
* xref:../vmware/index.adoc[VMware를 설치합니다]
* xref:../admin/index.adoc[StorageGRID 관리]
* xref:../tenant/index.adoc[테넌트 계정을 사용합니다]
* xref:../sg100-1000/index.adoc[SG100 및 SG1000 서비스 어플라이언스]
* xref:../sg5600/index.adoc[SG5600 스토리지 어플라이언스]
* xref:../sg5700/index.adoc[SG5700 스토리지 어플라이언스]
* xref:../sg6000/index.adoc[SG6000 스토리지 어플라이언스]

