---
permalink: swift/get-container-consistency-request.html 
sidebar: sidebar 
keywords: get container consistency request 
summary: 정합성 보장 레벨은 오브젝트의 가용성과 서로 다른 스토리지 노드 및 사이트에서 이러한 오브젝트의 일관성 간에 균형을 전환합니다. 컨테이너 일관성 가져오기 요청을 사용하면 특정 컨테이너에 적용되는 일관성 수준을 확인할 수 있습니다. 
---
= 컨테이너 일관성 요청 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정합성 보장 레벨은 오브젝트의 가용성과 서로 다른 스토리지 노드 및 사이트에서 이러한 오브젝트의 일관성 간에 균형을 전환합니다. 컨테이너 일관성 가져오기 요청을 사용하면 특정 컨테이너에 적용되는 일관성 수준을 확인할 수 있습니다.



== 요청하십시오

|===
| HTTP 헤더를 요청합니다 | 설명 


 a| 
X-Auth-Token
 a| 
요청에 사용할 계정의 Swift 인증 토큰을 지정합니다.



 a| 
'x-ntap-sg-consistency'
 a| 
요청 유형을 지정합니다. 여기서 true는 컨테이너 일관성을 얻고 false는 컨테이너를 가져옵니다.



 a| 
호스트
 a| 
요청이 전달되는 호스트 이름입니다.

|===


== 요청 예

[listing]
----
GET /v1/28544923908243208806/Swift container
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: true
Host: test.com
----


== 응답

|===
| 응답 HTTP 헤더 | 설명 


 a| 
다
 a| 
응답의 날짜 및 시간입니다.



 a| 
'연결'을 선택합니다
 a| 
서버에 대한 연결이 열려 있는지 또는 닫혀 있는지 여부



 a| 
X-Trans-ID
 a| 
요청에 대한 고유한 트랜잭션 식별자입니다.



 a| 
콘텐츠 길이
 a| 
응답 바디의 길이.



 a| 
'x-ntap-sg-consistency'
 a| 
컨테이너에 적용되는 정합성 보장 제어 레벨입니다. 지원되는 값은 다음과 같습니다.

* * ALL *: 모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.
* * strong-global *: 모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.
* * strong-site *: 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.
* * read-after-new-write *: 새 객체에 대한 읽기 후 쓰기 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공
+
* 참고 *: 응용 프로그램이 존재하지 않는 개체에 대한 헤드 요청을 사용하는 경우 하나 이상의 스토리지 노드를 사용할 수 없는 경우 500개의 내부 서버 오류가 발생할 수 있습니다. 이러한 오류를 방지하려면 "사용 가능" 수준을 사용하십시오.

* * Available * (헤드 작업의 최종 일관성): "read-after-new-write" 정합성 수준과 동일하게 동작하지만 헤드 작업에 대한 최종 정합성 보장만 제공합니다. 스토리지 노드를 사용할 수 없는 경우 "새 쓰기 후"보다 헤드 작업에 더 높은 가용성을 제공합니다.


|===


== 응답 예

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
x-ntap-sg-consistency: strong-site
----
.관련 정보
xref:../tenant/index.adoc[테넌트 계정을 사용합니다]
