---
permalink: swift/object-operations.html 
sidebar: sidebar 
keywords: swift object operations 
summary: 객체에 대해 다음과 같은 Swift API 작업이 수행됩니다. 
---
= 오브젝트 작업
:icons: font
:imagesdir: ../media/


[role="lead"]
객체에 대해 다음과 같은 Swift API 작업이 수행됩니다.



== 개체를 삭제합니다

이 작업은 StorageGRID 시스템에서 개체의 콘텐츠 및 메타데이터를 삭제합니다.

다음 요청 매개 변수가 필요합니다.

* '계정'입니다
* 컨테이너
* '개체'


다음 요청 헤더가 필요합니다.

* X-Auth-Token


성공적으로 실행하면 HTTP/1.1 204 No Content 응답이 있는 다음 응답 헤더가 반환됩니다.

* 콘텐츠 길이
* 콘텐츠 유형
* 다
* X-Trans-ID


오브젝트 삭제 요청을 처리할 때 StorageGRID는 저장된 모든 위치에서 오브젝트의 모든 복사본을 즉시 제거하려고 시도합니다. 성공하면 StorageGRID는 즉시 클라이언트에 응답을 반환합니다. 위치를 일시적으로 사용할 수 없기 때문에 30초 이내에 모든 복사본을 제거할 수 없는 경우 StorageGRID는 제거할 복사본을 대기시킨 다음 클라이언트에 성공 여부를 표시합니다.

개체 삭제 방법에 대한 자세한 내용은 정보 수명 주기 관리를 사용하여 개체 관리 지침을 참조하십시오.



== 객체를 가져옵니다

이 작업은 개체 콘텐츠를 검색하고 StorageGRID 시스템에서 개체 메타데이터를 가져옵니다.

다음 요청 매개 변수가 필요합니다.

* '계정'입니다
* 컨테이너
* '개체'


다음 요청 헤더가 필요합니다.

* X-Auth-Token


다음 요청 헤더는 선택 사항입니다.

* 인코딩 수락
* IF-MATCH
* If-Modified-Since
* "If-None-Match"
* "수정되지 않은 경우 - 이후"
* "범위"


성공적으로 실행하면 HTTP/1.1 200 OK 응답이 있는 다음 헤더가 반환됩니다.

* '수용 범위'
* Content-Disposition은 Content-Disposition 메타데이터가 설정된 경우에만 반환됩니다
* Content-Encoding은 Content-Encoding 메타데이터가 설정된 경우에만 반환됩니다
* 콘텐츠 길이
* 콘텐츠 유형
* 다
* 'ETag'
* 마지막 수정일
* X-타임스탬프
* X-Trans-ID




== 머리 물체

이 작업은 StorageGRID 시스템에서 수집된 개체의 메타데이터 및 속성을 검색합니다.

다음 요청 매개 변수가 필요합니다.

* '계정'입니다
* 컨테이너
* '개체'


다음 요청 헤더가 필요합니다.

* X-Auth-Token


성공적으로 실행하면 "HTTP/1.1 200 OK" 응답과 함께 다음 헤더가 반환됩니다.

* '수용 범위'
* Content-Disposition은 Content-Disposition 메타데이터가 설정된 경우에만 반환됩니다
* Content-Encoding은 Content-Encoding 메타데이터가 설정된 경우에만 반환됩니다
* 콘텐츠 길이
* 콘텐츠 유형
* 다
* 'ETag'
* 마지막 수정일
* X-타임스탬프
* X-Trans-ID




== 개체를 넣습니다

이 작업을 실행하면 새 개체가 데이터와 메타데이터로 만들어지거나 기존 개체를 StorageGRID 시스템의 데이터 및 메타데이터로 바꿉니다.

StorageGRID는 최대 5TiB(5,497,558,138,880바이트)의 오브젝트를 지원합니다.


IMPORTANT: 동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "최신" 평가 시기는 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 하며, Swift 클라이언트가 작업을 시작하는 시점이 아닙니다.

다음 요청 매개 변수가 필요합니다.

* '계정'입니다
* 컨테이너
* '개체'


다음 요청 헤더가 필요합니다.

* X-Auth-Token


다음 요청 헤더는 선택 사항입니다.

* 'Content-Disposition'
* 콘텐츠 인코딩
+
개체에 적용되는 ILM 규칙이 크기에 따라 개체를 필터링하고 수집 시 동기식 배치(Ingest 동작에 대한 균형 또는 엄격 옵션)를 사용하는 경우 청크된 "콘텐츠 인코딩"을 사용하지 마십시오.

* 전송 인코딩
+
개체에 적용되는 ILM 규칙이 크기에 따라 개체를 필터링하고 수집 시 동기식 배치(Ingest 동작에 대한 균형 또는 엄격 옵션)를 사용하는 경우 압축 또는 청크된 "전송 인코딩"을 사용하지 마십시오.

* 콘텐츠 길이
+
ILM 규칙이 크기를 기준으로 오브젝트를 필터링하고 수집 시 동기 배치를 사용하는 경우 'Content-Length'를 지정해야 합니다.

+

NOTE: Content-Encoding, Transfer-Encoding, Content-Length에 대한 지침을 따르지 않을 경우 StorageGRID는 개체 크기를 결정하고 ILM 규칙을 적용하기 전에 개체를 저장해야 합니다. 다시 말해, StorageGRID은 수집 중인 오브젝트의 중간 복사본을 기본적으로 생성해야 합니다. 즉, StorageGRID는 Ingest 동작에 대해 이중 커밋 옵션을 사용해야 합니다.

+
동기 배치 및 ILM 규칙에 대한 자세한 내용은 정보 수명 주기 관리를 통해 개체 관리 지침을 참조하십시오.

* 콘텐츠 유형
* 'ETag'
* 'X-Object-Meta-<name\>'(객체 관련 메타데이터)
+
ILM 규칙의 참조 시간으로 * 사용자 정의 작성 시간 * 옵션을 사용하려면 값을 사용자 정의 헤더("X-Object-Meta-Creation-Time")에 저장해야 합니다. 예를 들면 다음과 같습니다.

+
[listing]
----
X-Object-Meta-Creation-Time: 1443399726
----
+
이 필드는 1970년 1월 1일 이후 초 단위로 평가됩니다.

* X-Storage-Class: reduced_redundancy가 있습니다
+
수집된 개체와 일치하는 ILM 규칙이 이중 커밋 또는 균형 설정의 수집 동작을 지정하는 경우 이 헤더는 StorageGRID에서 만드는 개체 복사본 수에 영향을 줍니다.

+
** * 이중 커밋 *: ILM 규칙이 Ingest 동작에 대한 이중 커밋 옵션을 지정하는 경우 StorageGRID는 오브젝트가 수집될 때(단일 커밋) 단일 임시 복사본을 만듭니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하는 경우 StorageGRID은 시스템에서 규칙에 지정된 모든 사본을 즉시 만들 수 없는 경우에만 단일 중간 복사본을 만듭니다. StorageGRID에서 동기 배치를 수행할 수 있는 경우 이 머리글은 영향을 주지 않습니다.
+
reducted_redundancy' 헤더는 개체와 일치하는 ILM 규칙이 복제된 단일 복사본을 만들 때 가장 적합합니다. 이 경우 'REDED_READITORY'를 사용하면 모든 수집 작업에 대해 불필요한 오브젝트 복사본을 생성하고 삭제할 필요가 없습니다.

+
다른 상황에서는 수집 중에 오브젝트 데이터가 손실될 위험이 있기 때문에 reducted_redundancy" 헤더를 사용하지 않는 것이 좋습니다. 예를 들어, ILM 평가가 발생하기 전에 실패한 스토리지 노드에 단일 복사본이 처음 저장되는 경우 데이터가 손실될 수 있습니다.

+

IMPORTANT: 복제된 복사본이 항상 하나만 있으면 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.



+
reducted_redundancy를 지정하면 개체를 처음 인제스트할 때 생성되는 복사본 수에만 영향을 줍니다. 활성 ILM 정책에 따라 개체를 평가할 때 개체의 복사본 수에 영향을 주지 않으며 StorageGRID 시스템의 낮은 수준의 중복성에 데이터가 저장되지 않습니다.



성공적으로 실행하면 "HTTP/1.1 201 created" 응답으로 다음 헤더가 반환됩니다.

* 콘텐츠 길이
* 콘텐츠 유형
* 다
* 'ETag'
* 마지막 수정일
* X-Trans-ID


xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:monitoring-and-auditing-operations.adoc[운영 모니터링 및 감사]
