---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications 
summary: 'StorageGRID 내부 방화벽은 포트 22, 80, 123 및 443\을 제외한 그리드 네트워크의 특정 포트에 대한 들어오는 연결만 허용합니다(외부 통신에 대한 정보 참조\). 로드 밸런서 끝점에 의해 정의된 포트에서도 연결이 허용됩니다.' 
---
= 내부 그리드 노드 통신
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 내부 방화벽은 포트 22, 80, 123 및 443을 제외한 그리드 네트워크의 특정 포트에 대한 들어오는 연결만 허용합니다(외부 통신에 대한 정보 참조). 로드 밸런서 끝점에 의해 정의된 포트에서도 연결이 허용됩니다.


NOTE: 그리드 노드 간 ICMP(Internet Control Message Protocol) 트래픽을 사용하는 것이 좋습니다. ICMP 트래픽을 허용하면 그리드 노드에 도달할 수 없을 때 장애 조치 성능을 향상시킬 수 있습니다.

StorageGRID는 표에 나열된 ICMP 및 포트 외에도 VRRP(가상 라우터 이중화 프로토콜)를 사용합니다. VRRP는 IP 프로토콜 번호 112를 사용하는 인터넷 프로토콜입니다. StorageGRID는 유니캐스트 모드에서만 VRRP를 사용합니다. VRRP는 경우에만 필요합니다 xref:../admin/managing-high-availability-groups.adoc[고가용성 그룹] 구성됩니다.



== Linux 기반 노드에 대한 지침

엔터프라이즈 네트워킹 정책이 이러한 포트에 대한 액세스를 제한하는 경우 배포 구성 매개 변수를 사용하여 배포 시 포트를 다시 매핑할 수 있습니다. 포트 재매핑 및 배포 구성 매개 변수에 대한 자세한 내용은 다음을 참조하십시오.

* xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS를 설치합니다]
* xref:../ubuntu/index.adoc[Ubuntu 또는 Debian을 설치합니다]




== VMware 기반 노드에 대한 지침입니다

VMware 네트워킹 외부의 방화벽 제한을 정의해야 하는 경우에만 다음 포트를 구성합니다.

엔터프라이즈 네트워킹 정책이 이러한 포트에 대한 액세스를 제한하는 경우 VMware vSphere Web Client를 사용하여 노드를 구축하거나 그리드 노드 구축을 자동화할 때 구성 파일 설정을 사용하여 포트를 재매핑할 수 있습니다. 포트 재매핑 및 배포 구성 매개 변수에 대한 자세한 내용은 을 참조하십시오xref:../vmware/index.adoc[VMware를 설치합니다].



== 어플라이언스 노드에 대한 지침

엔터프라이즈 네트워킹 정책에서 이러한 포트에 대한 액세스를 제한하는 경우 StorageGRID 어플라이언스 설치 프로그램을 사용하여 포트를 재매핑할 수 있습니다. 어플라이언스의 포트 재매핑에 대한 자세한 내용은 다음을 참조하십시오.

* xref:../sg100-1000/index.adoc[SG100 및 SG1000 서비스 어플라이언스]
* xref:../sg6000/index.adoc[SG6000 스토리지 어플라이언스]
* xref:../sg5700/index.adoc[SG5700 스토리지 어플라이언스]
* xref:../sg5600/index.adoc[SG5600 스토리지 어플라이언스]




== StorageGRID 내부 포트

|===


| 포트 | TCP 또는 UDP입니다 | 보낸 사람 | 를 선택합니다 | 세부 정보 


 a| 
22
 a| 
TCP
 a| 
기본 관리자 노드
 a| 
모든 노드
 a| 
유지 관리 절차의 경우 기본 관리 노드는 포트 22에서 SSH를 사용하여 다른 모든 노드와 통신할 수 있어야 합니다. 다른 노드의 SSH 트래픽을 허용하는 것은 선택 사항입니다.



 a| 
80
 a| 
TCP
 a| 
어플라이언스
 a| 
기본 관리자 노드
 a| 
StorageGRID 어플라이언스에서 운영 관리자 노드와 통신하여 설치를 시작하는 데 사용됩니다.



 a| 
123을 선택합니다
 a| 
UDP입니다
 a| 
모든 노드
 a| 
모든 노드
 a| 
네트워크 시간 프로토콜 서비스. 모든 노드는 NTP를 사용하여 다른 모든 노드와 시간을 동기화합니다.



 a| 
443
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리자 노드
 a| 
설치 및 기타 유지 보수 절차 중에 기본 관리 노드에 상태를 전달하는 데 사용됩니다.



 a| 
1139
 a| 
TCP
 a| 
스토리지 노드
 a| 
스토리지 노드
 a| 
스토리지 노드 간 내부 트래픽



 a| 
1501
 a| 
TCP
 a| 
모든 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
보고, 감사 및 구성 내부 트래픽.



 a| 
1502)를 참조하십시오
 a| 
TCP
 a| 
모든 노드
 a| 
스토리지 노드
 a| 
S3 및 Swift 관련 내부 트래픽



 a| 
1504
 a| 
TCP
 a| 
모든 노드
 a| 
관리자 노드
 a| 
NMS 서비스 보고 및 구성 내부 트래픽



 a| 
1505
 a| 
TCP
 a| 
모든 노드
 a| 
관리자 노드
 a| 
AMS 서비스 내부 트래픽



 a| 
1506
 a| 
TCP
 a| 
모든 노드
 a| 
모든 노드
 a| 
서버 상태 내부 트래픽.



 a| 
1507
 a| 
TCP
 a| 
모든 노드
 a| 
게이트웨이 노드
 a| 
로드 밸런서 내부 트래픽



 a| 
1508
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리자 노드
 a| 
구성 관리 내부 트래픽



 a| 
1509
 a| 
TCP
 a| 
모든 노드
 a| 
아카이브 노드
 a| 
아카이브 노드 내부 트래픽



 a| 
1511)을 참조하십시오
 a| 
TCP
 a| 
모든 노드
 a| 
스토리지 노드
 a| 
메타데이터 내부 트래픽.



 a| 
5353)을 참조하십시오
 a| 
UDP입니다
 a| 
모든 노드
 a| 
모든 노드
 a| 
설치, 확장 및 복구 중에 전체 그리드 IP 변경 및 운영 관리자 노드 검색에 선택적으로 사용됩니다.



 a| 
7001)을 참조하십시오
 a| 
TCP
 a| 
스토리지 노드
 a| 
스토리지 노드
 a| 
Cassandra TLS 노드 간 클러스터 통신.



 a| 
7443
 a| 
TCP
 a| 
모든 노드
 a| 
관리자 노드
 a| 
유지보수 절차 및 오류 보고를 위한 내부 트래픽.



 a| 
9042
 a| 
TCP
 a| 
스토리지 노드
 a| 
스토리지 노드
 a| 
Cassandra 클라이언트 포트:



 a| 
9999
 a| 
TCP
 a| 
모든 노드
 a| 
모든 노드
 a| 
여러 서비스의 내부 트래픽. 유지 보수 절차, 메트릭 및 네트워킹 업데이트를 포함합니다.



 a| 
10226
 a| 
TCP
 a| 
스토리지 노드
 a| 
기본 관리자 노드
 a| 
StorageGRID 어플라이언스에서 E-Series SANtricity 시스템 관리자의 AutoSupport 메시지를 운영 관리 노드로 전달하는 데 사용됩니다.



 a| 
11139
 a| 
TCP
 a| 
아카이브/스토리지 노드
 a| 
아카이브/스토리지 노드
 a| 
스토리지 노드와 아카이브 노드 간의 내부 트래픽입니다.



 a| 
18000입니다
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
계정 서비스 내부 트래픽.



 a| 
18001
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
ID 페더레이션 내부 트래픽.



 a| 
18002
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
스토리지 노드
 a| 
객체 프로토콜과 관련된 내부 API 트래픽입니다.



 a| 
18003
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
플랫폼 서비스 내부 트래픽



 a| 
18017
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
스토리지 노드
 a| 
Data Mover Service Cloud Storage Pool의 내부 트래픽입니다.



 a| 
18019
 a| 
TCP
 a| 
스토리지 노드
 a| 
스토리지 노드
 a| 
삭제 코딩을 위한 청크 서비스 내부 트래픽입니다.



 a| 
18082
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
스토리지 노드
 a| 
S3 관련 내부 트래픽.



 a| 
18083
 a| 
TCP
 a| 
모든 노드
 a| 
스토리지 노드
 a| 
스위프트 관련 내부 트래픽.



 a| 
18200
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
스토리지 노드
 a| 
클라이언트 요청에 대한 추가 통계입니다.



 a| 
19000입니다
 a| 
TCP
 a| 
관리/스토리지 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
Keystone 서비스 내부 트래픽

|===
* 관련 정보 *

xref:external-communications.adoc[외부 통신]
