---
permalink: sg5600/configuring-autosupport.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, configure, configuring, set up, setup, autosupport, auto support 
summary: AutoSupport 도구는 어플라이언스에서 고객 지원 번들의 데이터를 수집하고 자동으로 기술 지원 부서에 전송합니다. AutoSupport를 구성하면 원격 문제 해결 및 문제 분석에 대한 기술 지원을 받을 수 있습니다. 
---
= AutoSupport를 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 도구는 어플라이언스에서 고객 지원 번들의 데이터를 수집하고 자동으로 기술 지원 부서에 전송합니다. AutoSupport를 구성하면 원격 문제 해결 및 문제 분석에 대한 기술 지원을 받을 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 제품에서 AutoSupport 기능을 활성화 및 활성화해야 합니다.
+
AutoSupport 기능은 저장소 관리 스테이션에서 전역적으로 활성화 및 비활성화됩니다.

* Storage Manager 이벤트 모니터는 어플라이언스에 액세스할 수 있는 하나 이상의 시스템에서 실행되고 있어야 하며, 둘 이상의 시스템에서 실행하는 것이 좋습니다.


모든 데이터는 사용자가 지정한 위치에서 압축된 단일 아카이브 파일 형식(.7z)으로 압축됩니다.

AutoSupport에서는 다음과 같은 유형의 메시지를 제공합니다.

|===
| 메시지 유형 | 설명 


 a| 
이벤트 메시지
 a| 
* 관리 대상 어플라이언스에서 지원 이벤트가 발생할 때 발송됩니다
* 시스템 구성 및 진단 정보를 포함합니다




 a| 
매일 메시지
 a| 
* 사용자가 구성할 수 있는 시간 간격 동안 매일 어플라이언스 현지 시간에 한 번씩 전송됩니다
* 현재 시스템 이벤트 로그 및 성능 데이터를 포함합니다




 a| 
주간 메시지
 a| 
* 사용자가 구성할 수 있는 시간 간격 동안 매주 한 번씩 제품의 현지 시간으로 전송됩니다
* 구성 및 시스템 상태 정보를 포함합니다


|===
.단계
. SANtricity 스토리지 관리자의 엔터프라이즈 관리 창에서 * 장치 * 탭을 선택한 다음 * 검색된 스토리지 배열 * 을 선택합니다.
. 도구 * > * AutoSupport * > * 구성 * 을 선택합니다.
. 필요한 경우 SANtricity 스토리지 관리자 온라인 도움말을 사용하여 작업을 완료합니다.


http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61197["NetApp 문서: SANtricity 스토리지 관리자"^]
