---
permalink: sg5600/index.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, overview, models, features 
summary: StorageGRID SG5600 어플라이언스는 StorageGRID 그리드에서 스토리지 노드로 작동하는 통합 스토리지 및 컴퓨팅 플랫폼입니다. 
---
= SG5600 어플라이언스: 개요
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID SG5600 어플라이언스는 StorageGRID 그리드에서 스토리지 노드로 작동하는 통합 스토리지 및 컴퓨팅 플랫폼입니다.

StorageGRID SG5600 어플라이언스에는 다음과 같은 구성 요소가 포함되어 있습니다.

|===
| 구성 요소 | 설명 


 a| 
E5500SG 컨트롤러
 a| 
컴퓨팅 서버E5600SG 컨트롤러는 Linux 운영 체제와 StorageGRID 소프트웨어를 실행합니다.

이 컨트롤러는 다음 장치에 연결됩니다.

* StorageGRID 시스템용 관리자, 그리드 및 클라이언트 네트워크
* E2700은 이중 SAS 경로(액티브/액티브)를 사용하며, E54600SG 컨트롤러를 이니시에이터로 작동합니다




 a| 
E2700 컨트롤러
 a| 
스토리지 컨트롤러E2700 컨트롤러는 표준 E-Series 스토리지 어레이로 작동하며 SANtricity 운영 체제(컨트롤러 펌웨어)를 실행합니다.

이 컨트롤러는 다음 장치에 연결됩니다.

* SANtricity 스토리지 관리자가 설치된 관리 네트워크입니다
* E5500SG 컨트롤러, 이중 SAS 경로(액티브/액티브)를 사용하고 E2700 컨트롤러가 대상으로 작동


|===
SG5600 어플라이언스에는 모델에 따라 다음과 같은 구성 요소도 포함되어 있습니다.

|===
| 구성 요소 | 모델 SG5612 | 모델 SG5660 


 a| 
드라이브
 a| 
NL-SAS 드라이브 12개
 a| 
NL-SAS 드라이브 60개



 a| 
엔클로저
 a| 
DE1600 엔클로저 - 드라이브와 컨트롤러가 장착된 2개의 랙 유닛(2U) 섀시
 a| 
DE6600 엔클로저, 드라이브와 컨트롤러가 장착된 4개의 랙 유닛(4U) 섀시



 a| 
전원 공급 장치 및 팬
 a| 
2개의 전원 팬 캐니스터
 a| 
전원 공급 장치 2개 및 팬 2개

|===

NOTE: E5500SG 컨트롤러는 StorageGRID 어플라이언스에 사용할 수 있도록 고도로 커스터마이징되었습니다. 다른 모든 구성 요소는 E-Series 문서에 설명된 대로 작동합니다. 단, 이러한 지침 에는 나와 있습니다.

각 StorageGRID 어플라이언스 스토리지 노드에서 사용할 수 있는 최대 기본 스토리지는 어플라이언스 모델 및 구성에 따라 고정됩니다. 쉘프를 추가하려면 드라이브를 추가할 때 사용 가능한 스토리지를 확장할 수 없습니다.
