---
permalink: sg5600/optional-changing-to-raid6-mode-sg5660-only.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, raid6 
summary: '60개 드라이브가 포함된 SG5660을 사용하는 경우 볼륨 구성을 기본 권장 설정인 DDP\(동적 디스크 풀\)에서 RAID6로 변경할 수 있습니다. StorageGRID 어플라이언스 스토리지 노드를 구축하기 전에만 모드를 변경할 수 있습니다.' 
---
= 선택 사항: RAID6 모드로 변경(SG5660만 해당)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
60개 드라이브가 포함된 SG5660을 사용하는 경우 볼륨 구성을 기본 권장 설정인 DDP(Dynamic Disk Pools)에서 RAID6로 변경할 수 있습니다. StorageGRID 어플라이언스 스토리지 노드를 구축하기 전에만 모드를 변경할 수 있습니다.

.필요한 것
* SG5660을 이미 사용하고 있습니다. SG5612는 RAID6를 지원하지 않습니다. SG5612를 사용하는 경우 DDP 모드를 사용해야 합니다.



IMPORTANT: 볼륨이 이미 구성되었거나 StorageGRID가 이전에 설치된 경우 RAID 모드를 변경하면 볼륨이 제거되고 교체됩니다. 해당 볼륨의 모든 데이터가 손실됩니다.

.이 작업에 대해
StorageGRID 어플라이언스 스토리지 노드를 구축하기 전에 다음 두 가지 볼륨 구성 옵션 중에서 선택할 수 있습니다.

* * DDP(동적 디스크 풀) * -- 기본값 및 권장 설정입니다. DDP는 향상된 하드웨어 데이터 보호 구성표로, 시스템 성능을 향상하고, 드라이브 장애 후 리빌드 시간을 단축하고, 관리를 간소화합니다.
* * RAID6 * -- 이 시스템은 각 디스크의 패리티 스트라이프를 사용하는 하드웨어 보호 스키마로서, 데이터가 손실되기 전에 RAID 세트 내에서 2개의 디스크 장애를 허용합니다.
+

IMPORTANT: 대부분의 StorageGRID 환경에서는 RAID6를 사용하지 않는 것이 좋습니다. RAID6는 스토리지 효율성을 DDP의 80%에 비해 88%까지 높일 수 있지만 DDP 모드는 드라이브 장애를 더욱 효율적으로 복구합니다.



.단계
. 서비스 랩톱을 사용하여 웹 브라우저를 열고 StorageGRID 어플라이언스 설치 프로그램: + ``https://_E5600SG_Controller_IP_:8443*` 액세스합니다
+
여기서, '_E600SG_Controller_IP_'는 E5500SG 컨트롤러의 IP 주소입니다.

. 메뉴 모음에서 * 고급 * > * RAID 모드 * 를 선택합니다.
. RAID 모드 구성 * 페이지의 모드 드롭다운 목록에서 * RAID6 * 을 선택합니다.
. 저장 * 을 클릭합니다.

