---
permalink: sg5600/replacing-e5600sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, Replacing, replace, E5600sg, controller, remove, removing, removal, install, installing, installation 
summary: E5500SG 컨트롤러를 교체해야 할 수 있습니다. 
---
= E5500SG 컨트롤러를 교체합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
E5500SG 컨트롤러를 교체해야 할 수 있습니다.

다음 리소스에 대한 액세스 권한이 있어야 합니다.

* E-Series 하드웨어 교체 정보는 NetApp Support 사이트(+)에서 확인할 수 있습니다http://mysupport.netapp.com/["mysupport.netapp.com"^]
* E5600 설명서를 참조하십시오
* 제품이 다 되었습니다 xref:placing-appliance-into-maintenance-mode.adoc[유지보수 모드로 전환되었습니다].


두 컨트롤러가 모두 정상적으로 작동하는 경우 제어된 종료를 허용하기 전에 E5500SG 컨트롤러를 먼저 종료하여 E2700 컨트롤러에 대한 연결을 중단할 수 있습니다.


NOTE: StorageGRID 소프트웨어를 설치하기 전에 컨트롤러를 교체하는 경우 이 절차를 완료한 후 즉시 StorageGRID 어플라이언스 설치 프로그램에 액세스하지 못할 수 있습니다. 어플라이언스와 동일한 서브넷에 있는 다른 호스트에서 StorageGRID 어플라이언스 설치 프로그램에 액세스할 수 있지만 다른 서브넷에 있는 호스트에서는 액세스할 수 없습니다. 이 조건은 15분 내에 해결되어야 하며(원래 컨트롤러의 ARP 캐시 항목이 시간 초과될 때), 또는 로컬 라우터 또는 게이트웨이에서 수동으로 이전의 ARP 캐시 항목을 삭제하여 즉시 조건을 지울 수 있습니다.

.단계
. 정전기 방지 보호 장치를 사용합니다.
. E54600 SG 컨트롤러에 연결된 각 케이블에 레이블을 지정하여 케이블을 올바르게 다시 연결할 수 있습니다.
+

IMPORTANT: 성능 저하를 방지하려면 케이블을 비틀거나 접거나 끼거나 밟지 마십시오. 케이블을 5cm(2인치) 반경보다 더 구부리지 마십시오.

. 어플라이언스를 유지보수 모드로 전환한 후 E5500SG 컨트롤러를 종료합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 'ssh admin@_grid_node_ip_' 명령을 입력합니다
... "passwords.txt" 파일에 나열된 암호를 입력합니다.
... 루트로 전환하려면 다음 명령을 입력합니다
... "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



.. E5500SG 컨트롤러를 종료합니다. + " * shutdown -h now * "


. 엔클로저의 전원을 끄고 컨트롤러 후면의 모든 LED 및 7개 세그먼트 디스플레이 작동이 멈출 때까지 기다립니다.
. 케이블을 분리합니다.
. E54600 SG 컨트롤러 설명서에 설명된 대로 컨트롤러를 분리합니다.
. E54600 SG 컨트롤러 설명서에 설명된 대로 새 컨트롤러를 삽입합니다.
. 모든 케이블을 교체합니다.
. 엔클로저의 전원을 다시 켭니다.
. 7개 세그먼트 코드를 모니터링합니다.
+
** E2700 컨트롤러:
+
마지막 LED 상태는 99입니다.

** E5500SG 컨트롤러:
+
마지막 LED 상태는 HA입니다.



. Grid Manager에서 어플라이언스 스토리지 노드의 상태를 모니터링합니다.
+
어플라이언스 스토리지 노드가 예상 상태로 돌아가는지 확인합니다.



https://mysupport.netapp.com/info/web/ECMP11751516.html["NetApp E-Series 및 EF-Series 하드웨어 교체 절차 를 참조하십시오"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61893["NetApp 설명서: E5600 시리즈"^]
