= 
:allow-uri-read: 


[role="tabbed-block"]
====
.복제된 데이터
--
* 수리가 완료되었는지 확인하려면:
+
.. 노드 * > * _ 복구되는 스토리지 노드 _ * > * ILM * 을 선택합니다.
.. 평가 섹션의 속성을 검토합니다. 복구가 완료되면 * Awaiting-all * 속성이 0 개체를 나타냅니다.


* 수리를 더 자세히 모니터링하려면:
+
.. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
.. 복구되는 *_GRID_ * > *_Storage Node _ * > * LDR * > * Data Store * 를 선택합니다.
.. 복제된 수리가 완료된 경우 다음 특성을 조합하여 가능한 한 결정합니다.
+

NOTE: Cassandra의 일관성이 없을 수 있으며, 복구 실패를 추적하지 않습니다.

+
*** * 시도된 복구(XRPA) *: 이 속성을 사용하여 복제된 복구 진행률을 추적합니다. 이 속성은 스토리지 노드가 고위험 객체를 복구하려고 할 때마다 증가합니다. 이 속성이 현재 스캔 기간(* Scan Period -- Estimated* 속성 제공)보다 더 긴 기간 동안 증가하지 않으면 ILM 스캐닝에서 모든 노드에서 복구해야 할 고위험 개체를 찾지 못한 것입니다.
+

NOTE: 고위험 개체는 완전히 손실될 위험이 있는 개체입니다. ILM 구성을 충족하지 않는 개체는 포함되지 않습니다.

*** * 스캔 기간 -- 예상(XSCM) *: 이 속성을 사용하여 이전에 수집된 개체에 정책 변경이 적용되는 시점을 추정합니다. 복구 시도 * 속성이 현재 스캔 기간보다 긴 기간 동안 증가하지 않으면 복제된 수리가 수행될 수 있습니다. 스캔 기간은 변경될 수 있습니다. 스캔 기간 -- 예상(XSCM) * 속성은 전체 그리드에 적용되며 모든 노드 스캔 기간의 최대값입니다. 그리드에 대한 * Scan Period -- Estimated * 속성 기록을 조회하여 적절한 기간을 결정할 수 있습니다.




* 필요에 따라 복제된 복구에 대한 예상 완료율을 얻으려면 repair-data 명령에 'show-replicated-repair-status' 옵션을 추가합니다.
+
REpair-data show-replicated-repair-status'를 참조하십시오

+

IMPORTANT: StorageGRID 11.6의 기술 미리 보기에는 '복제된-수리-상태' 옵션이 제공됩니다. 이 기능은 개발 중이며 반환된 값이 잘못되었거나 지연될 수 있습니다. 수리가 완료되었는지 확인하려면 에 설명된 대로 * Awaiting – All *, * repair attemptated (XRPA) * 및 * Scan Period -- Estimated (XSCM) * 를 사용합니다 xref:..//maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.adoc[수리 모니터링].



--
.삭제 코딩(EC) 데이터
--
삭제 코딩 데이터의 복구를 모니터링하고 실패한 요청을 다시 시도하려면 다음을 수행하십시오.

. 삭제 코딩 데이터 복구 상태를 확인합니다.
+
** 현재 작업의 예상 완료 시간과 완료 비율을 보려면 * 지원 * > * 도구 * > * 메트릭 * 을 선택합니다. 그런 다음 Grafana 섹션에서 * EC 개요 * 를 선택합니다. Grid EC Job Ec Job Estimated Time to Completion * 및 * Grid EC Job Percentage Completed * 대시보드를 확인합니다.
** 특정 repair-data 작업의 상태를 확인하려면 다음 명령을 사용합니다.
+
REpair-data show -ec-repair-status--repair-id repair ID'를 참조하십시오

** 이 명령을 사용하여 모든 수리를 나열합니다.
+
Repair-data show-ec-repair-status'를 참조하십시오

+
이 출력에는 현재 실행 중인 모든 수리에 대한 "재쌍 ID"를 포함한 정보가 나열됩니다.



. 출력에 복구 작업이 실패한 것으로 표시되면 '--repair-id' 옵션을 사용하여 복구를 다시 시도합니다.
+
이 명령은 복구 ID 6949309319275667690을 사용하여 장애가 발생한 노드 복구를 재시도합니다.

+
REpair-data start-ec-node-repair--repair-id 6949309319275667690

+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 볼륨 복구를 재시도합니다.

+
REpair-data start-ec-volume-repair--repair-id 6949309319275667690



--
====