---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: S3 테넌트를 사용하는 경우 테넌트 관리자 또는 테넌트 관리 API를 사용하여 S3 버킷의 오브젝트에 대해 수행된 작업의 정합성 제어를 변경할 수 있습니다. 
---
= 정합성 보장 수준을 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용하는 경우 테넌트 관리자 또는 테넌트 관리 API를 사용하여 S3 버킷의 오브젝트에 대해 수행된 작업의 정합성 제어를 변경할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 를 사용하여 테넌트 관리자에 로그인해야 합니다 xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저].
* 모든 버킷 관리 또는 루트 액세스 권한이 있는 사용자 그룹에 속해야 합니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다. 을 참조하십시오 xref:tenant-management-permissions.adoc[테넌트 관리 권한].


정합성 보장 레벨은 오브젝트의 가용성과 서로 다른 스토리지 노드 및 사이트에서 이러한 오브젝트의 일관성 간에 균형을 전환합니다. 일반적으로 버킷에 대해 * Read-After-new-write * 정합성 수준을 사용해야 합니다. Read-After-new-write* 정합성 수준이 클라이언트 애플리케이션의 요구 사항을 충족하지 않는 경우 버킷 정합성 수준을 설정하거나 '정합성 보장-제어' 헤더를 사용하여 정합성 보장 수준을 변경할 수 있습니다. 정합성 보장(Consistency-Control) 헤더는 버킷 정합성 수준을 재정의합니다.


NOTE: 버킷의 정합성 수준을 변경하면 변경 후 수집된 객체만 수정된 레벨에 맞게 보장됩니다.

.단계
. 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 목록에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. 버킷 옵션 * > * 정합성 보장 레벨 * 을 선택합니다.
. 이 버킷의 오브젝트에 대해 수행된 작업의 정합성 수준을 선택합니다.
+
[cols="1a,3a"]
|===
| 정합성 보장 레벨 | 설명 


 a| 
모두
 a| 
모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.



 a| 
강함 - 글로벌
 a| 
모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 정합성을 보장합니다.



 a| 
강력한 사이트
 a| 
사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.



 a| 
Read-After-new-write (기본값)
 a| 
새 객체에 대한 읽기-쓰기 후 정합성 보장 및 객체 업데이트에 대한 최종 정합성 보장 기능을 제공합니다. 에서는 고가용성을 제공하고 데이터 보호 보장을 제공합니다. Amazon S3 일관성 보장과 가장 비슷합니다.

* 참고: * 응용 프로그램이 존재하지 않는 키에 대해 헤드 또는 GET 작업을 시도하는 경우, Amazon S3 일관성 보장이 필요하지 않는 한 정합성 보장 레벨을 * 사용 가능 * 으로 설정합니다. 그렇지 않으면 하나 이상의 스토리지 노드를 사용할 수 없는 경우 500개의 내부 서버 오류가 발생할 수 있습니다.



 a| 
사용 가능(헤드 또는 GET 작업의 최종 정합성)
 a| 
는 * Read-After-new-write * 정합성 수준과 동일하게 작동하지만 헤드 및 GET 작업에 대한 최종 일관성을 제공합니다. 스토리지 노드를 사용할 수 없는 경우 헤드 및 GET 작업에 대해 * Read-After-new-write * 보다 높은 가용성을 제공합니다. 헤드 및 GET 작업에 대한 Amazon S3 정합성 보장과 다릅니다.

|===
. 변경 내용 저장 * 을 선택합니다.

