---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: 'StorageGRID에서 지정된 이벤트에 대한 알림을 대상 Amazon SNS(Simple Notification Service)\로 보내도록 하려면 S3 버킷에 대한 이벤트 알림을 활성화할 수 있습니다.' 
---
= 버킷에 대한 알림을 이해합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID에서 지정된 이벤트에 대한 알림을 대상 SNS(Amazon Simple Notification Service)로 보내도록 하려면 S3 버킷에 대한 이벤트 알림을 활성화할 수 있습니다.

가능합니다 xref:configuring-event-notifications.adoc[이벤트 알림을 구성합니다] 알림 구성 XML을 소스 버킷과 연결합니다. 알림 구성 XML은 버킷 알림을 구성하기 위한 S3 규칙을 따르고, 엔드포인트의 URN으로 지정된 대상 SNS 항목을 따릅니다.

이벤트 알림은 알림 구성에 지정된 대로 소스 버킷에서 생성되며 대상으로 전달됩니다. 개체와 관련된 이벤트가 성공하면 해당 이벤트에 대한 알림이 생성되고 배달 대기 상태가 됩니다.

알림의 고유성과 순서는 보장되지 않습니다. 전송 성공을 보장하기 위해 수행된 작업의 결과로 하나 이상의 이벤트 알림이 대상에 전달될 수 있습니다. 그리고 납품이 비동기식이기 때문에, 특히 서로 다른 StorageGRID 사이트에서 발생하는 작업의 경우, 대상에서 알림의 시간 순서가 소스 버킷의 이벤트 순서와 일치한다고 보장할 수 없습니다. 이벤트 메시지에서 '시퀀스' 키를 사용하여 Amazon S3 문서에 설명된 대로 특정 객체에 대한 이벤트 순서를 결정할 수 있습니다.



== 지원되는 알림 및 메시지

StorageGRID 이벤트 알림은 Amazon S3 API를 따르며 다음과 같은 제한 사항이 적용됩니다.

* 다음 이벤트 유형에 대한 알림을 구성할 수 없습니다. 이러한 이벤트 유형은 * 지원되지 않습니다 *.
+
** '3: RedundancyLostObject'를 선택합니다
** '3:ObjectRestore:완료됨'


* StorageGRID에서 보낸 이벤트 알림은 표에 나와 있는 것처럼 일부 키를 포함하지 않고 다른 키에 대해 특정 값을 사용한다는 점을 제외하고 표준 JSON 형식을 사용합니다.


[cols="1a,2a"]
|===
| 키 이름 | StorageGRID 값 


 a| 
이벤트 소스
 a| 
전쟁포로 S3



 a| 
awsRegion
 a| 
포함되지 않음



 a| 
X-amz-id-2
 a| 
포함되지 않음



 a| 
ARN
 a| 
''urn:SGWs:S3::bucket_name'

|===