---
permalink: tenant/what-platform-services-are.html 
sidebar: sidebar 
keywords: what are platform services 
summary: StorageGRID 플랫폼 서비스는 하이브리드 클라우드 전략을 구현하는 데 도움이 될 수 있습니다. 
---
= 플랫폼 서비스란 무엇입니까?
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 플랫폼 서비스는 하이브리드 클라우드 전략을 구현하는 데 도움이 될 수 있습니다.

테넌트 계정에 플랫폼 서비스를 사용할 수 있는 경우 모든 S3 버킷에 대해 다음 서비스를 구성할 수 있습니다.

* * CloudMirror 복제 * xref:understanding-cloudmirror-replication-service.adoc[StorageGRID CloudMirror 복제 서비스입니다] StorageGRID 버킷에서 지정된 외부 대상으로 특정 오브젝트를 미러링하는 데 사용됩니다.
+
예를 들어, CloudMirror 복제를 사용하여 특정 고객 레코드를 Amazon S3에 미러링한 다음 AWS 서비스를 활용하여 데이터에 대한 분석을 수행할 수 있습니다.

+

NOTE: 소스 버킷에 S3 오브젝트 잠금이 설정된 경우 CloudMirror 복제가 지원되지 않습니다.

* * 알림 *: xref:understanding-notifications-for-buckets.adoc[버킷당 이벤트 알림] 지정된 외부 SNS(Amazon Simple Notification Service ™)에 객체에 대해 수행된 특정 작업에 대한 알림을 보내는 데 사용됩니다.
+
예를 들어, 버킷에 추가된 각 오브젝트에 대해 관리자에게 경고가 전송되도록 구성할 수 있습니다. 여기서 객체는 중요한 시스템 이벤트와 연결된 로그 파일을 나타냅니다.

+

NOTE: S3 오브젝트 잠금이 활성화된 버킷에서 이벤트 알림을 구성할 수 있지만 오브젝트의 S3 오브젝트 잠금 메타데이터(마지막 보존 날짜 및 법적 보류 상태 포함)는 알림 메시지에 포함되지 않습니다.

* * 통합 서비스 검색 * xref:understanding-search-integration-service.adoc[검색 통합 서비스] 외부 서비스를 사용하여 메타데이터를 검색하거나 분석할 수 있는 지정된 Elasticsearch 인덱스에 S3 개체 메타데이터를 전송하는 데 사용됩니다.
+
예를 들어, S3 오브젝트 메타데이터를 원격 Elasticsearch 서비스로 전송하도록 버킷을 구성할 수 있습니다. 그런 다음 Elasticsearch를 사용하여 버킷에 대한 검색을 수행하고 객체 메타데이터에 있는 패턴에 대한 정교한 분석을 수행할 수 있습니다.

+

NOTE: S3 오브젝트 잠금이 활성화된 버킷에서 Elasticsearch 통합을 구성할 수 있지만 오브젝트의 S3 오브젝트 잠금 메타데이터(보존 기한 및 법적 보류 상태 포함)는 알림 메시지에 포함되지 않습니다.



플랫폼 서비스의 대상 위치는 일반적으로 StorageGRID 구축과 외부적이기 때문에 플랫폼 서비스는 데이터에 대한 외부 스토리지 리소스, 알림 서비스 및 검색 또는 분석 서비스를 사용하여 얻을 수 있는 성능과 유연성을 제공합니다.

단일 S3 버킷에 대해 모든 플랫폼 서비스 조합을 구성할 수 있습니다. 예를 들어, StorageGRID S3 버킷에서 CloudMirror 서비스 및 알림을 모두 구성하여 특정 오브젝트를 Amazon Simple Storage Service에 미러링하고 이러한 각 오브젝트에 대한 알림을 타사 모니터링 애플리케이션에 전송하여 AWS 비용을 추적할 수 있도록 할 수 있습니다.


IMPORTANT: 그리드 관리자 또는 그리드 관리 API를 사용하여 StorageGRID 관리자가 각 테넌트 계정에 대해 플랫폼 서비스 사용을 활성화해야 합니다.



== 플랫폼 서비스 구성 방법

플랫폼 서비스는 테넌트 관리자 또는 테넌트 관리 API를 사용하여 구성한 외부 엔드포인트와 통신합니다. 각 엔드포인트는 StorageGRID S3 버킷, Amazon 웹 서비스 버킷, SNS(Simple Notification Service) 주제 또는 로컬, AWS 또는 기타 위치에서 호스팅되는 Elasticsearch 클러스터와 같은 외부 대상을 나타냅니다.

끝점을 만든 후 버킷에 XML 구성을 추가하여 버킷에 대한 플랫폼 서비스를 활성화할 수 있습니다. XML 구성은 버킷이 작업해야 하는 오브젝트, 버킷이 취해야 하는 조치 및 버킷이 서비스에 사용해야 하는 엔드포인트를 식별합니다.

구성할 각 플랫폼 서비스에 대해 별도의 XML 구성을 추가해야 합니다. 예를 들면 다음과 같습니다.

. 키가 '/images'로 시작하는 모든 오브젝트를 Amazon S3 버킷에 복제하려면 소스 버킷에 복제 구성을 추가해야 합니다.
. 이러한 객체가 버킷에 저장될 때 알림을 보내려면 알림 구성을 추가해야 합니다.
. 마지막으로 이러한 개체의 메타데이터를 인덱싱하려면 검색 통합을 구현하는 데 사용되는 메타데이터 알림 구성을 추가해야 합니다.


구성 XML의 형식은 StorageGRID 플랫폼 서비스를 구현하는 데 사용되는 S3 REST API를 통해 제어됩니다.

[cols="1a,2a"]
|===
| 플랫폼 서비스 | S3 REST API 


 a| 
CloudMirror 복제
 a| 
* 버킷 복제를 가져옵니다
* 버킷 복제를 배치합니다




 a| 
알림
 a| 
* 버킷 알림을 받습니다
* 버킷 통지를 보냅니다




 a| 
검색 통합
 a| 
* Bucket 메타데이터 알림 구성 가져오기
* Put Bucket 메타데이터 알림 구성


이러한 작업은 StorageGRID에 맞게 맞춤형으로 제공됩니다.

|===
StorageGRID에서 이러한 API를 구축하는 방법에 대한 자세한 내용은 S3 클라이언트 애플리케이션 구현 지침을 참조하십시오.

xref:considerations-for-using-platform-services.adoc[플랫폼 서비스 사용에 대한 고려 사항]

xref:../s3/index.adoc[S3을 사용합니다]
