---
permalink: rhel/planning-and-preparation.html 
sidebar: sidebar 
keywords: installation planning red hat linux 
summary: 그리드 노드를 배포하고 StorageGRID 그리드를 구성하기 전에 절차를 완료하기 위한 단계와 요구 사항을 숙지해야 합니다. 
---
= 설치하기 전에(Red Hat 또는 CentOS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드를 배포하고 StorageGRID 그리드를 구성하기 전에 절차를 완료하기 위한 단계와 요구 사항을 숙지해야 합니다.

StorageGRID 배포 및 구성 절차에서는 StorageGRID 시스템의 아키텍처 및 작동에 대해 잘 알고 있다고 가정합니다.

단일 사이트 또는 여러 사이트를 한 번에 배포할 수 있지만, 모든 사이트는 최소 3개의 스토리지 노드를 보유해야 하는 최소 요구 사항을 충족해야 합니다.

StorageGRID 설치를 시작하기 전에 다음을 수행해야 합니다.

* 각 노드의 최소 CPU 및 RAM 요구사항을 비롯한 StorageGRID의 컴퓨팅 요구사항 이해
* StorageGRID가 트래픽 분리, 보안 및 관리의 편의를 위해 여러 네트워크를 지원하는 방법을 이해하고 각 StorageGRID 노드에 연결할 네트워크를 계획합니다.
+
StorageGRID 네트워킹 지침을 참조하십시오.

* 각 그리드 노드 유형의 스토리지 및 성능 요구 사항을 이해합니다.
* 구축할 StorageGRID 노드의 수와 유형을 지원하기에 충분한 리소스를 제공하는 물리적 서버 세트, 가상 서버 또는 둘 다 식별합니다.
* 서비스 중단 없이 물리적 호스트에 대해 예약된 유지 관리를 수행하려는 경우 노드 마이그레이션에 대한 요구 사항을 파악합니다.
* 모든 네트워킹 정보를 미리 수집합니다. DHCP를 사용하지 않는 경우 각 그리드 노드에 할당할 IP 주소와 사용할 DNS(Domain Name System) 및 NTP(Network Time Protocol) 서버의 IP 주소를 수집합니다.
* 모든 StorageGRID 어플라이언스를 포함하여 필요한 모든 하드웨어를 사양에 맞게 설치, 연결 및 구성합니다.
+

NOTE: 하드웨어 관련 설치 및 통합 지침은 StorageGRID 설치 절차에 포함되어 있지 않습니다. StorageGRID 어플라이언스를 설치하는 방법에 대한 자세한 내용은 해당 어플라이언스의 설치 및 유지 관리 지침을 참조하십시오.

* 사용할 수 있는 배포 및 구성 도구 중에서 선택합니다.


xref:../network/index.adoc[네트워킹 지침]

xref:../sg100-1000/index.adoc[SG100 및 SG1000 서비스 어플라이언스]

xref:../sg6000/index.adoc[SG6000 스토리지 어플라이언스]

xref:../sg5700/index.adoc[SG5700 스토리지 어플라이언스]

xref:../sg5600/index.adoc[SG5600 스토리지 어플라이언스]
