---
permalink: admin/configuring-client-connections.html 
sidebar: sidebar 
keywords: s3 connection, swift connection, connect to storagegrid 
summary: 그리드 관리자는 S3 및 Swift 테넌트가 클라이언트 애플리케이션을 StorageGRID 시스템에 연결하여 데이터를 저장 및 검색하는 방법을 제어하는 구성 옵션을 관리합니다. 다양한 클라이언트 및 테넌트 요구 사항을 충족하는 여러 가지 옵션이 있습니다. 
---
= S3 및 Swift 클라이언트 연결에 대해 설명합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 S3 및 Swift 테넌트가 클라이언트 애플리케이션을 StorageGRID 시스템에 연결하여 데이터를 저장 및 검색하는 방법을 제어하는 구성 옵션을 관리합니다. 다양한 클라이언트 및 테넌트 요구 사항을 충족하는 여러 가지 옵션이 있습니다.

클라이언트 응용 프로그램은 다음 중 하나를 연결하여 개체를 저장하거나 검색할 수 있습니다.

* 관리 노드 또는 게이트웨이 노드의 부하 분산 서비스 또는 선택적으로 관리 노드 또는 게이트웨이 노드의 고가용성(HA) 그룹의 가상 IP 주소입니다
* 게이트웨이 노드의 CLB 서비스 또는 게이트웨이 노드의 고가용성 그룹의 가상 IP 주소(선택 사항)입니다
+

NOTE: CLB 서비스는 더 이상 사용되지 않습니다. StorageGRID 11.3 릴리스 전에 구성된 클라이언트는 게이트웨이 노드에서 CLB 서비스를 계속 사용할 수 있습니다. 로드 밸런싱을 제공하기 위해 StorageGRID에 의존하는 다른 모든 클라이언트 애플리케이션은 로드 밸런서 서비스를 사용하여 연결해야 합니다.

* 외부 로드 밸런서가 있거나 없는 스토리지 노드


StorageGRID 시스템에서 다음 기능을 선택적으로 구성할 수 있습니다.

* * VLAN 인터페이스 *: 관리 노드와 게이트웨이 노드에서 가상 LAN(VLAN) 인터페이스를 생성하여 보안, 유연성 및 성능을 위해 클라이언트 및 테넌트 트래픽을 격리하고 분할할 수 있습니다. VLAN 인터페이스를 생성한 후 고가용성(HA) 그룹에 추가합니다.
* * 고가용성 그룹 *: 게이트웨이 노드 또는 관리 노드에 대한 인터페이스의 HA 그룹을 생성하여 액티브-백업 구성을 생성하거나 라운드 로빈 DNS 또는 타사 로드 밸런서 및 다중 HA 그룹을 사용하여 액티브-액티브 구성을 달성할 수 있습니다. HA 그룹의 가상 IP 주소를 사용하여 클라이언트 연결이 이루어집니다.
* * 로드 밸런서 서비스 *: 클라이언트가 클라이언트 연결을 위한 로드 밸런서 끝점을 만들어 로드 밸런서 서비스를 사용하도록 설정할 수 있습니다. 로드 밸런서 끝점을 만들 때 끝점에서 HTTP 또는 HTTPS 연결을 허용하는지 여부, 끝점을 사용할 클라이언트 유형(S3 또는 Swift) 및 HTTPS 연결에 사용할 인증서(해당하는 경우)를 포트 번호로 지정합니다.
* * 신뢰할 수 없는 클라이언트 네트워크 *: 클라이언트 네트워크를 신뢰할 수 없음으로 구성하여 보안을 강화할 수 있습니다. 클라이언트 네트워크를 신뢰할 수 없는 경우 클라이언트는 로드 밸런서 끝점만 사용하여 연결할 수 있습니다.


또한 StorageGRID에 직접 연결하는 클라이언트나 CLB 서비스(사용되지 않음)를 사용하는 클라이언트에 대해 HTTP를 사용하도록 설정할 수 있으며 S3 클라이언트에 대해 S3 API 엔드포인트 도메인 이름을 구성할 수 있습니다.
