---
permalink: admin/determining-ilm-policy-for-migrated-data.html 
sidebar: sidebar 
keywords: determing ilm policy, ilm for migrated data 
summary: StorageGRID 시스템의 ILM 정책은 복사본 수, 복사본이 저장되는 위치 및 복사본 보유 기간을 결정합니다. ILM 정책은 시간 경과에 따라 개체를 필터링하고 개체 데이터를 관리하는 방법을 설명하는 ILM 규칙 집합으로 구성되어 있습니다. 
---
= 마이그레이션된 데이터에 대한 ILM 정책을 결정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 ILM 정책은 복사본 수, 복사본이 저장되는 위치 및 복사본 보유 기간을 결정합니다. ILM 정책은 시간 경과에 따라 개체를 필터링하고 개체 데이터를 관리하는 방법을 설명하는 ILM 규칙 집합으로 구성되어 있습니다.

마이그레이션된 데이터의 사용 방법과 마이그레이션된 데이터의 요구 사항에 따라 일상적인 작업에 사용되는 ILM 규칙과 다른 마이그레이션 데이터에 대한 고유한 ILM 규칙을 정의할 수 있습니다. 예를 들어, 마이그레이션에 포함된 데이터에 대한 규정 요구사항과 일상적인 데이터 관리에 대한 규정 요구사항이 서로 다른 경우 다른 등급의 스토리지에 마이그레이션된 데이터의 복사본을 여러 개 만들어야 할 수 있습니다.

마이그레이션된 데이터와 일상적인 작업과 저장된 오브젝트 데이터를 고유하게 구분할 수 있는 경우 마이그레이션된 데이터에만 적용되는 규칙을 구성할 수 있습니다.

메타데이터 기준 중 하나를 사용하여 데이터 유형을 안정적으로 구분할 수 있는 경우, 이 기준을 사용하여 마이그레이션된 데이터에만 적용되는 ILM 규칙을 정의할 수 있습니다.

데이터 마이그레이션을 시작하기 전에 StorageGRID 시스템의 ILM 정책과 마이그레이션 데이터에 적용되는 방법을 이해하고 ILM 정책에 대한 모든 변경 사항을 적용 및 테스트해야 합니다. 을 참조하십시오 xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다].


CAUTION: 잘못 지정된 ILM 정책으로 인해 복구할 수 없는 데이터 손실이 발생할 수 있습니다. ILM 정책을 활성화하기 전에 변경한 모든 내용을 주의 깊게 검토하여 정책이 의도한 대로 작동하는지 확인합니다.
