---
permalink: admin/how-load-balancing-works-load-balancer-service.html 
sidebar: sidebar 
keywords: load balancer service, how load balancing works 
summary: 로드 밸런서 서비스는 들어오는 네트워크 연결을 클라이언트 애플리케이션에서 스토리지 노드로 배포합니다. 로드 밸런싱을 사용하려면 Grid Manager를 사용하여 부하 분산 엔드포인트를 구성해야 합니다. 
---
= 로드 밸런싱 작동 방식 - 로드 밸런서 서비스
:icons: font
:imagesdir: ../media/


[role="lead"]
로드 밸런서 서비스는 들어오는 네트워크 연결을 클라이언트 애플리케이션에서 스토리지 노드로 배포합니다. 로드 밸런싱을 사용하려면 Grid Manager를 사용하여 부하 분산 엔드포인트를 구성해야 합니다.

이러한 노드 유형에는 로드 밸런서 서비스가 포함되어 있으므로 관리 노드 또는 게이트웨이 노드에 대해서만 로드 밸런서 끝점을 구성할 수 있습니다. 스토리지 노드 또는 아카이브 노드의 끝점은 구성할 수 없습니다.

각 로드 밸런서 끝점은 포트, 네트워크 프로토콜(HTTP 또는 HTTPS), 클라이언트 유형(S3 또는 Swift) 및 바인딩 모드를 지정합니다. HTTPS 엔드포인트에는 서버 인증서가 필요합니다. 바인딩 모드를 사용하면 엔드포인트 포트의 액세스를 다음과 같이 제한할 수 있습니다.

* 특정 HA(고가용성) 그룹의 가상 IP 주소(VIP
* 특정 관리 및 게이트웨이 노드의 특정 네트워크 인터페이스




== 포트 고려 사항

클라이언트는 로드 밸런서 서비스를 실행하는 노드에서 구성한 모든 끝점에 액세스할 수 있습니다. 단, 포트 80과 443은 관리 노드에 예약되므로 이러한 포트에 구성된 끝점은 게이트웨이 노드에서만 로드 밸런싱 작업을 지원합니다.

포트를 다시 매핑한 경우 동일한 포트를 사용하여 로드 밸런서 끝점을 구성할 수 없습니다. 다시 매핑된 포트를 사용하여 끝점을 만들 수 있지만 이러한 끝점은 로드 밸런서 서비스가 아닌 원래 CLB 포트 및 서비스에 다시 매핑됩니다. 의 단계를 따릅니다 xref:../maintain/removing-port-remaps.adoc[포트 재맵을 제거합니다].


NOTE: CLB 서비스는 더 이상 사용되지 않습니다.



== CPU 가용성

각 관리 노드와 게이트웨이 노드의 로드 밸런서 서비스는 S3 또는 Swift 트래픽을 스토리지 노드로 전달할 때 독립적으로 작동합니다. 로드 밸런서 서비스는 가중 프로세스를 통해 더 많은 요청을 CPU 가용성이 높은 스토리지 노드로 라우팅합니다. 노드 CPU 로드 정보는 몇 분마다 업데이트되지만 가중치는 더 자주 업데이트될 수 있습니다. 모든 스토리지 노드에는 최소 기본 가중치 값이 할당됩니다. 이는 노드에서 100% 사용률을 보고하거나 사용률을 보고하지 않는 경우에도 마찬가지입니다.

경우에 따라 CPU 가용성에 대한 정보는 로드 밸런서 서비스가 있는 사이트로 제한됩니다.
