---
permalink: admin/impact-of-migration-on-operations.html 
sidebar: sidebar 
keywords: how data migration affects operations 
summary: StorageGRID 시스템은 오브젝트 스토리지 및 검색을 위한 효율적인 작업을 제공하고 오브젝트 데이터 및 메타데이터의 중복 복사본을 지속적으로 생성하여 데이터 손실로부터 데이터를 완벽하게 보호하도록 설계되었습니다. 
---
= 마이그레이션이 운영에 미치는 영향
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템은 오브젝트 스토리지 및 검색을 위한 효율적인 작업을 제공하고 오브젝트 데이터 및 메타데이터의 중복 복사본을 지속적으로 생성하여 데이터 손실로부터 데이터를 완벽하게 보호하도록 설계되었습니다.

그러나 일상적인 시스템 운영에 영향을 주지 않도록 이 장의 지침에 따라 데이터 마이그레이션을 주의 깊게 관리해야 합니다. 그렇지 않을 경우, 극단적인 경우 StorageGRID 시스템에 장애가 발생할 경우 데이터가 손실될 위험이 있습니다.

대량의 데이터를 마이그레이션하면 시스템에 추가 부하가 걸린 것입니다. StorageGRID 시스템이 로드가 많은 경우 객체를 저장하고 검색하는 요청에 더 느리게 응답합니다. 이로 인해 일상적인 작업에 필수적인 저장 및 검색 요청이 방해를 받을 수 있습니다. 마이그레이션으로 인해 다른 운영 문제가 발생할 수도 있습니다. 예를 들어, 스토리지 노드의 용량이 거의 다 되면 배치 수집으로 인한 과중한 간헐적 로드로 인해 스토리지 노드가 읽기 전용과 읽기-쓰기 간에 순환되어 알림을 생성할 수 있습니다.

로드가 많은 경우 큐는 StorageGRID 시스템에서 수행하는 다양한 작업에 대해 개발되어 오브젝트 데이터 및 메타데이터의 완전한 이중화를 보장할 수 있습니다.

마이그레이션 중에 StorageGRID 시스템을 안전하고 효율적으로 운영할 수 있도록 이 문서의 지침에 따라 데이터 마이그레이션을 신중하게 관리해야 합니다. 데이터를 마이그레이션할 때는 오브젝트를 일괄적으로 수집하거나 지속적으로 스로틀로 인제스트합니다. 그런 다음 StorageGRID 시스템을 지속적으로 모니터링하여 다양한 속성 값을 초과하지 않는지 확인합니다.
