---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 그리드 관리자는 S3 및 Swift 클라이언트가 StorageGRID 시스템을 사용하여 오브젝트를 저장 및 검색하고, 스토리지 사용량을 모니터링하고, 클라이언트가 수행할 수 있는 작업을 관리하는 데 사용하는 테넌트 계정을 생성하고 관리합니다. 
---
= 테넌트 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 S3 및 Swift 클라이언트가 StorageGRID 시스템을 사용하여 오브젝트를 저장 및 검색하고, 스토리지 사용량을 모니터링하고, 클라이언트가 수행할 수 있는 작업을 관리하는 데 사용하는 테넌트 계정을 생성하고 관리합니다.



== 테넌트 계정이란 무엇입니까?

테넌트 계정을 사용하면 S3(Simple Storage Service) REST API 또는 Swift REST API를 사용하는 클라이언트 애플리케이션이 StorageGRID에 개체를 저장하고 검색할 수 있습니다.

각 테넌트 계정은 계정을 생성할 때 지정하는 단일 프로토콜 사용을 지원합니다. 두 프로토콜을 모두 사용하는 StorageGRID 시스템에 오브젝트를 저장하고 검색하려면 S3 버킷 및 오브젝트, Swift 컨테이너 및 오브젝트, 두 개의 테넌트 계정을 만들어야 합니다. 각 테넌트 계정에는 고유한 계정 ID, 인증된 그룹 및 사용자, 버킷 또는 컨테이너 및 객체가 있습니다.

필요에 따라 시스템에 저장된 객체를 다른 엔터티로 분리하려는 경우 추가 테넌트 계정을 생성할 수 있습니다. 예를 들어, 다음과 같은 사용 사례에서 여러 테넌트 계정을 설정할 수 있습니다.

* * 기업 활용 사례: * 엔터프라이즈 애플리케이션에서 StorageGRID 시스템을 관리하는 경우 조직의 여러 부서에서 그리드의 객체 스토리지를 분리할 수 있습니다. 이 경우 마케팅 부서, 고객 지원 부서, 인사 부서 등에 대한 테넌트 계정을 만들 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하는 경우 S3 버킷 및 버킷 정책을 사용하여 엔터프라이즈의 부서 간에 오브젝트를 분리할 수 있습니다. 테넌트 계정은 사용할 필요가 없습니다. 자세한 내용은 S3 클라이언트 애플리케이션 구현 지침을 참조하십시오.

* * 서비스 공급자 활용 사례: * StorageGRID 시스템을 서비스 공급자로 관리하는 경우 그리드의 객체 스토리지를 그리드의 스토리지를 임대할 다른 엔터티로 분리할 수 있습니다. 이 경우 회사 A, 회사 B, 회사 C 등에 대한 테넌트 계정을 생성합니다.




== 테넌트 계정을 생성하고 구성합니다

테넌트 계정을 생성할 때 다음 정보를 지정합니다.

* 테넌트 계정의 표시 이름입니다.
* 테넌트 계정(S3 또는 Swift)에서 사용할 클라이언트 프로토콜입니다.
* S3 테넌트 계정의 경우: 테넌트 계정에 S3 버킷을 포함하는 플랫폼 서비스를 사용할 수 있는 권한이 있는지 여부 테넌트 계정에서 플랫폼 서비스를 사용하도록 허용하는 경우 해당 사용자의 사용을 지원하도록 그리드가 구성되어 있는지 확인해야 합니다. "플랫폼 서비스"를 참조하십시오.
* 필요한 경우 테넌트 계정의 스토리지 할당량 -- 테넌트의 객체에 사용할 수 있는 최대 GB, 테라바이트 또는 PB입니다. 할당량이 초과되면 테넌트가 새 객체를 생성할 수 없습니다.
+

NOTE: 테넌트의 스토리지 할당량은 물리적 크기(디스크 크기)가 아닌 논리적 양(오브젝트 크기)을 나타냅니다.

* StorageGRID 시스템에 대해 ID 페더레이션이 설정된 경우 테넌트 계정을 구성할 수 있는 루트 액세스 권한이 있는 통합 그룹입니다.
* StorageGRID 시스템에서 SSO(Single Sign-On)를 사용하지 않는 경우 테넌트 계정이 자체 ID 소스를 사용할지 또는 그리드의 ID 소스를 공유할지 여부 및 테넌트의 로컬 루트 사용자의 초기 암호를 공유할지 여부


테넌트 계정이 생성된 후 다음 작업을 수행할 수 있습니다.

* * GRID용 플랫폼 서비스 관리 *: 테넌트 계정에 대해 플랫폼 서비스를 사용하는 경우, 플랫폼 서비스 메시지가 전달되는 방법과 StorageGRID 배포에서 플랫폼 서비스를 사용하는 데 필요한 네트워킹 요구 사항을 이해해야 합니다.
* * 테넌트 계정의 스토리지 사용량 모니터링 *: 테넌트가 해당 계정을 사용하기 시작한 후 Grid Manager를 사용하여 각 테넌트가 사용하는 스토리지 양을 모니터링할 수 있습니다.
+

NOTE: 노드가 그리드의 다른 노드로부터 격리되면 테넌트의 스토리지 사용량 값이 최신 상태가 아닐 수 있습니다. 네트워크 연결이 복원되면 합계가 업데이트됩니다.

+
테넌트에 대해 할당량을 설정한 경우 * 테넌트 할당량 사용량 높음 * 알림을 설정하여 테넌트가 할당량을 사용하고 있는지 확인할 수 있습니다. 활성화된 경우 테넌트가 할당량의 90%를 사용한 경우 이 경고가 트리거됩니다. 자세한 내용은 StorageGRID 모니터링 및 문제 해결 설명서의 경고 참조를 참조하십시오.

* * 클라이언트 작업 구성 *: 일부 클라이언트 작업이 금지되는지 여부를 구성할 수 있습니다.




== S3 테넌트를 구성합니다

S3 테넌트 계정이 생성된 후 테넌트 사용자는 테넌트 관리자에 액세스하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 통합을 설정하고(ID 소스를 그리드와 공유하지 않는 경우) 로컬 그룹 및 사용자를 생성합니다
* S3 액세스 키 관리
* S3 버킷 생성 및 관리
* 스토리지 사용량 모니터링
* 플랫폼 서비스 사용(활성화된 경우)



IMPORTANT: S3 테넌트 사용자는 테넌트 관리자를 사용하여 S3 액세스 키 및 버킷을 생성 및 관리할 수 있지만, S3 클라이언트 애플리케이션을 사용하여 오브젝트를 수집 및 관리해야 합니다.



== Swift 테넌트를 구성합니다

Swift 테넌트 계정이 생성된 후 테넌트의 루트 사용자는 테넌트 관리자에 액세스하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 통합을 설정하고(ID 소스를 그리드와 공유하지 않는 경우) 로컬 그룹 및 사용자를 만듭니다
* 스토리지 사용량 모니터링



IMPORTANT: Swift 사용자는 테넌트 관리자에 액세스하려면 루트 액세스 권한이 있어야 합니다. 그러나 루트 액세스 권한은 사용자가 Swift REST API에 인증하여 컨테이너를 생성하고 객체를 수집하는 것을 허용하지 않습니다. 사용자는 Swift REST API에 인증할 수 있는 Swift 관리자 권한이 있어야 합니다.

xref:../tenant/index.adoc[테넌트 계정을 사용합니다]
