---
permalink: admin/removing-nfs-audit-client-from-audit-share.html 
sidebar: sidebar 
keywords: nfs audit client, remove audit client 
summary: NFS 감사 클라이언트는 IP 주소를 기반으로 감사 공유에 대한 액세스 권한이 부여됩니다. IP 주소를 제거하여 기존 감사 클라이언트를 제거할 수 있습니다. 
---
= 감사 공유에서 NFS 감사 클라이언트를 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 감사 클라이언트는 IP 주소를 기반으로 감사 공유에 대한 액세스 권한이 부여됩니다. IP 주소를 제거하여 기존 감사 클라이언트를 제거할 수 있습니다.

.필요한 것
* 루트/관리자 계정 암호(해당 패키지에서 사용 가능)가 있는 "passwords.txt" 파일이 있습니다.
* "Configuration.txt" 파일이 있습니다(해당 패키지에서 사용 가능).


.이 작업에 대해
감사 공유에 액세스할 수 있는 마지막 IP 주소는 제거할 수 없습니다.

.단계
. 기본 관리자 노드에 로그인합니다.
+
.. 'ssh admin@_primary_Admin_Node_IP_' 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
.. 루트로 전환하려면 다음 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



. NFS 구성 유틸리티 'config_nfs.rb'를 시작합니다
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. Audit share에서 IP address를 remove-ip-from-share에서 삭제한다
+
서버에 구성된 감사 공유의 번호가 매겨진 목록이 표시됩니다. 감사 공유는 '/var/local/audit/export'로 나열됩니다

. 감사 공유에 해당하는 번호('_audit_share_number_')를 입력합니다
+
감사 공유에 액세스할 수 있는 번호가 매겨진 IP 주소 목록이 표시됩니다.

. 제거할 IP 주소에 해당하는 번호를 입력합니다.
+
감사 공유가 업데이트되며 이 IP 주소를 가진 감사 클라이언트에서 더 이상 액세스가 허용되지 않습니다.

. 메시지가 표시되면 * Enter * 를 누릅니다.
+
NFS 구성 유틸리티가 표시됩니다.

. NFS 구성 유틸리티 'exit'를 닫습니다
. StorageGRID 배포가 다른 사이트에 추가 관리 노드가 있는 다중 데이터 센터 사이트 배포인 경우 필요에 따라 다음 감사 공유를 비활성화합니다.
+
.. 각 사이트의 관리자 노드에 원격으로 로그인:
+
... 'ssh admin@_grid_node_ip_' 명령을 입력합니다
... "passwords.txt" 파일에 나열된 암호를 입력합니다.
... 루트로 전환하려면 다음 명령을 입력합니다
... "passwords.txt" 파일에 나열된 암호를 입력합니다.


.. 이 단계를 반복하여 각 추가 관리 노드에 대한 감사 공유를 구성합니다.
.. 원격 관리 노드에 대한 원격 보안 셸 로그인을 'exit'로 닫습니다


. 명령 셸에서 'exit'를 로그아웃합니다

