---
permalink: admin/scheduling-data-migration.html 
sidebar: sidebar 
keywords: data migration schedule, monitor data migration 
summary: 필요한 기간 내에 ILM 정책에 따라 데이터를 배치할 수 있도록 데이터 마이그레이션을 예약하고 모니터링해야 합니다. 
---
= 데이터 마이그레이션 예약 및 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요한 기간 내에 ILM 정책에 따라 데이터를 배치할 수 있도록 데이터 마이그레이션을 예약하고 모니터링해야 합니다.



== 데이터 마이그레이션을 예약합니다

핵심 운영 시간 중에는 데이터 마이그레이션을 하지 마십시오. 시스템 사용량이 적은 야간, 주말 및 기타 시간으로 데이터 마이그레이션을 제한합니다.

가능한 경우 활동이 많은 기간 동안에는 데이터 마이그레이션을 예약하지 마십시오. 그러나 높은 활동 기간을 완전히 피하는 것이 실용적이지 않은 경우에는 관련 특성을 면밀히 모니터링하고 허용 가능한 값을 초과하는 경우 조치를 취하는 한 계속 진행하는 것이 안전합니다.



== 데이터 마이그레이션을 모니터링합니다

이 표에는 데이터 마이그레이션 중에 모니터링해야 하는 속성과 이러한 특성이 나타내는 문제가 나열되어 있습니다.

트래픽 분류 정책을 사용하여 수집 임계치를 조절할 경우, 다음 표에 설명된 통계와 함께 관찰된 비율을 모니터링하고 필요한 경우 제한을 줄일 수 있습니다.

[cols="1a,2a"]
|===
| 모니터링 | 설명 


 a| 
ILM 평가를 기다리는 개체의 수입니다
 a| 
. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. 배포 * > * 개요 * > * 기본 * 을 선택합니다.
. ILM 활동 섹션에서 다음 특성에 대해 표시된 개체 수를 모니터링합니다.
+
** * Awaiting-all(XQUZ) *: ILM 평가를 기다리는 총 개체 수.
** * Awaiting-Client(XCQZ) *: 클라이언트 작업에서 ILM 평가를 기다리는 총 오브젝트 수(예: 수집).


. 이러한 속성 중 하나에 대해 표시되는 오브젝트 수가 100,000개를 초과할 경우 개체의 수집 속도를 조절하여 StorageGRID 시스템의 로드를 줄입니다.




 a| 
타겟 아카이브 시스템의 스토리지 용량
 a| 
ILM 정책이 마이그레이션된 데이터의 복사본을 대상 아카이브 스토리지 시스템(테이프 또는 클라우드)에 저장하는 경우 대상 아카이브 스토리지 시스템의 용량을 모니터링하여 마이그레이션된 데이터에 충분한 용량이 있는지 확인하십시오.



 a| 
* Archive Node * > * ARC * > * Store *
 a| 
ARVF(Store Failures) * 속성에 대한 알람이 트리거되면 대상 아카이브 스토리지 시스템의 용량이 한계에 도달했을 수 있습니다. 대상이 되는 아카이브 스토리지 시스템을 확인하고 알람을 트리거한 문제를 모두 해결합니다.

|===