---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: '클라이언트 애플리케이션은 그리드 노드의 IP 주소와 해당 노드에 있는 서비스의 포트 번호를 사용하여 StorageGRID에 연결할 수 있습니다. 고가용성 \(HA\) 그룹을 구성한 경우 클라이언트 응용 프로그램은 HA 그룹의 가상 IP 주소를 사용하여 연결할 수 있습니다.' 
---
= 요약: 클라이언트 연결을 위한 IP 주소 및 포트
:icons: font
:imagesdir: ../media/


[role="lead"]
클라이언트 애플리케이션은 그리드 노드의 IP 주소와 해당 노드에 있는 서비스의 포트 번호를 사용하여 StorageGRID에 연결할 수 있습니다. HA(고가용성) 그룹이 구성되어 있는 경우 클라이언트 애플리케이션은 HA 그룹의 가상 IP 주소를 사용하여 연결할 수 있습니다.

이 표에는 클라이언트가 StorageGRID에 연결할 수 있는 다양한 방법과 각 연결 유형에 사용되는 IP 주소 및 포트가 요약되어 있습니다. 이 지침은 로드 밸런서 끝점과 HA(고가용성) 그룹이 이미 구성되어 있는 경우 그리드 관리자에서 이 정보를 찾는 방법을 설명합니다.

[cols="1a,1a,1a,1a"]
|===
| 연결 위치 | 클라이언트가 연결하는 서비스입니다 | IP 주소입니다 | 포트 


 a| 
HA 그룹
 a| 
로드 밸런서
 a| 
HA 그룹의 가상 IP 주소입니다
 a| 
* 로드 밸런서 엔드포인트 포트




 a| 
HA 그룹
 a| 
CLB

* 참고: * CLB 서비스는 더 이상 사용되지 않습니다.
 a| 
HA 그룹의 가상 IP 주소입니다
 a| 
기본 S3 포트:

* HTTPS: 8082
* HTTP: 8084


기본 Swift 포트:

* HTTPS: 8083
* HTTP: 8085




 a| 
관리자 노드
 a| 
로드 밸런서
 a| 
관리 노드의 IP 주소입니다
 a| 
* 로드 밸런서 엔드포인트 포트




 a| 
게이트웨이 노드
 a| 
로드 밸런서
 a| 
게이트웨이 노드의 IP 주소입니다
 a| 
* 로드 밸런서 엔드포인트 포트




 a| 
게이트웨이 노드
 a| 
CLB

* 참고: * CLB 서비스는 더 이상 사용되지 않습니다.
 a| 
게이트웨이 노드의 IP 주소입니다

* 참고: * 기본적으로 CLB 및 LDR용 HTTP 포트는 사용되지 않습니다.
 a| 
기본 S3 포트:

* HTTPS: 8082
* HTTP: 8084


기본 Swift 포트:

* HTTPS: 8083
* HTTP: 8085




 a| 
스토리지 노드
 a| 
LDR
 a| 
스토리지 노드의 IP 주소입니다
 a| 
기본 S3 포트:

* HTTPS: 18082
* HTTP: 18084


기본 Swift 포트:

* HTTPS: 18083
* HTTP: 18085


|===
S3 클라이언트를 게이트웨이 노드 HA 그룹의 로드 밸런서 끝점에 연결하려면 아래와 같이 구조화된 URL을 사용합니다.

* "https://_VIP-of-HA-group:LB-endpoint-port_`


예를 들어 HA 그룹의 가상 IP 주소가 192.0.2.5이고 S3 로드 밸런서 끝점의 포트 번호가 10443인 경우 S3 클라이언트는 다음 URL을 사용하여 StorageGRID에 연결할 수 있습니다.

* '\https://192.0.2.5:10443`


Swift 클라이언트를 게이트웨이 노드 HA 그룹의 로드 밸런서 끝점에 연결하려면 아래와 같이 구조화된 URL을 사용합니다.

* "https://_VIP-of-HA-group:LB-endpoint-port_`


예를 들어 HA 그룹의 가상 IP 주소가 192.0.2.6이고 Swift 로드 밸런서 끝점의 포트 번호가 10444인 경우 Swift 클라이언트는 다음 URL을 사용하여 StorageGRID에 연결할 수 있습니다.

* '\https://192.0.2.6:10444`


클라이언트가 StorageGRID에 연결하는 데 사용하는 IP 주소에 대한 DNS 이름을 구성할 수 있습니다. 로컬 네트워크 관리자에게 문의하십시오.

.단계
. 를 사용하여 Grid Manager에 로그인합니다 xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저].
. 그리드 노드의 IP 주소를 찾으려면
+
.. 노드 * 를 선택합니다.
.. 연결할 관리 노드, 게이트웨이 노드 또는 스토리지 노드를 선택합니다.
.. 개요 * 탭을 선택합니다.
.. 노드 정보 섹션에서 노드의 IP 주소를 확인합니다.
.. IPv6 주소 및 인터페이스 매핑을 보려면 * 더 보기 * 를 선택합니다.
+
클라이언트 응용 프로그램에서 목록의 IP 주소로의 연결을 설정할 수 있습니다.

+
*** eth0: * 그리드 네트워크
*** * eth1: * 관리 네트워크(옵션)
*** * eth2: * 클라이언트 네트워크(옵션)
+

NOTE: 관리 노드 또는 게이트웨이 노드를 보고 있고 고가용성 그룹의 활성 노드인 경우 HA 그룹의 가상 IP 주소가 eth2에 표시됩니다.





. 고가용성 그룹의 가상 IP 주소를 찾으려면 다음을 수행합니다.
+
.. 구성 * > * 네트워크 * > * 고가용성 그룹 * 을 선택합니다.
.. 표에서 HA 그룹의 가상 IP 주소를 확인합니다.


. 로드 밸런서 끝점의 포트 번호를 찾으려면 다음을 수행합니다.
+
.. 구성 * > * 네트워크 * > * 로드 밸런서 엔드포인트 * 를 선택합니다.
+
로드 밸런서 끝점 페이지가 나타나고 이미 구성된 끝점 목록이 표시됩니다.

.. 끝점을 선택하고 * 끝점 편집 * 을 선택합니다.
+
끝점 편집 창이 열리고 끝점에 대한 추가 세부 정보가 표시됩니다.

.. 선택한 끝점이 올바른 프로토콜(S3 또는 Swift)과 함께 사용하도록 구성되었는지 확인한 후 * Cancel * (취소 *)을 선택합니다.
.. 클라이언트 연결에 사용할 끝점의 포트 번호를 확인합니다.
+

NOTE: 포트 번호가 80 또는 443이면 해당 포트가 관리 노드에 예약되므로 끝점이 게이트웨이 노드에서만 구성됩니다. 다른 모든 포트는 게이트웨이 노드와 관리 노드 모두에서 구성됩니다.




