---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 여러 개의 비기본 관리 노드가 있을 수 있습니다. 
---
= 관리 노드의 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 여러 개의 비기본 관리 노드가 있을 수 있습니다.

그리드 관리자 또는 테넌트 관리자에 로그인할 때 관리 노드에 연결됩니다. 모든 관리 노드에 연결할 수 있으며 각 관리 노드에는 StorageGRID 시스템의 유사한 보기가 표시됩니다. 그러나 기본 관리 노드를 사용하여 유지 관리 절차를 수행해야 합니다.

관리 노드를 사용하여 S3 및 Swift 클라이언트 트래픽의 로드 밸런싱을 수행할 수도 있습니다.

관리 노드는 다음 서비스를 호스팅합니다.

* AMS 서비스
* CMN 서비스
* NMS 서비스
* Prometheus 서비스
* 로드 밸런서 및 고가용성 서비스(S3 및 Swift 클라이언트 트래픽 지원)


관리 노드는 그리드 관리 API 및 테넌트 관리 API의 요청을 처리하는 관리 애플리케이션 프로그램 인터페이스(mgmt-API)도 지원합니다. 을 참조하십시오 xref:using-grid-management-api.adoc[Grid Management API를 사용합니다].



== AMS 서비스의 정의

AMS(Audit Management System) 서비스는 시스템 활동 및 이벤트를 추적합니다.



== CMN 서비스의 정의

CMN(Configuration Management Node) 서비스는 모든 서비스에 필요한 시스템 전반의 연결 및 프로토콜 기능을 관리합니다. 또한 CMN 서비스는 그리드 작업을 실행하고 모니터링하는 데 사용됩니다. StorageGRID 배포당 하나의 CMN 서비스만 있습니다. CMN 서비스를 호스팅하는 관리 노드를 기본 관리 노드라고 합니다.



== NMS 서비스의 정의

NMS(네트워크 관리 시스템) 서비스는 StorageGRID 시스템의 브라우저 기반 인터페이스인 그리드 관리자를 통해 표시되는 모니터링, 보고 및 구성 옵션을 강화합니다.



== Prometheus 서비스의 정의

Prometheus 서비스는 모든 노드의 서비스에서 시계열 메트릭을 수집합니다.
