---
permalink: s3/benefits-of-active-http-connections.html 
sidebar: sidebar 
keywords: active http connection benefits 
summary: '스토리지 노드 또는 게이트웨이 노드의 CLB 서비스\(더 이상 사용되지 않음\)에 직접 연결하는 경우 HTTP 연결이 지속적으로 트랜잭션을 수행하더라도 활성 HTTP 연결 기간을 최대 10분으로 제한해야 합니다.' 
---
= 활성 HTTP 연결의 이점
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드 또는 게이트웨이 노드의 CLB 서비스(더 이상 사용되지 않음)에 직접 연결하는 경우 HTTP 연결이 지속적으로 트랜잭션을 수행하더라도 활성 HTTP 연결 기간을 최대 10분으로 제한해야 합니다.

연결을 열어 두어야 하는 최대 기간을 결정하는 것은 연결 지속성의 이점과 내부 시스템 리소스에 대한 연결을 이상적으로 할당하는 것입니다.

클라이언트가 스토리지 노드 또는 CLB 서비스에 접속할 경우 활성 HTTP 연결을 제한하면 다음과 같은 이점이 있습니다.

* StorageGRID 시스템 전체에서 최적의 로드 밸런싱을 지원합니다.
+
CLB 서비스를 사용할 때는 오래 지속되는 TCP/IP 연결을 방지하여 StorageGRID 시스템 전체의 로드 밸런싱을 최적화해야 합니다. HTTP 연결을 다시 설정하고 재조정할 수 있도록 클라이언트 응용 프로그램을 구성하여 각 HTTP 연결 기간을 추적하고 설정된 시간 후에 HTTP 연결을 닫아야 합니다.

+
CLB 서비스는 클라이언트 응용 프로그램이 HTTP 연결을 설정할 때 StorageGRID 시스템 전체의 로드 균형을 조정합니다. 시간이 지남에 따라 로드 밸런싱 요구 사항이 변경됨에 따라 HTTP 연결이 더 이상 최적화되지 않을 수 있습니다. 시스템은 클라이언트 애플리케이션이 각 트랜잭션에 대해 별도의 HTTP 연결을 설정할 때 최상의 로드 밸런싱을 수행하지만, 이 경우 영구 연결과 관련된 훨씬 더 가치 있는 이득을 얻을 수 없습니다.

+

NOTE: CLB 서비스는 더 이상 사용되지 않습니다.

* 클라이언트 응용 프로그램이 사용 가능한 공간이 있는 LDR 서비스로 HTTP 트랜잭션을 보낼 수 있도록 합니다.
* 유지보수 절차를 시작할 수 있습니다.
+
일부 유지 관리 절차는 진행 중인 모든 HTTP 연결이 완료된 후에만 시작됩니다.



부하 분산 서비스에 대한 클라이언트 연결의 경우 일부 유지 관리 절차를 즉시 시작할 수 있도록 개방 연결 기간을 제한하는 것이 유용할 수 있습니다. 클라이언트 연결 기간이 제한되지 않으면 활성 연결이 자동으로 종료되는 데 몇 분이 걸릴 수 있습니다.
