---
permalink: s3/complete-multipart-upload.html 
sidebar: sidebar 
keywords: multipart upload, object, object size 
summary: 전체 다중 파트 업로드 작업은 이전에 업로드한 파트를 조립하여 개체의 여러 부분 업로드를 완료합니다. 
---
= 멀티파트 업로드를 완료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전체 다중 파트 업로드 작업은 이전에 업로드한 파트를 조립하여 개체의 여러 부분 업로드를 완료합니다.



== 충돌 해결

동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "Latest-WINS" 평가 시기는 S3 클라이언트가 작업을 시작할 때가 아니라 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 합니다.



== 요청 헤더

"x-amz-storage-class" 요청 헤더가 지원되며 일치하는 ILM 규칙에서 이중 커밋 또는 밸런스의 수집 동작을 지정하는 경우 StorageGRID에서 생성되는 개체 복사본 수에 영향을 줍니다.

* '표준'입니다
+
(기본값) ILM 규칙이 이중 커밋 옵션을 사용하거나 균형 옵션이 중간 복사본 생성으로 돌아올 때 이중 커밋 수집 작업을 지정합니다.

* Reduced_redundancy를 선택합니다
+
ILM 규칙이 이중 커밋 옵션을 사용하거나 균형 옵션이 중간 복사본 생성으로 돌아올 때 단일 커밋 수집 작업을 지정합니다.

+

NOTE: S3 오브젝트 잠금이 활성화된 버킷으로 오브젝트를 인스팅하는 경우 REDED_REPREADITORY' 옵션이 무시됩니다. 개체를 레거시 준수 버킷으로 인스팅하는 경우 REDED_REPREADITORIAL' 옵션은 오류를 반환합니다. StorageGRID은 규정 준수 요구 사항이 충족될 수 있도록 항상 이중 커밋 수집을 수행합니다.




IMPORTANT: 15일 이내에 여러 부분 업로드가 완료되지 않으면 작업이 비활성으로 표시되고 모든 관련 데이터가 시스템에서 삭제됩니다.


NOTE: 반환된 "ETag" 값은 MD5 데이터 합계가 아니라 다중 파트 오브젝트에 대한 "ETag" 값의 Amazon S3 API 구현을 따릅니다.



== 버전 관리

이 작업은 여러 부분 업로드를 완료합니다. 버켓에 대해 버전 관리가 활성화된 경우 다중 파트 업로드가 완료되면 개체 버전이 생성됩니다.

버켓에 대한 버전 관리가 활성화된 경우 저장할 개체의 버전에 대해 고유한 rionId가 자동으로 생성됩니다. 이 인상파 ID는 X-amz-version-id 응답 헤더를 사용하여 응답에서도 반환됩니다.

버전 관리가 일시 중단된 경우 개체 버전은 null rionId로 저장되며, null 버전이 이미 있는 경우에는 덮어쓰게 됩니다.


NOTE: 버켓에 대해 버전 관리가 활성화된 경우, 같은 개체 키에서 동시 다중 파트 업로드가 완료된 경우에도 다중 파트 업로드를 완료하면 항상 새 버전이 생성됩니다. 버켓에 대해 버전 관리를 사용하지 않으면 다중 파트 업로드를 시작한 다음 다른 다중 파트 업로드를 시작하여 동일한 개체 키에서 먼저 완료할 수 있습니다. 비버전 버킷에서는 마지막으로 완료한 다중 파트 업로드가 우선 적용됩니다.



== 복제, 알림 또는 메타데이터 알림에 실패했습니다

플랫폼 서비스에 대해 다중 파트 업로드가 발생하는 버킷이 구성된 경우 연결된 복제 또는 알림 작업이 실패한 경우에도 다중 파트 업로드가 성공합니다.

이 경우 SMTT(Grid Manager on Total Events)에서 경보가 발생합니다. 마지막 이벤트 메시지는 알림이 실패한 마지막 객체에 대해 ''버킷 이름 오브젝트 키에 대한 알림을 게시하지 못했습니다''라고 표시됩니다. (이 메시지를 보려면 * nodes * > *_Storage Node_ * > * Events * 를 선택합니다. 테이블 상단의 마지막 이벤트 보기) 이벤트 메시지는 '/var/local/log/bycast-err.log'에도 나열됩니다.

테넌트는 개체의 메타데이터 또는 태그를 업데이트하여 실패한 복제 또는 알림을 트리거할 수 있습니다. 테넌트는 불필요한 변경을 방지하기 위해 기존 값을 다시 제출할 수 있습니다.

.관련 정보
xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]
