---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: S3 오브젝트 가져오기 요청을 사용하여 S3 버킷에서 오브젝트를 검색할 수 있습니다. 
---
= 객체 가져오기
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 오브젝트 가져오기 요청을 사용하여 S3 버킷에서 오브젝트를 검색할 수 있습니다.



== 개체 및 다중 파트 개체를 가져옵니다

'PARTNUMBER' 요청 파라미터를 사용하면 멀티파트 또는 분할된 개체의 특정 부분을 검색할 수 있습니다. X-amz-MP-parts-count 응답 요소는 개체의 부품 수를 나타냅니다.

분할/다중 파트 개체와 비분할/비다중 파트 개체 모두에 대해 'PARTNUMBER'를 1로 설정할 수 있지만, "x-amz-MP-parts-count" 응답 요소는 분할된 또는 다중 파트 개체에 대해서만 반환됩니다.



== 고객이 제공한 암호화 키(SSE-C)를 사용하여 서버측 암호화를 위한 요청 헤더

사용자가 제공한 고유 키로 개체를 암호화한 경우 머리글 3개를 모두 사용합니다.

* X-amz-서버측-암호화-고객-알고리즘: AES256 지정.
* 'x-amz-서버측-암호화-고객-키': 오브젝트의 암호화 키를 지정합니다.
* X-amz-서버측-암호화-고객-키-MD5: 오브젝트의 암호화 키에 대한 MD5 다이제스트를 지정합니다.



IMPORTANT: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.



== 사용자 메타데이터의 UTF-8 문자

StorageGRID는 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자가 있는 개체에 대한 요청을 가져오십시오. 키 이름이나 값에 인쇄할 수 없는 문자가 포함되어 있으면 "x-amz-missing-meta" 헤더가 반환되지 않습니다.



== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않으며 'XNotImplemented'를 반환합니다.

* X-amz-웹사이트-리디렉션-위치




== 버전 관리

rrionId 서브리소스를 지정하지 않으면 가장 최근 버전의 객체가 버전 관리되는 버킷에 페치됩니다. 객체의 현재 버전이 삭제 표식이면 x-amz-DELETE-MARKER 응답 헤더가 TRUE로 설정된 상태로 "Not Found" 상태가 반환됩니다.



== Get Object for Cloud Storage Pool 개체의 동작

개체가 클라우드 스토리지 풀에 저장된 경우(정보 수명 주기 관리를 통해 개체 관리 지침 참조) 오브젝트 가져오기 요청의 동작은 개체의 상태에 따라 달라집니다. 자세한 내용은 " 헤드 개체 "를 참조하십시오.


NOTE: 객체가 클라우드 스토리지 풀에 저장되고 오브젝트 복사본이 하나 이상 그리드에 존재하는 경우, 객체 가져오기 요청은 클라우드 스토리지 풀에서 데이터를 검색하기 전에 그리드에서 데이터를 검색하려고 시도합니다.

|===
| 개체의 상태입니다 | Get Object의 동작입니다 


 a| 
StorageGRID로 수집되었지만 아직 ILM에 의해 평가되지 않은 오브젝트 또는 기존 스토리지 풀에 저장된 오브젝트 또는 삭제 코딩 사용
 a| 
200OK

개체의 복사본이 검색됩니다.



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
200OK

개체의 복사본이 검색됩니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었습니다
 a| 
403 금지됨, InvalidObjectState

개체를 검색 가능한 상태로 복원하려면 POST 개체 복원 요청을 사용합니다.



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
403 금지됨, InvalidObjectState

POST 개체 복원 요청이 완료될 때까지 기다립니다.



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
200OK

개체의 복사본이 검색됩니다.

|===


== 클라우드 스토리지 풀에서 다중 또는 분할 오브젝트

여러 부분 개체를 업로드했거나 StorageGRID가 큰 개체를 세그먼트로 분할한 경우 StorageGRID는 개체의 부분 또는 세그먼트의 하위 집합을 샘플링하여 클라우드 저장소 풀에서 개체를 사용할 수 있는지 여부를 결정합니다. 일부 개체의 일부가 이미 검색 불가능한 상태로 전환되었거나 개체의 일부가 아직 복원되지 않은 경우 Get Object 요청이 '200 OK'를 잘못 반환할 수도 있습니다.

다음과 같은 경우:

* Get Object 요청이 일부 데이터를 반환하지만 전송 도중에 중지될 수 있습니다.
* 이후 개체 가져오기 요청이 403 사용 금지 를 반환할 수 있습니다.


xref:using-server-side-encryption.adoc[서버측 암호화를 사용합니다]

xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:post-object-restore.adoc[사후 개체 복원]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 작업이 감사 로그에서 추적되었습니다]
