---
permalink: s3/get-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket consistency request 
summary: Get Bucket 정합성 보장 요청을 사용하면 특정 버킷에 적용되는 정합성 보장 수준을 확인할 수 있습니다. 
---
= 버킷 정합성 보장 요청 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Get Bucket 정합성 보장 요청을 사용하면 특정 버킷에 적용되는 정합성 보장 수준을 확인할 수 있습니다.

기본 정합성 보장 컨트롤은 새로 생성된 객체에 대해 읽기/쓰기 작업을 보장하도록 설정됩니다.

이 작업을 완료하려면 S3:GetBucketConsistency 권한이 있거나 계정 루트가 됩니다.



== 요청 예

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 응답

응답 XML에서 "<Consistency>"는 다음 값 중 하나를 반환합니다.

|===
| 일관성 제어 | 설명 


 a| 
모두
 a| 
모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.



 a| 
강함 - 글로벌
 a| 
모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 정합성을 보장합니다.



 a| 
강력한 사이트
 a| 
사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.



 a| 
읽기-후-새로-쓰기
 a| 
(기본값) 새 객체에 대한 읽기 후 쓰기 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 Amazon S3 일관성 보장과 가장 비슷합니다.

* 참고: * 응용 프로그램이 존재하지 않는 개체에 대한 헤드 요청을 사용하는 경우 하나 이상의 스토리지 노드를 사용할 수 없는 경우 500개의 내부 서버 오류가 발생할 수 있습니다. 이러한 오류를 방지하려면 Amazon S3와 유사한 일관성 보장이 필요하지 않는 한 일관성 제어를 ""사용 가능""으로 설정합니다.



 a| 
사용 가능(헤드 작업의 최종 일관성)
 a| 
"새 쓰기 후 다시 쓰기" 정합성 수준과 동일하게 동작하지만 헤드 작업에 대한 최종 정합성 보장만 제공합니다. 스토리지 노드를 사용할 수 없는 경우 "새 쓰기 후"보다 헤드 작업에 더 높은 가용성을 제공합니다. 헤드 작업에 대한 Amazon S3 정합성 보장과 다릅니다.

|===


== 응답 예

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
xref:consistency-controls.adoc[일관성 제어]
