---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: head object 
summary: S3 헤드 오브젝트 요청을 사용하여 오브젝트 자체를 반환하지 않고 오브젝트에서 메타데이터를 검색할 수 있습니다. 
---
= 헤드 개체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 헤드 오브젝트 요청을 사용하여 오브젝트 자체를 반환하지 않고 오브젝트에서 메타데이터를 검색할 수 있습니다. 객체가 클라우드 스토리지 풀에 저장된 경우 헤드 객체를 사용하여 객체의 전환 상태를 확인할 수 있습니다.



== 헤드 개체 및 다중 파트 개체

'PARTNUMBER' 요청 파라미터를 사용하면 멀티파트 또는 분할된 개체의 특정 부분에 대한 메타데이터를 검색할 수 있습니다. X-amz-MP-parts-count 응답 요소는 개체의 부품 수를 나타냅니다.

분할/다중 파트 개체와 비분할/비다중 파트 개체 모두에 대해 'PARTNUMBER'를 1로 설정할 수 있지만, "x-amz-MP-parts-count" 응답 요소는 분할된 또는 다중 파트 개체에 대해서만 반환됩니다.



== 고객이 제공한 암호화 키(SSE-C)를 사용하여 서버측 암호화를 위한 요청 헤더

사용자가 제공한 고유 키로 개체를 암호화한 경우 이 헤더 3개를 모두 사용합니다.

* X-amz-서버측-암호화-고객-알고리즘: AES256 지정.
* 'x-amz-서버측-암호화-고객-키': 오브젝트의 암호화 키를 지정합니다.
* X-amz-서버측-암호화-고객-키-MD5: 오브젝트의 암호화 키에 대한 MD5 다이제스트를 지정합니다.



IMPORTANT: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.



== 사용자 메타데이터의 UTF-8 문자

StorageGRID는 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자가 있는 개체에 대한 헤드 요청은 키 이름이나 값에 인쇄할 수 없는 문자가 포함된 경우 "x-amz-missing-meta" 헤더를 반환하지 않습니다.



== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않으며 'XNotImplemented'를 반환합니다.

* X-amz-웹사이트-리디렉션-위치




== 클라우드 스토리지 풀 객체에 대한 응답 헤더입니다

객체가 클라우드 스토리지 풀에 저장된 경우(정보 수명 주기 관리를 통해 객체 관리 지침 참조) 다음 응답 헤더가 반환됩니다.

* X-amz-STERAGE-CLASS:빙하
* X-amz-restore


응답 헤더는 클라우드 스토리지 풀로 이동되는 오브젝트의 상태에 대한 정보를 제공하며, 선택적으로 검색할 수 없는 상태로 전환된 후 복구됩니다.

|===
| 개체의 상태입니다 | 헤드 객체에 대한 응답 


 a| 
StorageGRID로 수집되었지만 아직 ILM에 의해 평가되지 않은 오브젝트 또는 기존 스토리지 풀에 저장된 오브젝트 또는 삭제 코딩 사용
 a| 
200 OK (특별한 응답 헤더는 반환되지 않음)



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
200OK

X-amz-STERAGE-CLASS:빙하

''x-amz-restore:ongoing-request="false", expiry-date="sat, 23 JULY 20 2030 00:00:00:00 GMT"

객체가 검색 불가능한 상태로 전환되기 전까지 만료 날짜 값은 향후 일정 원거리 시간으로 설정됩니다. 정확한 전환 시간은 StorageGRID 시스템에 의해 제어되지 않습니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었지만 하나 이상의 복사본이 그리드에 있습니다
 a| 
200OK

X-amz-STERAGE-CLASS:빙하

''x-amz-restore:ongoing-request="false", expiry-date="sat, 23 JULY 20 2030 00:00:00:00 GMT"

만료 날짜 값은 앞으로 어느 정도 먼 시간으로 설정됩니다.

* 참고 *: 그리드의 복사본을 사용할 수 없는 경우(예: 스토리지 노드가 다운된 경우), 객체를 성공적으로 검색하기 전에 POST 객체 복원 요청을 발행하여 클라우드 스토리지 풀에서 복제본을 복원해야 합니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었으며 그리드에 복사본이 없습니다
 a| 
200OK

X-amz-STERAGE-CLASS:빙하



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
200OK

X-amz-STERAGE-CLASS:빙하

''x-amz-restore:진행 중인-request="true"'



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
200OK

X-amz-STERAGE-CLASS:빙하

"x-amz-restore:ongoing-request="false", expiry-date="sat, 23 July 20 2018 00:00:00:00 GMT"

'만료 날짜'는 Cloud Storage Pool의 객체가 검색 불가능한 상태로 반환되는 시점을 나타냅니다.

|===


== Cloud Storage Pool에서 다중 또는 분할 오브젝트 지원

여러 부분 개체를 업로드했거나 StorageGRID가 큰 개체를 세그먼트로 분할한 경우 StorageGRID는 개체의 부분 또는 세그먼트의 하위 집합을 샘플링하여 클라우드 저장소 풀에서 개체를 사용할 수 있는지 여부를 결정합니다. 일부 개체의 일부가 이미 검색 불가능 상태로 전환되었거나 개체의 일부가 아직 복원되지 않은 경우 헤드 객체 요청이 "x-amz-restore:ongoing-request="false""를 잘못 반환할 수 있습니다.



== 버전 관리

rrionId 서브리소스를 지정하지 않으면 가장 최근 버전의 객체가 버전 관리되는 버킷에 페치됩니다. 객체의 현재 버전이 삭제 표식이면 x-amz-DELETE-MARKER 응답 헤더가 TRUE로 설정된 상태로 "Not Found" 상태가 반환됩니다.

xref:using-server-side-encryption.adoc[서버측 암호화를 사용합니다]

xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:post-object-restore.adoc[사후 개체 복원]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 작업이 감사 로그에서 추적되었습니다]
