---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, uploads 
summary: 다중 파트 업로드 시작 작업은 개체에 대한 다중 파트 업로드를 시작하고 업로드 ID를 반환합니다. 
---
= 멀티파트 업로드를 시작합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
다중 파트 업로드 시작 작업은 개체에 대한 다중 파트 업로드를 시작하고 업로드 ID를 반환합니다.

X-amz-STERAGE-CLASS 요청 헤더는 지원된다. 'x-amz-storage-class'에 대해 제출된 가치는 수집 중에 StorageGRID가 오브젝트 데이터를 보호하는 방식에 영향을 주며, ILM에 의해 결정되는 StorageGRID 시스템에 저장된 개체의 영구 복사본의 수가 아닙니다.

수집된 개체와 일치하는 ILM 규칙이 Ingest 동작에 Strict 옵션을 사용하는 경우 "x-amz-storage-class" 헤더는 영향을 주지 않습니다.

X-amz-storage-class에 사용할 수 있는 값은 다음과 같다.

* '표준'(기본값)
+
** * 이중 커밋 *: ILM 규칙이 Ingest 동작에 대한 이중 커밋 옵션을 지정하는 경우, 개체가 수집되는 즉시 해당 개체의 두 번째 복사본이 생성되어 다른 스토리지 노드(이중 커밋)에 배포됩니다. ILM을 평가할 때 StorageGRID는 이러한 초기 중간 복사본이 규칙의 배치 지침을 충족하는지 여부를 결정합니다. 그렇지 않으면 새 오브젝트 복사본을 다른 위치에 만들어야 하고 초기 중간 복사본을 삭제해야 할 수 있습니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하고 StorageGRID이 규칙에 지정된 모든 복사본을 즉시 만들 수 없는 경우 StorageGRID은 다른 스토리지 노드에 두 개의 임시 복사본을 만듭니다.
+
StorageGRID에서 ILM 규칙(동기 배치)에 지정된 모든 오브젝트 복사본을 즉시 생성할 수 있으면 'x-amz-storage-class' 헤더가 효과가 없습니다.



* Reduced_redundancy를 선택합니다
+
** * 이중 커밋 *: ILM 규칙이 Ingest 동작에 대한 이중 커밋 옵션을 지정하는 경우 StorageGRID는 오브젝트가 수집될 때(단일 커밋) 단일 임시 복사본을 만듭니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하는 경우 StorageGRID은 시스템에서 규칙에 지정된 모든 사본을 즉시 만들 수 없는 경우에만 단일 중간 복사본을 만듭니다. StorageGRID에서 동기 배치를 수행할 수 있는 경우 이 머리글은 영향을 주지 않습니다. Reduced_redundancy 옵션은 개체와 일치하는 ILM 규칙이 복제된 단일 복사본을 만들 때 가장 적합합니다. 이 경우 'REDED_READITORY'를 사용하면 모든 수집 작업에 대해 불필요한 오브젝트 복사본을 생성하고 삭제할 필요가 없습니다.


+
다른 상황에서는 reducted_redundancy 옵션을 사용하지 않는 것이 좋습니다. REDED_READITAINEY는 수집 중에 오브젝트 데이터가 손실될 위험을 증가시킵니다. 예를 들어, ILM 평가가 발생하기 전에 실패한 스토리지 노드에 단일 복사본이 처음 저장되는 경우 데이터가 손실될 수 있습니다.



* 주의 *: 한 번에 하나의 복제 사본만 있으면 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.

reducted_redundancy를 지정하면 개체를 처음 인제스트할 때 생성되는 복제본 수만 영향을 받습니다. 활성 ILM 정책에 따라 개체를 평가할 때 개체의 복사본 수에 영향을 주지 않으며 StorageGRID 시스템에서 낮은 수준의 중복성에 데이터가 저장되지 않습니다.

* 참고 *: S3 오브젝트 잠금이 활성화된 버킷으로 오브젝트를 인스팅하는 경우, reducted_redundancy 옵션이 무시됩니다. 개체를 레거시 준수 버킷으로 인스팅하는 경우 REDED_REPREADITORIAL' 옵션은 오류를 반환합니다. StorageGRID은 규정 준수 요구 사항이 충족될 수 있도록 항상 이중 커밋 수집을 수행합니다.

지원되는 요청 헤더는 다음과 같습니다.

* 콘텐츠 유형
* x-amz-meta- 뒤에 사용자 정의 메타데이터를 포함하는 이름-값 쌍이 있습니다
+
사용자 정의 메타데이터에 대한 이름 값 쌍을 지정할 때 다음 일반 형식을 사용합니다.

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
ILM 규칙의 참조 시간으로 * 사용자 정의 작성 시간 * 옵션을 사용하려면 객체를 만들 때 기록하는 메타데이터의 이름으로 "creation-time"을 사용해야 합니다. 예를 들면 다음과 같습니다.

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
창조시간 값은 1970년 1월 1일 이후 초 단위로 평가된다.

+

NOTE: 레거시 규정 준수 기능이 설정된 버킷에 객체를 추가하는 경우 사용자 정의 메타데이터로 '생성 시간'을 추가할 수 없습니다. 오류가 반환됩니다.

* S3 오브젝트 잠금 요청 헤더:
+
** 'X-amz-object-lock-mode
** 'X-amz-object-lock-retain-until-date'
** X-amz-object-lock-legal-hold
+
이러한 헤더 없이 요청이 이루어지면 버킷 기본 보존 설정을 사용하여 개체 버전 보존 기간을 계산합니다.

+
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금 사용]



* SSE 요청 헤더:
+
** 'X-amz-서버측-암호화'
** X-amz-서버측-암호화-고객-키-MD5
** 'X-amz-서버측-암호화-고객-키'
** 'X-amz-서버측-암호화-고객-알고리즘'
+
<<Request headers for server-side encryption>>



+

NOTE: StorageGRID에서 UTF-8 문자를 처리하는 방법에 대한 자세한 내용은 Put Object 설명서를 참조하십시오.





== 서버측 암호화에 대한 요청 헤더

다음 요청 헤더를 사용하여 서버측 암호화를 사용하여 다중 파트 개체를 암호화할 수 있습니다. SSE 및 SSE-C 옵션은 상호 배타적입니다.

* * SSE *: StorageGRID에서 관리하는 고유 키로 객체를 암호화하려면 다중 파트 업로드 시작 요청에서 다음 헤더를 사용하십시오. 업로드 부품 요청에 이 헤더를 지정하지 마십시오.
+
** 'X-amz-서버측-암호화'


* * SSE-C *: 사용자가 제공 및 관리하는 고유 키를 사용하여 개체를 암호화하려는 경우 다중 파트 업로드 시작 요청(및 각 후속 업로드 파트 요청)에서 이 헤더 세 개를 모두 사용합니다.
+
** X-amz-서버측-암호화-고객-알고리즘: AES256 지정.
** 'X-amz-서버측-암호화-고객 키': 새 오브젝트의 암호화 키를 지정합니다.
** X-amz-서버측-암호화-고객-키-MD5: 새 개체의 암호화 키에 대해 MD5 다이제스트를 지정합니다.




* 주의: * 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.



== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않으며 'XNotImplemented'를 반환합니다

* X-amz-웹사이트-리디렉션-위치




== 버전 관리

멀티파트 업로드는 업로드 시작, 리스팅 업로드, 파트 업로드, 업로드된 파트 조립 및 업로드 완료를 위한 별도의 작업으로 구성됩니다. MultiPart Upload 작업이 완료되면 개체가 만들어지고 버전이 적용됩니다(해당하는 경우).

xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:using-server-side-encryption.adoc[서버측 암호화를 사용합니다]

xref:put-object.adoc[개체 를 넣습니다]
