---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: 이 섹션에서는 StorageGRID 시스템이 객체에 대해 S3 REST API 작업을 구축하는 방법에 대해 설명합니다. 
---
= 객체에 대한 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 StorageGRID 시스템이 객체에 대해 S3 REST API 작업을 구축하는 방법에 대해 설명합니다.

다음 조건은 모든 개체 작업에 적용됩니다.

* StorageGRID xref:consistency-controls.adoc[일관성 제어] 는 다음과 같은 경우를 제외하고 모든 개체 작업에서 지원됩니다.
+
** 객체 ACL을 가져옵니다
** '옵션 /'
** 개체를 법적 증거 자료 보관
** 개체 보존
** 개체 내용 을 선택합니다


* 동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "Latest-WINS" 평가 시기는 S3 클라이언트가 작업을 시작할 때가 아니라 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 합니다.
* StorageGRID 버킷의 모든 오브젝트는 익명 사용자 또는 다른 계정에서 만든 오브젝트를 포함하여 버킷 소유자가 소유합니다.
* Swift를 통해 StorageGRID 시스템으로 수집된 데이터 오브젝트는 S3를 통해 액세스할 수 없습니다.


다음 표에서는 StorageGRID에서 S3 REST API 오브젝트 작업을 구현하는 방법을 설명합니다.

[cols="1a,2a"]
|===
| 작동 | 구축 


 a| 
개체 삭제
 a| 
멀티팩터 인증(MFA)과 응답 헤더 X-amz-MFA는 지원되지 않습니다.

오브젝트 삭제 요청을 처리할 때 StorageGRID는 저장된 모든 위치에서 오브젝트의 모든 복사본을 즉시 제거하려고 시도합니다. 성공하면 StorageGRID는 즉시 클라이언트에 응답을 반환합니다. 위치를 일시적으로 사용할 수 없기 때문에 30초 이내에 모든 복사본을 제거할 수 없는 경우 StorageGRID는 제거할 복사본을 대기시킨 다음 클라이언트에 성공 여부를 표시합니다.

* 버전 관리 *

특정 버전을 제거하려면 요청자가 버킷 소유자여야 하며 rrionId 하위 리소스를 사용해야 합니다. 이 하위 리소스를 사용하면 버전이 영구적으로 삭제됩니다. 만약 rionId가 삭제 표식에 해당하면 응답 헤더 x-amz-delete-marker가 TRUE로 설정된다.

* 버전 지원 버킷에서 rionId 하위 리소스 없이 개체를 삭제하면 삭제 표식이 생성됩니다. 삭제 마커의 rionId는 x-amz-version-id 응답 헤더를 사용하여 반환되고 x-amz-delete-marker 응답 헤더는 TRUE로 설정됩니다.
* 버전 일시 중지된 버킷에서 rionId ' 하위 리소스 없이 개체를 삭제하면 기존 'null' 버전 또는 'null' 삭제 표식이 영구적으로 삭제되고 새 'null' 삭제 표식이 생성됩니다. x-amz-DELETE-MARKER 응답 헤더가 TRUE로 설정된 상태로 반환됩니다.


* 참고 *: 경우에 따라 객체에 대해 여러 개의 삭제 마커가 존재할 수 있습니다.



 a| 
여러 개체를 삭제합니다
 a| 
멀티팩터 인증(MFA)과 응답 헤더 X-amz-MFA는 지원되지 않습니다.

동일한 요청 메시지에서 여러 객체를 삭제할 수 있습니다.



 a| 
개체 태그 지정 삭제
 a| 
"태그 지정" 하위 리소스를 사용하여 개체에서 모든 태그를 제거합니다. 모든 Amazon S3 REST API 동작으로 구현됩니다.

* 버전 관리 *

요청에 rionId 쿼리 매개 변수가 지정되지 않은 경우 버전 지정된 버킷에 있는 개체의 최신 버전에서 모든 태그가 삭제됩니다. 객체의 현재 버전이 삭제 표식이면 x-amz-delete-marker 응답 헤더가 true로 설정된 상태로 "MethodNotAllowed" 상태가 반환됩니다.



 a| 
객체 가져오기
 a| 
xref:get-object.adoc[객체 가져오기]



 a| 
객체 ACL을 가져옵니다
 a| 
계정에 필요한 액세스 자격 증명이 제공된 경우 이 작업은 개체 소유자의 ID, DisplayName 및 사용 권한과 함께 긍정적인 응답을 반환합니다. 이는 소유자가 개체에 대한 모든 액세스 권한을 가지고 있음을 나타냅니다.



 a| 
객체 법적 증거 자료 보관
 a| 
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다]



 a| 
개체 보존 가져오기
 a| 
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다]



 a| 
객체 태그 지정 가져오기
 a| 
"태그 지정" 하위 리소스를 사용하여 개체에 대한 모든 태그를 반환합니다. 모든 Amazon S3 REST API 동작으로 구현됩니다

* 버전 관리 *

요청에 rionId 쿼리 매개 변수가 지정되지 않은 경우 이 작업은 최신 버전의 개체에서 버전 관리되는 버킷으로 모든 태그를 반환합니다. 객체의 현재 버전이 삭제 표식이면 x-amz-delete-marker 응답 헤더가 true로 설정된 상태로 "MethodNotAllowed" 상태가 반환됩니다.



 a| 
헤드 개체
 a| 
xref:head-object.adoc[헤드 개체]



 a| 
사후 개체 복원
 a| 
xref:post-object-restore.adoc[사후 개체 복원]



 a| 
개체 를 넣습니다
 a| 
xref:put-object.adoc[개체 를 넣습니다]



 a| 
개체 - 복사 를 선택합니다
 a| 
xref:put-object-copy.adoc[개체 - 복사 를 선택합니다]



 a| 
개체를 법적 증거 자료 보관
 a| 
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다]



 a| 
개체 보존
 a| 
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다]



 a| 
개체 태그 지정
 a| 
태그 지정 하위 리소스를 사용하여 기존 개체에 태그 집합을 추가합니다. 모든 Amazon S3 REST API 동작으로 구현됩니다

* 개체 태그 제한 *

새 개체를 업로드할 때 태그를 추가하거나 기존 개체에 태그를 추가할 수 있습니다. StorageGRID 및 Amazon S3 모두 각 오브젝트에 대해 최대 10개의 태그를 지원합니다. 개체와 관련된 태그에는 고유한 태그 키가 있어야 합니다. 태그 키의 길이는 최대 128자의 유니코드 문자이고 태그 값의 길이는 최대 256자의 유니코드 문자일 수 있습니다. 키와 값은 대/소문자를 구분합니다.

* 태그 업데이트 및 수집 동작 *

오브젝트 태그 지정을 사용하여 개체의 태그를 업데이트하는 경우 StorageGRID에서는 개체를 다시 수집하지 않습니다. 즉, 일치하는 ILM 규칙에 지정된 Ingest 동작 옵션이 사용되지 않습니다. ILM이 정상적인 백그라운드 ILM 프로세스에 의해 다시 평가될 때 업데이트로 인해 트리거되는 개체 배치에 대한 모든 변경 사항이 발생합니다.

즉, ILM 규칙이 수집 동작에 Strict 옵션을 사용하는 경우 필요한 개체 배치를 만들 수 없는 경우(예: 새로 필요한 위치를 사용할 수 없음) 작업이 수행되지 않습니다. 업데이트된 오브젝트는 필요한 배치가 가능할 때까지 현재 위치를 유지합니다.

* 충돌 해결 *

동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "Latest-WINS" 평가 시기는 S3 클라이언트가 작업을 시작할 때가 아니라 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 합니다.

* 버전 관리 *

요청에 rionId 쿼리 매개 변수가 지정되지 않은 경우 작업에서 버전 관리되는 버킷의 가장 최신 버전의 개체에 태그를 추가합니다. 객체의 현재 버전이 삭제 표식이면 x-amz-delete-marker 응답 헤더가 true로 설정된 상태로 "MethodNotAllowed" 상태가 반환됩니다.

|===
xref:s3-operations-tracked-in-audit-logs.adoc[S3 작업이 감사 로그에서 추적되었습니다]
