---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: S3 POST 오브젝트 복원 요청을 사용하여 클라우드 스토리지 풀에 저장된 오브젝트를 복원할 수 있습니다. 
---
= 사후 개체 복원
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 POST 오브젝트 복원 요청을 사용하여 클라우드 스토리지 풀에 저장된 오브젝트를 복원할 수 있습니다.



== 지원되는 요청 유형입니다

StorageGRID는 개체 복원을 위한 POST 개체 복원 요청만 지원합니다. 복원의 선택 유형을 지원하지 않습니다. SELECT 요청은 'XNotImplemented'를 반환합니다.



== 버전 관리

필요한 경우 rionId를 지정하여 버전이 있는 버킷에서 개체의 특정 버전을 복원합니다. rionId를 지정하지 않으면 객체의 최신 버전이 복원됩니다



== 클라우드 스토리지 풀 객체에 대한 POST 객체 복구의 동작

개체가 클라우드 스토리지 풀에 저장된 경우(정보 수명 주기 관리를 통해 개체 관리 지침 참조) POST 개체 복원 요청은 개체의 상태에 따라 다음과 같은 동작을 수행합니다. 자세한 내용은 " 헤드 개체 "를 참조하십시오.


NOTE: 객체가 클라우드 스토리지 풀에 저장되어 있고 하나 이상의 오브젝트 복제본도 그리드에 있는 경우 POST 객체 복원 요청을 실행하여 객체를 복원할 필요가 없습니다. 대신 Get Object 요청을 사용하여 로컬 복사본을 직접 검색할 수 있습니다.

|===
| 개체의 상태입니다 | POST 개체 복원 동작 


 a| 
StorageGRID로 수집되었지만 ILM에서 아직 평가되지 않은 오브젝트 또는 클라우드 스토리지 풀에 없는 오브젝트
 a| 
403 금지됨, InvalidObjectState



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
200 OK 어떤 변경도 없다.

* 참고 *: 객체가 검색 불가능한 상태로 전환되기 전에는 해당 '만료 날짜'를 변경할 수 없습니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었습니다
 a| 
'202 수락됨'은 요청 본문에 지정된 일 동안 검색할 수 있는 객체 복사본을 클라우드 스토리지 풀에 복원합니다. 이 기간이 끝나면 객체는 복구할 수 없는 상태로 돌아갑니다.

선택적으로 "계층" 요청 요소를 사용하여 복원 작업이 완료될 때까지 걸리는 시간("신속", "표준" 또는 "대량")을 결정합니다. '계층'을 지정하지 않으면 '표준' 계층이 사용됩니다.

* 주의 *: 오브젝트가 S3 Glacier Deep Archive로 전환되었거나 Cloud Storage Pool이 Azure Blob Storage를 사용하는 경우 "빠른" 계층을 사용하여 복원할 수 없습니다. 다음 오류는 403 사용 금지, InvalidTier로 반환됩니다. 검색 옵션은 이 저장소 클래스에서 지원되지 않습니다.



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
409갈등대, RestoreAlreadyInProgress



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
200OK

* 참고: * 개체가 검색 가능한 상태로 복원되면, POST 개체 복원 요청을 새 값으로 다시 발행하여 '만료 날짜'를 변경할 수 있습니다. 복원 날짜는 요청 시간을 기준으로 업데이트됩니다.

|===
xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:head-object.adoc[헤드 개체]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 작업이 감사 로그에서 추적되었습니다]
