---
permalink: s3/put-object-copy.html 
sidebar: sidebar 
keywords: object, add object, put, put object request 
summary: S3 PUT 오브젝트 복사 요청을 사용하여 S3에 이미 저장된 오브젝트 복사본을 생성할 수 있습니다. Put Object - Copy 작업은 GET 및 PUT를 수행하는 작업과 동일합니다. 
---
= 개체 - 복사 를 선택합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 PUT 오브젝트 복사 요청을 사용하여 S3에 이미 저장된 오브젝트 복사본을 생성할 수 있습니다. Put Object - Copy 작업은 GET 및 PUT를 수행하는 작업과 동일합니다.



== 충돌 해결

동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "Latest-WINS" 평가 시기는 S3 클라이언트가 작업을 시작할 때가 아니라 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 합니다.



== 개체 크기

단일 PUT 오브젝트 작업의 maximum_recommended_size는 5GiB(5,368,709,120바이트)입니다. 5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용합니다.


IMPORTANT: StorageGRID 11.6에서 단일 PUT 객체 작업에 대한 Maximum_supported_size는 5TiB(5,497,558,138,880바이트)입니다. 그러나 5GiB를 초과하는 개체를 업로드하려고 하면 * S3 PUT 오브젝트 크기가 너무 큼 * 경고가 트리거됩니다.



== 사용자 메타데이터의 UTF-8 문자

요청에 사용자 정의 메타데이터의 키 이름이나 값에 UTF-8 값이 포함되어 있으면 StorageGRID 동작이 정의되지 않습니다.

StorageGRID는 사용자 정의 메타데이터의 키 이름이나 값에 포함된 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 이스케이프된 UTF-8 문자는 ASCII 문자로 처리됩니다.

* 사용자 정의 메타데이터에 이스케이프된 UTF-8 문자가 포함된 경우 요청이 성공합니다.
* StorageGRID는 키 이름 또는 값의 해석된 값에 인쇄할 수 없는 문자가 포함된 경우 "x-amz-missing-meta" 헤더를 반환하지 않습니다.




== 지원되는 요청 헤더입니다

지원되는 요청 헤더는 다음과 같습니다.

* 콘텐츠 유형
* X-amz-copy 소스
* X-amz-copy-source-if-match
* X-amz-copy-source-if-none-match
* X-amz-copy-source-if-수정되지 않음-since
* X-amz-copy-source-if-modified-since
* x-amz-meta- 뒤에 사용자 정의 메타데이터를 포함하는 이름-값 쌍이 있습니다
* 'x-amz-metadata-directive': 기본값은 'copy'로, 객체와 관련 메타데이터를 복사할 수 있습니다.
+
오브젝트를 복사할 때 기존 메타데이터를 덮어쓰거나 오브젝트 메타데이터를 업데이트하도록 "replace"를 지정할 수 있습니다.

* X-amz-스토리지 클래스
* 'x-amz-tagging-directive': 기본값은 'copy'로, 객체와 모든 태그를 복사할 수 있습니다.
+
개체를 복사할 때 기존 태그를 덮어쓰거나 태그를 업데이트하려면 "다시 배치"를 지정할 수 있습니다.

* S3 오브젝트 잠금 요청 헤더:
+
** 'X-amz-object-lock-mode
** 'X-amz-object-lock-retain-until-date'
** X-amz-object-lock-legal-hold
+
이러한 헤더 없이 요청이 이루어지면 버킷 기본 보존 설정을 사용하여 개체 버전 보존 기간을 계산합니다.

+
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다]



* SSE 요청 헤더:
+
** ''x-amz-copy-sourcestevids-server-sideencryptionsever-customer-algorithm''입니다
** X-amz-copy-sources.\xserver-side-encryption-customer-key
** ''X-amz-copy-sourcestifs-server-side-encryption-customer-key-md5'
** 'X-amz-서버측-암호화'
** X-amz-서버측-암호화-고객-키-MD5
** 'X-amz-서버측-암호화-고객-키'
** 'X-amz-서버측-암호화-고객-알고리즘'
+
을 참조하십시오 <<Request headers for server-side encryption>>







== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않습니다.

* 캐시-컨트롤
* 'Content-Disposition'
* 콘텐츠 인코딩
* 컨텐츠-언어
* '만료'
* X-amz-웹사이트-리디렉션-위치




== 스토리지 클래스 옵션

"x-amz-storage-class" 요청 헤더가 지원되며 일치하는 ILM 규칙에서 이중 커밋 또는 밸런스의 수집 동작을 지정하는 경우 StorageGRID에서 생성되는 개체 복사본 수에 영향을 줍니다.

* '표준'입니다
+
(기본값) ILM 규칙이 이중 커밋 옵션을 사용하거나 균형 옵션이 중간 복사본 생성으로 돌아올 때 이중 커밋 수집 작업을 지정합니다.

* Reduced_redundancy를 선택합니다
+
ILM 규칙이 이중 커밋 옵션을 사용하거나 균형 옵션이 중간 복사본 생성으로 돌아올 때 단일 커밋 수집 작업을 지정합니다.

+

NOTE: S3 오브젝트 잠금이 활성화된 버킷으로 오브젝트를 인스팅하는 경우 REDED_REPREADITORY' 옵션이 무시됩니다. 개체를 레거시 준수 버킷으로 인스팅하는 경우 REDED_REPREADITORIAL' 옵션은 오류를 반환합니다. StorageGRID은 규정 준수 요구 사항이 충족될 수 있도록 항상 이중 커밋 수집을 수행합니다.





== Put Object - Copy에서 x-amz-copy-source 사용

x-amz-copy-source 헤더에 지정된 소스 버킷과 키가 대상 버킷 및 키와 다른 경우 소스 객체 데이터의 복제본이 대상에 기록됩니다.

소스와 대상이 일치하고 "x-amz-metadata-directive" 헤더가 replace"로 지정된 경우 해당 요청의 메타데이터 값으로 오브젝트의 메타데이터가 업데이트됩니다. 이 경우 StorageGRID는 오브젝트를 다시 수집하지 않습니다. 여기에는 두 가지 중요한 결과가 있습니다.

* Put Object-Copy를 사용하여 기존 개체를 현재 위치에서 암호화하거나 기존 개체의 암호화를 변경할 수 없습니다. X-amz-서버측-암호화 헤더나 x-amz-서버측-암호화-고객-알고리즘 헤더를 제공하면 StorageGRID는 요청을 거부하고 XNotImplemented를 반환합니다.
* 일치하는 ILM 규칙에 지정된 Ingest 동작 옵션은 사용되지 않습니다. ILM이 정상적인 백그라운드 ILM 프로세스에 의해 다시 평가될 때 업데이트로 인해 트리거되는 개체 배치에 대한 모든 변경 사항이 발생합니다.
+
즉, ILM 규칙이 수집 동작에 Strict 옵션을 사용하는 경우 필요한 개체 배치를 만들 수 없는 경우(예: 새로 필요한 위치를 사용할 수 없음) 작업이 수행되지 않습니다. 업데이트된 오브젝트는 필요한 배치가 가능할 때까지 현재 위치를 유지합니다.





== 서버측 암호화에 대한 요청 헤더

서버 측 암호화를 사용하는 경우 소스 개체가 암호화되었는지 여부 및 대상 개체를 암호화할 계획인지에 따라 요청 헤더가 제공됩니다.

* 소스 객체가 SSE-C(customer-provided key)를 사용하여 암호화된 경우, 객체를 해독한 다음 복사할 수 있도록 객체 복사 요청(Put Object-Copy request)에 다음 세 개의 헤더를 포함해야 합니다.
+
** X-amz-copy-sourcesources. ever-sideboretationsencryptionsever-customer-algorithm은 AES256을 지정합니다.
** 'x-amz-copy-sourcesources.x.server-side-encryption-customer-key'는 소스 객체를 만들 때 제공한 암호화 키를 지정합니다.
** ''x-amz-copy-sourcesourcesifx-server-side-encryption-customer-key-md5': 소스 개체를 만들 때 제공한 MD5 다이제스트를 지정합니다.


* 제공 및 관리하는 고유 키를 사용하여 대상 개체(복사본)를 암호화하려면 다음 세 개의 머리글을 포함합니다.
+
** X-amz-서버측-암호화-고객-알고리즘: AES256 지정.
** 'X-amz-서버측-암호화-고객-키': 대상 객체에 대한 새 암호화 키를 지정합니다.
** X-amz-서버측-암호화-고객-키-MD5: 새 암호화 키의 MD5 다이제스트를 지정합니다.




* 주의: * 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.

* SSE(StorageGRID)에서 관리되는 고유 키로 대상 객체(사본)를 암호화하려면 객체 복사 요청(Put Object-Copy request)에 이 헤더를 포함시킵니다.
+
** 'X-amz-서버측-암호화'




참고: * 오브젝트의 '서버측 암호화' 값은 업데이트할 수 없습니다. 대신 X-amz-metadata-directive:replace를 사용하여 새로운 서버 측 암호화 값으로 복사본을 만듭니다.



== 버전 관리

소스 버킷의 버전이 있는 경우 "x-amz-copy-source" 헤더를 사용하여 객체의 최신 버전을 복사할 수 있습니다. 개체의 특정 버전을 복사하려면 rionId 하위 리소스를 사용하여 복사할 버전을 명시적으로 지정해야 합니다. 목적지 버킷의 버전 관리가 되면 생성된 버전은 'x-amz-version-id' 응답 헤더로 반환됩니다. 대상 버킷의 버전 관리가 일시 중단된 경우 x-amz-version-id는 "null" 값을 반환합니다.

xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:using-server-side-encryption.adoc[서버측 암호화를 사용합니다]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 작업이 감사 로그에서 추적되었습니다]

xref:put-object.adoc[개체 를 넣습니다]
