---
permalink: s3/put-object.html 
sidebar: sidebar 
keywords: object, add object, put, put object request 
summary: S3 PUT 오브젝트 요청을 사용하여 오브젝트를 버킷에 추가할 수 있습니다. 
---
= 개체 를 넣습니다
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 PUT 오브젝트 요청을 사용하여 오브젝트를 버킷에 추가할 수 있습니다.



== 충돌 해결

동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "Latest-WINS" 평가 시기는 S3 클라이언트가 작업을 시작할 때가 아니라 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 합니다.



== 개체 크기

단일 PUT 오브젝트 작업의 maximum_recommended_size는 5GiB(5,368,709,120바이트)입니다. 5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용합니다.


IMPORTANT: StorageGRID 11.6에서 단일 PUT 객체 작업에 대한 Maximum_supported_size는 5TiB(5,497,558,138,880바이트)입니다. 그러나 5GiB를 초과하는 개체를 업로드하려고 하면 * S3 PUT 오브젝트 크기가 너무 큼 * 경고가 트리거됩니다.



== 사용자 메타데이터 크기입니다

Amazon S3는 각 PUT 요청 헤더 내의 사용자 정의 메타데이터 크기를 2KB로 제한합니다. StorageGRID는 사용자 메타데이터를 24KiB로 제한합니다. 사용자 정의 메타데이터의 크기는 각 키와 값의 UTF-8 인코딩에서 바이트 수의 합계를 구하여 측정됩니다.



== 사용자 메타데이터의 UTF-8 문자

요청에 사용자 정의 메타데이터의 키 이름이나 값에 UTF-8 값이 포함되어 있으면 StorageGRID 동작이 정의되지 않습니다.

StorageGRID는 사용자 정의 메타데이터의 키 이름이나 값에 포함된 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 이스케이프된 UTF-8 문자는 ASCII 문자로 처리됩니다.

* 사용자 정의 메타데이터에 이스케이프된 UTF-8 문자가 포함된 경우 Put, Put Object-Copy, Get 및 head 요청이 성공합니다.
* StorageGRID는 키 이름 또는 값의 해석된 값에 인쇄할 수 없는 문자가 포함된 경우 "x-amz-missing-meta" 헤더를 반환하지 않습니다.




== 개체 태그 제한

새 개체를 업로드할 때 태그를 추가하거나 기존 개체에 태그를 추가할 수 있습니다. StorageGRID 및 Amazon S3 모두 각 오브젝트에 대해 최대 10개의 태그를 지원합니다. 개체와 관련된 태그에는 고유한 태그 키가 있어야 합니다. 태그 키의 길이는 최대 128자의 유니코드 문자이고 태그 값의 길이는 최대 256자의 유니코드 문자일 수 있습니다. 키와 값은 대/소문자를 구분합니다.



== 개체 소유권

StorageGRID에서는 소유자가 아닌 계정 또는 익명 사용자가 만든 개체를 포함하여 모든 개체가 버킷 소유자 계정에 의해 소유됩니다.



== 지원되는 요청 헤더입니다

지원되는 요청 헤더는 다음과 같습니다.

* 캐시-컨트롤
* 'Content-Disposition'
* 콘텐츠 인코딩
+
Content-Encoding의 torageGRID에 대해 AWS-chunched를 지정하면 다음 항목을 확인할 수 없습니다.

+
** StorageGRID는 청크 데이터에 대해 청크 서명을 확인하지 않습니다.
** StorageGRID는 오브젝트에 대해 사용자가 "x-amz-decoded-content-length"를 제공하는 값을 확인하지 않습니다.


* 컨텐츠-언어
* 콘텐츠 길이
* 내용-MD5
* 콘텐츠 유형
* '만료'
* 전송 인코딩
+
AWS-chunched 페이로드 서명도 사용되는 경우 청크된 전송 인코딩이 지원됩니다.

* x-amz-meta- 뒤에 사용자 정의 메타데이터를 포함하는 이름-값 쌍이 있습니다.
+
사용자 정의 메타데이터에 대한 이름 값 쌍을 지정할 때 다음 일반 형식을 사용합니다.

+
[listing, subs="specialcharacters,quotes"]
----
x-amz-meta-_name_: _value_
----
+
ILM 규칙의 참조 시간으로 * 사용자 정의 작성 시간 * 옵션을 사용하려면 객체를 만들 때 기록하는 메타데이터의 이름으로 "creation-time"을 사용해야 합니다. 예를 들면 다음과 같습니다.

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
창조시간 값은 1970년 1월 1일 이후 초 단위로 평가된다.

+

NOTE: ILM 규칙은 참조 시간에 * 사용자 정의 작성 시간 * 과 수집 동작에 대한 균형 또는 엄격 옵션을 모두 사용할 수 없습니다. ILM 규칙을 만들면 오류가 반환됩니다.

* X-amz-태깅
* S3 오브젝트 잠금 요청 헤더
+
** 'X-amz-object-lock-mode
** 'X-amz-object-lock-retain-until-date'
** X-amz-object-lock-legal-hold
+
이러한 헤더 없이 요청이 이루어지면 버킷 기본 보존 설정을 사용하여 개체 버전 보존 기간을 계산합니다.

+
xref:using-s3-object-lock.adoc[S3 오브젝트 잠금을 사용합니다]



* SSE 요청 헤더:
+
** 'X-amz-서버측-암호화'
** X-amz-서버측-암호화-고객-키-MD5
** 'X-amz-서버측-암호화-고객-키'
** 'X-amz-서버측-암호화-고객-알고리즘'
+
을 참조하십시오 <<Request headers for server-side encryption>>







== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않습니다.

* X-amz-ACL 요청 헤더는 지원되지 않습니다.
* X-amz-website-redirect-location 요청 헤더는 지원되지 않으며 XNotImplemented를 반환합니다.




== 스토리지 클래스 옵션

X-amz-STERAGE-CLASS 요청 헤더는 지원된다. 'x-amz-storage-class'에 대해 제출된 가치는 수집 중에 StorageGRID가 오브젝트 데이터를 보호하는 방식에 영향을 주며, ILM에 의해 결정되는 StorageGRID 시스템에 저장된 개체의 영구 복사본의 수가 아닙니다.

수집된 개체와 일치하는 ILM 규칙이 Ingest 동작에 Strict 옵션을 사용하는 경우 "x-amz-storage-class" 헤더는 영향을 주지 않습니다.

X-amz-storage-class에 사용할 수 있는 값은 다음과 같다.

* '표준'(기본값)
+
** * 이중 커밋 *: ILM 규칙이 Ingest 동작에 대한 이중 커밋 옵션을 지정하는 경우, 개체가 수집되는 즉시 해당 개체의 두 번째 복사본이 생성되어 다른 스토리지 노드(이중 커밋)에 배포됩니다. ILM을 평가할 때 StorageGRID는 이러한 초기 중간 복사본이 규칙의 배치 지침을 충족하는지 여부를 결정합니다. 그렇지 않으면 새 오브젝트 복사본을 다른 위치에 만들어야 하고 초기 중간 복사본을 삭제해야 할 수 있습니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하고 StorageGRID이 규칙에 지정된 모든 복사본을 즉시 만들 수 없는 경우 StorageGRID은 다른 스토리지 노드에 두 개의 임시 복사본을 만듭니다.
+
StorageGRID에서 ILM 규칙(동기 배치)에 지정된 모든 오브젝트 복사본을 즉시 생성할 수 있으면 'x-amz-storage-class' 헤더가 효과가 없습니다.



* Reduced_redundancy를 선택합니다
+
** * 이중 커밋 *: ILM 규칙이 Ingest 동작에 대한 이중 커밋 옵션을 지정하는 경우 StorageGRID는 오브젝트가 수집될 때(단일 커밋) 단일 임시 복사본을 만듭니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하는 경우 StorageGRID은 시스템에서 규칙에 지정된 모든 사본을 즉시 만들 수 없는 경우에만 단일 중간 복사본을 만듭니다. StorageGRID에서 동기 배치를 수행할 수 있는 경우 이 머리글은 영향을 주지 않습니다. Reduced_redundancy 옵션은 개체와 일치하는 ILM 규칙이 복제된 단일 복사본을 만들 때 가장 적합합니다. 이 경우 'REDED_READITORY'를 사용하면 모든 수집 작업에 대해 불필요한 오브젝트 복사본을 생성하고 삭제할 필요가 없습니다.


+
다른 상황에서는 reducted_redundancy 옵션을 사용하지 않는 것이 좋습니다. REDED_READITAINEY는 수집 중에 오브젝트 데이터가 손실될 위험을 증가시킵니다. 예를 들어, ILM 평가가 발생하기 전에 실패한 스토리지 노드에 단일 복사본이 처음 저장되는 경우 데이터가 손실될 수 있습니다.



* 주의 *: 한 번에 하나의 복제 사본만 있으면 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.

reducted_redundancy를 지정하면 개체를 처음 인제스트할 때 생성되는 복제본 수만 영향을 받습니다. 활성 ILM 정책에 따라 개체를 평가할 때 개체의 복사본 수에 영향을 주지 않으며 StorageGRID 시스템에서 낮은 수준의 중복성에 데이터가 저장되지 않습니다.

* 참고 *: S3 오브젝트 잠금이 활성화된 버킷으로 오브젝트를 인스팅하는 경우, reducted_redundancy 옵션이 무시됩니다. 개체를 레거시 준수 버킷으로 인스팅하는 경우 REDED_REPREADITORIAL' 옵션은 오류를 반환합니다. StorageGRID은 규정 준수 요구 사항이 충족될 수 있도록 항상 이중 커밋 수집을 수행합니다.



== 서버측 암호화에 대한 요청 헤더

다음 요청 헤더를 사용하여 서버측 암호화를 사용하여 개체를 암호화할 수 있습니다. SSE 및 SSE-C 옵션은 상호 배타적입니다.

* * SSE *: StorageGRID에서 관리하는 고유 키를 사용하여 오브젝트를 암호화하려면 다음 헤더를 사용하십시오.
+
** 'X-amz-서버측-암호화'


* * SSE-C *: 사용자가 제공 및 관리하는 고유 키로 객체를 암호화하려면 이 헤더 세 개를 모두 사용합니다.
+
** X-amz-서버측-암호화-고객-알고리즘: AES256 지정.
** 'X-amz-서버측-암호화-고객 키': 새 오브젝트의 암호화 키를 지정합니다.
** X-amz-서버측-암호화-고객-키-MD5: 새 개체의 암호화 키에 대해 MD5 다이제스트를 지정합니다.




* 주의: * 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 오브젝트 데이터를 보호하기 전에 "'서버측 암호화 사용'의 고려 사항을 검토하십시오.

* 참고: * 개체가 SSE 또는 SSE-C로 암호화된 경우 버킷 수준 또는 그리드 수준 암호화 설정은 무시됩니다.



== 버전 관리

버켓에 대한 버전 관리가 활성화된 경우 저장할 개체의 버전에 대해 고유한 rionId가 자동으로 생성됩니다. 이 인상파 ID는 X-amz-version-id 응답 헤더를 사용하여 응답에서도 반환됩니다.

버전 관리가 일시 중단된 경우 개체 버전은 null rionId로 저장되며, null 버전이 이미 있는 경우에는 덮어쓰게 됩니다.

xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:operations-on-buckets.adoc[버킷 작업]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 작업이 감사 로그에서 추적되었습니다]

xref:using-server-side-encryption.adoc[서버측 암호화를 사용합니다]

xref:configuring-tenant-accounts-and-connections.adoc[클라이언트 연결 구성 방법]
