---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords: s3 rest api supported operations, s3 rest api limitations 
summary: 'StorageGRID 시스템은 대부분의 작업을 지원하고 몇 가지 제한 사항이 있는 간단한 스토리지 서비스 API(API 버전 2006-03-01)를 구현합니다. S3 REST API 클라이언트 애플리케이션을 통합할 때 구현 세부 정보를 이해해야 합니다.' 
---
= S3 REST API에서 지원되는 작업 및 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템은 대부분의 작업을 지원하고 몇 가지 제한 사항이 있는 간단한 스토리지 서비스 API(API 버전 2006-03-01)를 구현합니다. S3 REST API 클라이언트 애플리케이션을 통합할 때 구현 세부 정보를 이해해야 합니다.

StorageGRID 시스템은 가상 호스팅 방식의 요청과 경로 스타일 요청을 모두 지원합니다.



== 날짜 처리

S3 REST API의 StorageGRID 구현은 유효한 HTTP 날짜 형식만 지원합니다.

StorageGRID 시스템은 날짜 값을 허용하는 모든 헤더에 대해 유효한 HTTP 날짜 형식만 지원합니다. 날짜의 시간 부분은 그리니치 표준시(GMT) 형식 또는 표준 시간대 오프셋 없이 UTC(국제 표준시) 형식으로 지정할 수 있습니다(+0000을 지정해야 함). 요청에 "x-amz-date" 헤더를 포함하면 날짜 요청 헤더에 지정된 모든 값이 무시됩니다. AWS 서명 버전 4를 사용할 때는 날짜 헤더가 지원되지 않으므로 서명된 요청에 "x-amz-date" 헤더가 있어야 합니다.



== 공통 요청 헤더

StorageGRID 시스템은 에 의해 정의된 공통 요청 헤더를 지원합니다 http://["AWS(Amazon Web Services) 문서: Amazon Simple Storage Service API Reference 를 참조하십시오"^]한 가지 예외가 있습니다.

|===
| 요청 헤더 | 구축 


 a| 
권한 부여
 a| 
AWS Signature 버전 2에 대한 전체 지원

다음 경우를 제외하고 AWS Signature 버전 4 지원:

* 요청 본문에 대한 SHA256 값이 계산되지 않습니다. 사용자가 제출한 값은 X-amz-content-SHA256 헤더용으로 'unsigned-payload' 값이 제공된 것처럼 유효성 검사 없이 허용됩니다.




 a| 
X-amz-security-token
 a| 
구현되지 않았습니다. 'XNotImplemented'를 반환합니다.

|===


== 공통 응답 헤더

StorageGRID 시스템은 한 가지 예외를 제외하고 _Simple Storage Service API Reference_에 의해 정의된 모든 공통 응답 헤더를 지원합니다.

|===
| 응답 헤더 | 구축 


 a| 
X-amz-id-2
 a| 
사용 안 합니다

|===