---
permalink: s3/using-s3-object-lock.html 
sidebar: sidebar 
keywords: using S3 object lock, object lock, S3 object 
summary: StorageGRID 시스템에서 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 S3 오브젝트 잠금이 설정된 버킷을 생성한 다음 해당 버켓에 추가하는 각 오브젝트 버전에 대한 보관 기한 및 법적 보류 설정을 지정할 수 있습니다. 
---
= S3 오브젝트 잠금을 사용합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템에서 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 S3 오브젝트 잠금이 설정된 버킷을 생성한 다음 각 버킷의 기본 보존 기간 또는 해당 버킷에 추가한 각 오브젝트 버전에 대한 특정 보관 기간 및 법적 증거 보관 설정을 지정할 수 있습니다.

S3 오브젝트 잠금을 사용하면 고정된 시간 또는 무기한으로 오브젝트를 삭제 또는 덮어쓰는 것을 방지하기 위해 오브젝트 레벨 설정을 지정할 수 있습니다.

StorageGRID S3 오브젝트 잠금 기능은 Amazon S3 규정 준수 모드에 상응하는 단일 보존 모드를 제공합니다. 기본적으로 보호된 개체 버전은 사용자가 덮어쓰거나 삭제할 수 없습니다. StorageGRID S3 오브젝트 잠금 기능은 거버넌스 모드를 지원하지 않으며, 특별한 권한이 있는 사용자가 보존 설정을 무시하거나 보호된 오브젝트를 삭제할 수 없습니다.



== 버킷에 대해 S3 오브젝트 잠금을 설정합니다

StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 각 버킷을 생성할 때 선택적으로 S3 오브젝트 잠금을 활성화할 수 있습니다. 다음 방법 중 하나를 사용할 수 있습니다.

* 테넌트 관리자를 사용하여 버킷을 생성합니다.
+
xref:../tenant/index.adoc[테넌트 계정을 사용합니다]

* X-amz-bucket-object-lock-enabled 요청 헤더로 PUT Bucket 요청을 이용하여 bucket을 생성한다.
+
xref:operations-on-buckets.adoc[버킷 작업]



버킷이 생성된 후에는 S3 오브젝트 잠금을 추가하거나 비활성화할 수 없습니다. S3 오브젝트 잠금에는 버킷 버전 관리가 필요하며, 이 버전은 버킷을 생성할 때 자동으로 활성화됩니다.

S3 오브젝트 잠금이 활성화된 버킷에는 S3 오브젝트 잠금 설정이 있는 오브젝트와 없는 오브젝트의 조합이 포함될 수 있습니다. StorageGRID는 S3 오브젝트 잠금 버킷의 오브젝트에 대한 기본 보존 기간을 지원하며 오브젝트 잠금 구성 버킷 작업을 지원합니다. '3:object-lock-remaining-days' 정책 조건 키는 객체에 대해 허용되는 최소 및 최대 보존 기간을 설정합니다.



== 버킷에 S3 오브젝트 잠금이 설정되었는지 확인

S3 오브젝트 잠금이 활성화되어 있는지 확인하려면 를 사용합니다 xref:../s3/use-s3-object-lock-default-bucket-retention.adoc#get-object-lock-configuration[개체 잠금 구성을 가져옵니다] 요청하십시오.



== S3 오브젝트 잠금 설정으로 오브젝트를 생성합니다

S3 오브젝트 잠금이 활성화된 버킷에 오브젝트 버전을 추가할 때 S3 오브젝트 잠금 설정을 지정하려면 오브젝트 넣기, 오브젝트 복사 넣기 또는 다중 파트 업로드 요청을 시작합니다. 다음 요청 헤더를 사용하십시오.


NOTE: 버킷을 생성할 때 S3 오브젝트 잠금을 활성화해야 합니다. 버킷을 생성한 후에는 S3 오브젝트 잠금을 추가하거나 비활성화할 수 없습니다.

* 'x-amz-object-lock-mode'로, 반드시 준수(대소문자 구분)되어야 합니다.
+

NOTE: x-amz-object-lock-mode를 지정할 경우 x-amz-object-lock-retain-until-date를 지정해야 합니다.

* 'X-amz-object-lock-retain-until-date'
+
** 유지 종료 날짜 값은 2020-08-10T21:46:00Z 형식이어야 합니다. 소수 자릿수는 허용되지만 소수점 이하 자릿수는 3자리만 유지됩니다(밀리초 단위). 다른 ISO 8601 형식은 허용되지 않습니다.
** 보존 종료 날짜는 미래여야 합니다.


* X-amz-object-lock-legal-hold
+
법적 증거 자료 보관(대소문자 구분)이 켜져 있는 경우, 해당 물체는 법적 증거 자료 보관 하에 배치됩니다. 법적 증거 자료 보관 기능이 꺼져 있는 경우 법적 증거 자료 보관 작업이 없습니다. 다른 값을 사용하면 400개의 잘못된 요청(InvalidArgument) 오류가 발생합니다.



이러한 요청 헤더를 사용하는 경우 다음과 같은 제한 사항에 유의하십시오.

* "x-amz-object-lock- *" 요청 헤더가 Put Object 요청에 있는 경우 Content-MD5" 요청 헤더가 필요합니다. 개체 복사 또는 멀티파트 업로드를 시작하려면 Content-MD5가 필요하지 않습니다.
* 버킷에 S3 오브젝트 잠금이 활성화되어 있지 않고 "x-amz-object-lock- *" 요청 헤더가 있는 경우 400개의 잘못된 요청(InvalidRequest) 오류가 반환됩니다.
* Put Object 요청은 AWS 동작에 맞춰 "x-amz-storage-class:reduced_redundancy"를 사용할 수 있도록 지원합니다. 하지만 오브젝트가 S3 오브젝트 잠금이 설정된 버킷으로 수집되면 StorageGRID는 항상 이중 커밋 수집을 수행합니다.
* 이후 GET 또는 HEAD 객체 버전 응답에는 헤더 "x-amz-OBJECT-LOCK-MODE", "x-amz-OBJECT-REGATE-DATE" 및 "x-amz-OBJECT-LOCK-REGAL-HOLD"가 포함되며, 구성된 경우 요청 송신자가 올바른 '3:GET *' 권한을 가지고 있는 경우 이에 해당합니다.
* 이후 개체 버전 삭제 또는 개체 버전 삭제 요청은 보존 기한 이전이거나 법적 보류가 켜져 있는 경우 실패합니다.




== S3 오브젝트 잠금 설정을 업데이트합니다

기존 개체 버전에 대한 법적 증거 자료 보관 또는 보존 설정을 업데이트해야 하는 경우 다음 개체 하위 리소스 작업을 수행할 수 있습니다.

* '개체 법적 증거 자료 보관'
+
새 법적 증거 자료 보관 값이 켜져 있으면 해당 개체는 법적 증거 자료 보관 아래에 배치됩니다. 법적 증거 자료 보관 가치가 없는 경우 법적 구속이 해제됩니다.

* '개체 보존'을 선택합니다
+
** 모드 값은 규정 준수(대/소문자 구분)여야 합니다.
** 유지 종료 날짜 값은 2020-08-10T21:46:00Z 형식이어야 합니다. 소수 자릿수는 허용되지만 소수점 이하 자릿수는 3자리만 유지됩니다(밀리초 단위). 다른 ISO 8601 형식은 허용되지 않습니다.
** 개체 버전에 기존 보존 기한이 있는 경우 개체 버전을 늘릴 수만 있습니다. 새 값은 미래여야 합니다.




xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다]

xref:../tenant/index.adoc[테넌트 계정을 사용합니다]

xref:put-object.adoc[개체 를 넣습니다]

xref:put-object-copy.adoc[개체 - 복사 를 선택합니다]

xref:initiate-multipart-upload.adoc[멀티파트 업로드를 시작합니다]

xref:object-versioning.adoc[오브젝트 버전 관리]

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html["Amazon Simple Storage Service 사용자 가이드: S3 Object Lock 사용"^]
