---
permalink: monitor/commonly-used-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, Prometheus metrics, metrics 
summary: 관리 노드의 Prometheus 서비스는 모든 노드의 서비스에서 시계열 메트릭을 수집합니다. Prometheus는 1,000개 이상의 메트릭을 수집하지만 가장 중요한 StorageGRID 작업을 모니터링하려면 상대적으로 적은 수의 수치가 필요합니다. 
---
= 일반적으로 사용되는 Prometheus 메트릭입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드의 Prometheus 서비스는 모든 노드의 서비스에서 시계열 메트릭을 수집합니다. Prometheus는 1,000개 이상의 메트릭을 수집하지만 가장 중요한 StorageGRID 작업을 모니터링하려면 상대적으로 적은 수의 수치가 필요합니다.

메트릭은 Prometheus 데이터에 예약된 공간이 가득 찰 때까지 각 관리 노드에 저장됩니다. '/var/local/mysql_ibdata/' 볼륨이 용량에 도달하면 가장 오래된 메트릭이 먼저 삭제됩니다.

전체 메트릭 목록을 얻으려면 Grid Management API를 사용하십시오.

. Grid Manager 상단에서 도움말 아이콘을 선택하고 * API Documentation * 을 선택합니다.
. 메트릭 * 작업을 찾습니다.
. Get/Grid/metric-names 동작을 수행한다.
. 결과를 다운로드합니다.


다음 표에는 가장 일반적으로 사용되는 Prometheus 메트릭이 나열되어 있습니다. 이 목록을 참조하여 기본 알림 규칙의 조건을 보다 잘 이해하거나 사용자 지정 알림 규칙의 조건을 구성할 수 있습니다.


NOTE: 이름에 _private_이 포함된 메트릭은 내부 전용이며 StorageGRID 릴리스 간에 예고 없이 변경될 수 있습니다.

|===
| Prometheus 메트릭입니다 | 설명 


 a| 
alertmanager_notifications_failed_total
 a| 
실패한 총 경고 알림 수입니다.



 a| 
node_filesystem_AVAIL_bytes를 나타냅니다
 a| 
루트가 아닌 사용자가 사용할 수 있는 파일 시스템 공간의 크기(바이트)입니다.



 a| 
node_memory_MemAvailable_bytes입니다
 a| 
메모리 정보 필드 MemAvailable_Bytes



 a| 
node_network_carrier 를 선택합니다
 a| 
/sys/class/net/<iface>의 캐리어 값입니다.



 a| 
node_network_Receive_errs_total
 a| 
네트워크 장치 통계 Receive_errs입니다.



 a| 
node_network_transmit_errs_total
 a| 
네트워크 디바이스 통계 transmit_errs



 a| 
StorageGRID_관리_다운
 a| 
노드가 예상 이유로 그리드에 연결되어 있지 않습니다. 예를 들어, 노드의 노드 또는 서비스가 정상적으로 종료되었거나 노드가 재부팅 중이거나 소프트웨어가 업그레이드 중입니다.



 a| 
StorageGRID_appliance_compute_controller_hardware_status입니다
 a| 
어플라이언스에서 컴퓨팅 컨트롤러 하드웨어의 상태입니다.



 a| 
StorageGRID_appliance_failed_disks입니다
 a| 
어플라이언스의 스토리지 컨트롤러의 경우 최적화되지 않은 드라이브의 수입니다.



 a| 
StorageGRID_어플라이언스_스토리지_컨트롤러_하드웨어_상태입니다
 a| 
어플라이언스에 있는 스토리지 컨트롤러 하드웨어의 전체 상태입니다.



 a| 
StorageGRID_content_버킷 및_컨테이너
 a| 
이 스토리지 노드에서 알려진 S3 버킷 및 Swift 컨테이너의 총 수입니다.



 a| 
StorageGRID_content_objects
 a| 
이 스토리지 노드에서 알려진 S3 및 Swift 데이터 오브젝트의 총 수 Count는 S3 또는 Swift를 통해 시스템과 상호 작용하는 클라이언트 애플리케이션에서 생성한 데이터 오브젝트에만 유효합니다.



 a| 
StorageGRID_content_objects_lost
 a| 
이 서비스가 StorageGRID 시스템에서 누락된 것으로 감지한 총 오브젝트 수입니다. 손실 원인을 파악하고 복구가 가능한지 여부를 판단하기 위한 조치를 취해야 합니다.

xref:troubleshooting-lost-and-missing-object-data.adoc[분실하거나 누락된 오브젝트 데이터 문제를 해결합니다]



 a| 
StorageGRID_http_sessions_incoming_attempted입니다
 a| 
스토리지 노드에 대해 시도된 총 HTTP 세션 수입니다.



 a| 
StorageGRID_http_sessions_incoming_currently_설정됨
 a| 
스토리지 노드에서 현재 활성(열린) 상태의 HTTP 세션 수입니다.



 a| 
StorageGRID_http_sessions_incoming_failed 를 참조하십시오
 a| 
조작된 HTTP 요청 또는 작업 처리 중 오류로 인해 성공적으로 완료되지 못한 총 HTTP 세션 수입니다.



 a| 
StorageGRID_http_sessions_incoming_successful입니다
 a| 
성공적으로 완료된 총 HTTP 세션 수입니다.



 a| 
StorageGRID_ILM_waiting_background_objects
 a| 
이 노드의 총 개체 수가 스캔에서 ILM 평가를 대기 중입니다.



 a| 
StorageGRID_ILM_클라이언트_평가_개체_초당_대기 중
 a| 
이 노드의 ILM 정책에 따라 객체가 평가되는 현재 속도입니다.



 a| 
StorageGRID_ILM_클라이언트_개체 대기 중
 a| 
클라이언트 작업(예: 수집)에서 ILM 평가를 대기 중인 이 노드의 총 오브젝트 수



 a| 
StorageGRID_ILM_TOTAL_OBJECURS_TOTAL_OB
 a| 
ILM 평가를 대기 중인 총 개체 수입니다.



 a| 
StorageGRID_ILM_스캔_개체_초당_입니다
 a| 
이 노드가 소유한 오브젝트가 스캔되어 ILM을 위해 대기되는 속도입니다.



 a| 
StorageGRID_ILM_SCAN_PERIOD_Estimated_minutes입니다
 a| 
이 노드에서 전체 ILM 스캔을 완료하는 데 걸리는 예상 시간입니다.

* 참고: * 전체 스캔은 ILM이 이 노드가 소유한 모든 개체에 적용되었다고 보장하지 않습니다.



 a| 
StorageGRID_load_balancer_endpoint_cert_expiry_time
 a| 
epoch 이후 초 단위의 로드 밸런서 끝점 인증서 만료 시간.



 a| 
StorageGRID_metadata_query_average_latency_milliseconds
 a| 
이 서비스를 통해 메타데이터 저장소에 대해 쿼리를 실행하는 데 필요한 평균 시간입니다.



 a| 
StorageGRID_NETWORK_Received_Bytes를 나타냅니다
 a| 
설치 후 수신된 총 데이터 양입니다.



 a| 
StorageGRID_NETWORK_TAINED_BATED
 a| 
설치 후 전송된 총 데이터 양입니다.



 a| 
StorageGRID_노드_CPU_활용률_백분율
 a| 
이 서비스에서 현재 사용 중인 사용 가능한 CPU 시간의 백분율입니다. 서비스 사용 중인 상태를 나타냅니다. 사용 가능한 CPU 시간은 서버의 CPU 수에 따라 다릅니다.



 a| 
StorageGRID_NTP_선택됨_시간_소스_오프셋_밀리초
 a| 
선택한 시간 소스에서 제공하는 시간의 체계적 오프셋. 시간 소스에 도달하는 지연 시간이 시간 소스가 NTP 클라이언트에 도달하는 데 필요한 시간과 같지 않으면 오프셋이 발생합니다.



 a| 
StorageGRID_NTP_잠김
 a| 
노드가 네트워크 시간 프로토콜(NTP) 서버에 잠기지 않았습니다.



 a| 
StorageGRID_S3_데이터_전송_바이트_수집되었습니다
 a| 
속성이 마지막으로 재설정된 이후 S3 클라이언트에서 이 스토리지 노드로 수집된 총 데이터 양입니다.



 a| 
StorageGRID_S3_데이터_전송_바이트_검색됨
 a| 
속성이 마지막으로 재설정된 이후 이 스토리지 노드에서 S3 클라이언트가 검색한 총 데이터 양입니다.



 a| 
StorageGRID_S3_작업_에 실패했습니다
 a| 
S3 승인 실패로 인해 발생한 작업을 제외한 총 S3 작업 실패 횟수(HTTP 상태 코드 4xx 및 5xx).



 a| 
StorageGRID_S3_운영_성공
 a| 
성공한 S3 작업의 총 수(HTTP 상태 코드 2xx).



 a| 
StorageGRID_S3_운영_권한이 없습니다
 a| 
인증 실패로 인한 총 실패한 S3 작업 수.



 a| 
StorageGRID_servercertificate_management_interface_cert_expiry_days입니다
 a| 
관리 인터페이스 인증서가 만료되기 전의 일 수입니다.



 a| 
StorageGRID_servercertificate_storage_api_endpoints_cert_expiry_days를 지정합니다
 a| 
객체 스토리지 API 인증서가 만료되기 전의 일 수입니다.



 a| 
StorageGRID_SERVICE_CPU_초
 a| 
설치 후 이 서비스에서 CPU를 사용한 누적 시간입니다.



 a| 
StorageGRID_SERVICE_MEMORY_USAGE_Bytes
 a| 
이 서비스에서 현재 사용 중인 메모리(RAM)의 양입니다. 이 값은 Linux 상위 유틸리티가 RES로 표시하는 값과 동일합니다.



 a| 
StorageGRID_SERVICE_NETWORK_Received_Bytes를 나타냅니다
 a| 
설치 후 이 서비스에서 수신한 총 데이터 양입니다.



 a| 
StorageGRID_SERVICE_NETWORK_TAINED_BATED
 a| 
이 서비스에서 보낸 총 데이터 양입니다.



 a| 
StorageGRID_Service_Restarts
 a| 
서비스가 다시 시작된 총 횟수입니다.



 a| 
StorageGRID_SERVICE_RUNTIME_초
 a| 
설치 후 서비스가 실행된 총 시간입니다.



 a| 
StorageGRID_SERVICE_Uptime_초
 a| 
서비스가 마지막으로 다시 시작된 이후 실행된 총 시간입니다.



 a| 
StorageGRID_스토리지_상태_현재
 a| 
스토리지 서비스의 현재 상태입니다. 속성 값은 다음과 같습니다.

* 10 = 오프라인
* 15 = 유지 보수
* 20 = 읽기 전용
* 30 = 온라인




 a| 
StorageGRID_스토리지_상태입니다
 a| 
스토리지 서비스의 현재 상태입니다. 속성 값은 다음과 같습니다.

* 0 = 오류 없음
* 10 = 전환 중
* 20 = 사용 가능한 공간이 부족합니다
* 30 = 볼륨을 사용할 수 없습니다
* 40 = 오류




 a| 
StorageGRID_스토리지_활용률_바이트
 a| 
스토리지 노드에서 복제 및 삭제 코딩 오브젝트 데이터의 총 크기에 대한 추정치입니다.



 a| 
StorageGRID_스토리지_활용률_메타데이터_허용됨_바이트
 a| 
객체 메타데이터에 허용되는 각 스토리지 노드의 볼륨 0의 총 공간입니다. 이 값은 항상 노드의 메타데이터에 예약된 실제 공간보다 작습니다. 왜냐하면 예약된 공간의 일부는 필수 데이터베이스 작업(예: 컴팩션 및 복구) 및 향후 하드웨어 및 소프트웨어 업그레이드에 필요하기 때문입니다. 오브젝트 메타데이터에 허용되는 공간은 전체 오브젝트 용량을 제어합니다.



 a| 
StorageGRID_스토리지_활용률_메타데이터_바이트
 a| 
스토리지 볼륨 0의 오브젝트 메타데이터 크기(바이트)입니다.



 a| 
StorageGRID_스토리지_활용률_총_공간_바이트
 a| 
모든 오브젝트 저장소에 할당된 총 스토리지 공간입니다.



 a| 
StorageGRID_스토리지_활용률_가용_공간_바이트
 a| 
남은 총 오브젝트 스토리지 공간 크기입니다. 스토리지 노드의 모든 오브젝트 저장소에 사용할 수 있는 공간을 합산하여 계산합니다.



 a| 
StorageGRID_Swift_데이터_전송_바이트_수집되었습니다
 a| 
속성을 마지막으로 재설정한 이후 Swift 클라이언트에서 이 스토리지 노드로 수집된 총 데이터 양입니다.



 a| 
StorageGRID_SwiFT_DATA_transfers_bytes_검색됨
 a| 
속성이 마지막으로 재설정된 이후 이 스토리지 노드에서 Swift 클라이언트가 검색한 총 데이터 양입니다.



 a| 
StorageGRID_SwiFT_operations_failed 를 참조하십시오
 a| 
Swift 인증 실패에 의해 발생한 것을 제외한 Swift 작업의 총 실패 수(HTTP 상태 코드 4xx 및 5xx).



 a| 
StorageGRID_Swift_operations_successful입니다
 a| 
성공적인 Swift 작업의 총 수(HTTP 상태 코드 2xx).



 a| 
StorageGRID_SwiFT_operations_unauthorized를 지정합니다
 a| 
인증 실패로 인해 실패한 Swift 작업의 총 수(HTTP 상태 코드 401, 403, 405).



 a| 
StorageGRID_tenant_usage_data_bytes를 나타냅니다
 a| 
테넌트의 모든 객체의 논리적 크기입니다.



 a| 
StorageGRID_tenant_usage_object_count
 a| 
테넌트의 객체 수입니다.



 a| 
StorageGRID_tenant_usage_quota_bytes를 나타냅니다
 a| 
테넌트 객체에 사용할 수 있는 최대 논리 공간 크기입니다. 할당량 메트릭을 제공하지 않으면 무제한 공간을 사용할 수 있습니다.

|===