---
permalink: monitor/logs-for-third-party-software.html 
sidebar: sidebar 
keywords: troubleshooting, logs 
summary: 타사 소프트웨어 로그를 사용하여 문제를 해결할 수 있습니다. 
---
= 타사 소프트웨어에 대한 로그입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
타사 소프트웨어 로그를 사용하여 문제를 해결할 수 있습니다.

[cols="1a,2a,3a,1a"]
|===
| 범주 | 파일 이름입니다 | 참고 | 에 있습니다 


 a| 
아카이빙
| /var/local/log/dsierror.log 를 참조하십시오  a| 
TSM 클라이언트 API에 대한 오류 정보입니다.
 a| 
아카이브 노드



 a| 
MySQL
| /var/local/log/mysql.err/var/local/log/mysql-slow.log  a| 
MySQL에서 생성된 로그 파일.

mysql.err 파일은 데이터베이스 오류와 시작 및 종료 등의 이벤트를 캡처합니다.

mysql-slow.log 파일(slow query log)은 실행에 10초 이상 걸린 SQL 문을 캡처합니다.
 a| 
관리자 노드



 a| 
운영 체제
| /var/local/log/messages입니다  a| 
이 디렉토리에는 운영 체제에 대한 로그 파일이 포함되어 있습니다. 이러한 로그에 포함된 오류도 그리드 관리자에 표시됩니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 * Topology * > *_Site_ * > *_Node_ * > * SSM * > * Events * 를 선택합니다.
 a| 
모든 노드



 a| 
NTP
| /var/local/log/ntp.log /var/lib/ntp/var/log/ntpstats/  a| 
'/var/local/log/ntp.log'에는 NTP 오류 메시지에 대한 로그 파일이 포함되어 있습니다.

'/var/lib/ntp/var/log/ntpstats/' 디렉토리에는 NTP 타이밍 통계가 포함됩니다.

'loostats'는 루프 필터 통계 정보를 기록합니다.

피에르통계(peerstats)는 피어 통계 정보를 기록합니다.
 a| 
모든 노드



 a| 
삼바
| /var/local/log/samba/  a| 
Samba 로그 디렉토리에는 각 Samba 프로세스(SMB, NMB 및 winbind)와 모든 클라이언트 호스트 이름/IP에 대한 로그 파일이 포함됩니다.
 a| 
관리자 노드가 CIFS를 통해 감사 공유를 내보내도록 구성되었습니다

|===