---
permalink: monitor/logs-files-reference.html 
sidebar: sidebar 
keywords: log, logs, log files 
summary: StorageGRID는 이벤트, 진단 메시지 및 오류 상태를 캡처하는 데 사용되는 로그를 제공합니다. 문제 해결을 지원하기 위해 로그 파일을 수집하여 기술 지원 부서에 전달하라는 요청을 받을 수 있습니다. 
---
= 로그 파일 참조
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 이벤트, 진단 메시지 및 오류 상태를 캡처하는 데 사용되는 로그를 제공합니다. 문제 해결을 지원하기 위해 로그 파일을 수집하여 기술 지원 부서에 전달하라는 요청을 받을 수 있습니다.

로그는 다음과 같이 분류됩니다.

* xref:storagegrid-software-logs.adoc[StorageGRID 소프트웨어 로그]
* xref:deployment-and-maintenance-logs.adoc[배포 및 유지 관리 로그]
* xref:logs-for-third-party-software.adoc[타사 소프트웨어에 대한 로그입니다]
* xref:about-bycast-log.adoc[bycast.log 정보]



IMPORTANT: 각 로그 유형에 대해 제공되는 세부 정보는 참조용으로만 제공됩니다. 로그는 기술 지원 부서에서 제공하는 고급 문제 해결을 위한 것입니다. 감사 로그 및 응용 프로그램 로그 파일을 사용하여 문제 기록을 재구성하는 고급 기술은 이 지침의 범위를 벗어납니다.

로그에 액세스하려면 하나 이상의 노드에서 로그 파일 및 시스템 데이터를 단일 로그 파일 아카이브로 수집할 수 있습니다(* 지원 * > * 도구 * > * 로그 *). 또는 운영 관리 노드를 사용할 수 없거나 특정 노드에 연결할 수 없는 경우 다음과 같이 각 그리드 노드에 대한 개별 로그 파일에 액세스할 수 있습니다.

. ssh admin@grid_node_ip' 명령을 입력한다
. "passwords.txt" 파일에 나열된 암호를 입력합니다.
. 루트로 전환하려면 다음 명령을 입력합니다
. "passwords.txt" 파일에 나열된 암호를 입력합니다.


StorageGRID 로그 파일 아카이브에는 각 범주에 대해 설명된 로그와 메트릭 및 디버그 명령 출력이 포함된 추가 파일이 포함됩니다.

[cols="1a,3a"]
|===
| 보관 위치 | 설명 


| 감사  a| 
정상적인 시스템 작동 중에 생성된 감사 메시지입니다.



| 기본 OS 로그  a| 
StorageGRID 이미지 버전을 포함한 기본 운영 체제 정보



| 번들  a| 
글로벌 구성 정보(번들)



| Cassandra 를 클릭합니다  a| 
Cassandra 데이터베이스 정보 및 리퍼 복구 로그.



| EC  a| 
현재 노드에 대한 VCSs 정보 및 프로필 ID별 EC 그룹 정보



| 그리드  a| 
디버그(bycast.log)와 스베르매니저 로그를 포함한 일반 그리드 로그입니다.



| grid.xml  a| 
모든 노드에서 공유되는 그리드 구성 파일입니다.



| 해그루  a| 
고가용성 그룹 메트릭 및 로그



| 설치합니다  a| 
'두서버' 및 설치 로그.



| lumberjack.log  a| 
로그 수집과 관련된 디버그 메시지입니다.



| 람다 - 중재인  a| 
S3 Select 프록시 요청과 관련된 로그입니다.



| 메트릭  a| 
Grafana, Jaeger, 노드 수출자 및 Prometheus에 대한 서비스 로그.



| 오류  a| 
Miscd 액세스 및 오류 로그.



| MySQL  a| 
MariaDB 데이터베이스 구성 및 관련 로그.



| 결과  a| 
네트워킹 관련 스크립트 및 Dynip 서비스에서 생성된 로그입니다.



| Nginx  a| 
부하 분산 장치 구성 파일 및 로그 그리드 관리자 및 테넌트 관리자 트래픽 로그도 포함됩니다.



| Nginx-GW  a| 
부하 분산 장치 구성 파일 및 로그



| NTP  a| 
NTP 구성 파일 및 로그



| OS  a| 
서비스 PID를 포함한 노드 및 그리드 상태 파일



| 기타  a| 
다른 폴더에 수집되지 않은 '/var/local/log' 아래의 로그 파일.



| 성능  a| 
CPU, 네트워킹 및 디스크 I/O에 대한 성능 정보



| Prometheus - 데이터  a| 
로그 컬렉션에 Prometheus 데이터가 포함된 경우 현재 Prometheus 메트릭입니다.



| 프로비저닝  a| 
그리드 프로비저닝 프로세스와 관련된 로그입니다.



| 래프트  a| 
플랫폼 서비스에 사용되는 RAFT 클러스터의 로그입니다.



| SNMP를 선택합니다  a| 
SNMP 에이전트 구성 및 알람 허용/거부 목록은 SNMP 알림을 보내는 데 사용됩니다.



| 소켓 - 데이터  a| 
네트워크 디버그용 소켓 데이터



| system-commands.txt  a| 
StorageGRID 컨테이너 명령의 출력 네트워킹 및 디스크 사용과 같은 시스템 정보를 포함합니다.

|===
.관련 정보
xref:collecting-log-files-and-system-data.adoc[로그 파일 및 시스템 데이터를 수집합니다]
