---
permalink: monitor/set-up-snmp-alert-notifications.html 
sidebar: sidebar 
keywords: how to use snmp notifications for alerts 
summary: 경고가 발생할 때 StorageGRID에서 SNMP 알림을 보내도록 하려면 StorageGRID SNMP 에이전트를 활성화하고 하나 이상의 트랩 대상을 구성해야 합니다. 
---
= 경고에 대한 SNMP 알림을 설정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
경고가 발생할 때 StorageGRID에서 SNMP 알림을 보내도록 하려면 StorageGRID SNMP 에이전트를 활성화하고 하나 이상의 트랩 대상을 구성해야 합니다.

그리드 관리자의 * 구성 * > * 모니터링 * > * SNMP 에이전트 * 옵션을 사용하거나 그리드 관리 API의 SNMP 끝점을 사용하여 StorageGRID SNMP 에이전트를 활성화 및 구성할 수 있습니다. SNMP 에이전트는 SNMP 프로토콜의 세 가지 버전을 모두 지원합니다.

SNMP 에이전트를 구성하는 방법에 대한 자세한 내용은 을 참조하십시오 xref:using-snmp-monitoring.adoc[SNMP 모니터링을 사용합니다].

StorageGRID SNMP 에이전트를 구성한 후 두 가지 유형의 이벤트 기반 알림을 보낼 수 있습니다.

* 트랩은 관리 시스템에서 확인이 필요하지 않은 SNMP 에이전트가 보낸 알림입니다. 트랩은 알림이 트리거되는 등 StorageGRID 내에 발생한 사항을 관리 시스템에 알리는 역할을 합니다. 트랩은 SNMP의 세 가지 버전에서 모두 지원됩니다.
* 는 트랩과 유사하지만 관리 시스템에서 확인을 필요로 합니다. SNMP 에이전트가 일정 시간 내에 승인을 받지 못하면 승인을 받거나 최대 재시도 값에 도달할 때까지 알림을 다시 보냅니다. SNMPv2c 및 SNMPv3에서 알림이 지원됩니다.


기본 또는 사용자 지정 경고가 심각도 수준에서 트리거되면 트랩 및 알림 알림이 전송됩니다. 경고에 대한 SNMP 알림을 표시하지 않으려면 경고에 대한 무음을 구성해야 합니다. 을 참조하십시오 xref:silencing-alert-notifications.adoc[알림 메시지를 해제합니다].

경고 알림은 선호하는 송신자가 되도록 구성된 관리 노드에서 보냅니다. 기본적으로 기본 관리 노드가 선택됩니다. 를 참조하십시오 xref:../admin/index.adoc[StorageGRID 관리 지침].


NOTE: 특정 알람(기존 시스템)이 지정된 심각도 수준 이상으로 트리거될 때도 트랩 및 알림 알림이 전송되지만, 모든 알람 또는 모든 알람 심각도에 대해 SNMP 알림이 전송되지 않습니다. 을 참조하십시오 xref:alarms-that-generate-snmp-notifications.adoc[SNMP 알림을 생성하는 알람(레거시 시스템)].
