---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: 그리드 노드를 폐기하기 전에 활성화된 데이터 복구 작업이 없는지 확인해야 합니다. 수리가 실패한 경우 서비스를 다시 시작하고 서비스 해제 절차를 수행하기 전에 수리가 완료될 수 있도록 해야 합니다. 
---
= 데이터 복구 작업을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드를 폐기하기 전에 활성화된 데이터 복구 작업이 없는지 확인해야 합니다. 수리가 실패한 경우 서비스를 다시 시작하고 서비스 해제 절차를 수행하기 전에 수리가 완료될 수 있도록 해야 합니다.

연결이 끊긴 스토리지 노드의 서비스를 해제해야 하는 경우 서비스 해제 절차가 완료된 후 데이터 복구 작업이 성공적으로 완료되도록 이러한 단계를 완료해야 합니다. 제거된 노드에 있었던 삭제 코딩 조각이 성공적으로 복구되었는지 확인해야 합니다.

이 단계는 삭제 코딩 오브젝트가 있는 시스템에만 적용됩니다.

. 기본 관리자 노드에 로그인합니다.
+
.. 'ssh admin@_grid_node_ip_' 명령을 입력합니다
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.

.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
.. 루트로 전환하려면 다음 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.


. Repair-data show-ec-repair-status'라는 복구 실행 여부를 확인한다
+
** 데이터 복구 작업을 실행하지 않은 경우 출력은 "작업을 찾을 수 없음"입니다. 복구 작업을 다시 시작할 필요가 없습니다.
** 데이터 복구 작업이 이전에 실행되었거나 현재 실행 중인 경우 출력에 복구에 대한 정보가 나열됩니다. 각 수리마다 고유한 수리 ID가 있습니다. 다음 단계로 이동합니다.


+
[listing]
----
root@DC1-ADM1:~ # repair-data show-ec-repair-status

Repair ID Scope Start Time End Time State Est/Affected Bytes Repaired Retry Repair
===================================================================================
949283 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:27:06.9 Success 17359 17359 No
949292 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:37:06.9 Failure 17359 0     Yes
949294 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:47:06.9 Failure 17359 0     Yes
949299 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:57:06.9 Failure 17359 0     Yes
----
. 모든 수리의 상태가 '성공'이면 수리 작업을 다시 시작할 필요가 없습니다.
. 복구 상태가 "실패"인 경우 해당 복구를 다시 시작해야 합니다.
+
.. 출력에서 실패한 복구에 대한 수리 ID를 얻습니다.
.. repair-data start-ec-node-repair' 명령을 실행합니다.
+
'--repair-id' 옵션을 사용하여 복구 ID를 지정합니다. 예를 들어 복구 ID 949292를 사용하여 복구를 다시 시도하려는 경우 이 명령을 실행합니다. repair-data start-ec-node-repair--repair-id 949292

.. 모든 수리에 대한 상태가 '성공'이 될 때까지 EC 데이터 수리 상태를 계속 추적합니다.



