---
permalink: maintain/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, installation files, download 
summary: StorageGRID 그리드 노드를 복구하려면 먼저 소프트웨어를 다운로드하고 파일을 추출해야 합니다. 
---
= StorageGRID 설치 파일을 다운로드하고 압축을 풉니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 그리드 노드를 복구하려면 먼저 소프트웨어를 다운로드하고 파일을 추출해야 합니다.

그리드에서 현재 실행 중인 StorageGRID 버전을 사용해야 합니다.

.단계
. 현재 설치된 소프트웨어 버전을 확인합니다. 그리드 관리자 상단에서 도움말 아이콘을 선택하고 * 정보 * 를 선택합니다.
. StorageGRID용 NetApp 다운로드 페이지로 이동합니다.
+
https://["NetApp 다운로드: StorageGRID"]

. 그리드에서 현재 실행 중인 StorageGRID 버전을 선택합니다.
+
StorageGRID 소프트웨어 버전은 11.x.x.y 형식으로 되어 있습니다

. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
. 다운로드 페이지의 * StorageGRID * 설치 열에서 해당 플랫폼의 ".tgz" 또는 ".zip" 파일을 선택합니다.
+
설치 아카이브 파일에 표시된 버전이 현재 설치된 소프트웨어 버전과 일치해야 합니다.

+
Windows를 실행 중인 경우 '.zip' 파일을 사용합니다.

+
[cols="1a,2a"]
|===
| 플랫폼 | 설치 아카이브 


 a| 
Red Hat Enterprise Linux 또는 CentOS
| 'S torageGRID-Webscale-_version_-RPM-_UniqueID_.zip''S torageGRID-Webscale-_version_-RPM-_UniqueID_.tgz' 


 a| 
Ubuntu 또는 Debian 또는 어플라이언스
| 'storageGRID-Webscale-_version_-deb-_UniqueID_.zip''storageGRID-Webscale-_version_-deb-_UniqueID_.tgz' 


 a| 
VMware
| 'S torageGRID-Webscale-_version_-vmware-_UniqueID_.zip''S torageGRID-Webscale-_version_-vmware-_UniqueID_.tgz' 
|===
. 아카이브 파일을 다운로드하고 압축을 풉니다.
. 플랫폼에 적합한 단계에 따라 필요한 파일과 복구해야 할 그리드 노드를 기반으로 선택하십시오.
+
각 플랫폼의 단계에 나열된 경로는 아카이브 파일에 의해 설치된 최상위 디렉토리를 기준으로 합니다.

. 를 복구하는 경우 xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS 시스템]에서 해당 파일을 선택합니다.


[cols="1a,1a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| ./rpms/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./rpms/NLF000000.txt  a| 
제품에 대한 지원 권한을 제공하지 않는 무료 라이센스입니다.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RHEL 또는 CentOS 호스트에 StorageGRID 노드 이미지를 설치하기 위한 rpm 패키지입니다.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RHEL 또는 CentOS 호스트에 StorageGRID 호스트 서비스를 설치하기 위한 rpm 패키지입니다.



| 배포 스크립팅 도구 | 설명 


| ./rpms/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./rpms/configure-sga.py  a| 
StorageGRID 어플라이언스 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /rpms/configure -StorageGrid.sample.json  a| 
"configure-StorageGrid.py" 스크립트와 함께 사용할 구성 파일의 예



| ./rpms/storagegrid-ssoauth.py  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제



| /rpms/configure -StorageGrid.blank.json을 지정합니다  a| 
configure-StorageGrid.py 스크립트와 함께 사용할 빈 구성 파일입니다.



| ./rpms/Extras/Ansible  a| 
StorageGRID 컨테이너 배포를 위한 RHEL 또는 CentOS 호스트 구성을 위한 Ansible 역할 및 플레이북의 예 필요에 따라 역할 또는 플레이북을 사용자 지정할 수 있습니다.



| /rpms/Extras/API-schemas  a| 
StorageGRID에 대한 API 스키마입니다.

* 참고 *: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 StorageGRID 관리 API를 사용하도록 작성한 코드가 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===
. 를 복구하는 경우 xref:../ubuntu/index.adoc[Ubuntu 또는 Debian 시스템]에서 해당 파일을 선택합니다.


[cols="1a,1a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| ./debs/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| /debs/NLF000000.txt 를 참조하십시오  a| 
테스트 및 개념 증명 배포에 사용할 수 있는 비프로덕션 NetApp 라이센스 파일.



| /debs/storagegrid-webscale-images-version-SHA.deb 를 참조하십시오  a| 
StorageGRID 노드 이미지를 Ubuntu 또는 Debian 호스트에 설치하기 위한 DEB 패키지.



| /debs/storagegrid-webscale-images-version-SHA.deb.md5 를 참조하십시오  a| 
파일 '/debs/storagegrid-webscale-images-version-SHA.deb` 에 대한 MD5 체크섬입니다.



| /debs/storagegrid-webscale-service-version-SHA.deb 를 참조하십시오  a| 
Ubuntu 또는 Debian 호스트에 StorageGRID 호스트 서비스를 설치하기 위한 DEB 패키지.



| 배포 스크립팅 도구 | 설명 


| /debs/configure-storagegrid.py 를 참조하십시오  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /debs/configure-sga.py 를 참조하십시오  a| 
StorageGRID 어플라이언스 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /debs/storagegrid-ssoauth.py 를 참조하십시오  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제



| /debs/configure -StorageGrid.sample.json 을 참조하십시오  a| 
"configure-StorageGrid.py" 스크립트와 함께 사용할 구성 파일의 예



| /debs/configure -StorageGrid.blank.json 을 참조하십시오  a| 
configure-StorageGrid.py 스크립트와 함께 사용할 빈 구성 파일입니다.



| ./debs/Extras/Ansible  a| 
StorageGRID 컨테이너 배포를 위한 Ubuntu 또는 Debian 호스트 구성을 위한 Ansible 역할 및 플레이북 예 필요에 따라 역할 또는 플레이북을 사용자 지정할 수 있습니다.



| /debs/Extras/API-schemas  a| 
StorageGRID에 대한 API 스키마입니다.

* 참고 *: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 StorageGRID 관리 API를 사용하도록 작성한 코드가 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===
. 를 복구하는 경우 xref:../vmware/index.adoc[VMware 시스템]에서 해당 파일을 선택합니다.


[cols="1a,1a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| ./vSphere/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./vSphere/NLF000000.txt  a| 
제품에 대한 지원 권한을 제공하지 않는 무료 라이센스입니다.



| ./vSphere/NetApp-SG-version-SHA.vmdk입니다  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.



| ./vSphere/vSphere-primary-admin.ovf./vSphere/vSphere-primary-admin.mf  a| 
기본 관리 노드를 배포하기 위한 오픈 가상화 형식 템플릿 파일(".ovf") 및 매니페스트 파일(".mf")입니다.



| ./vSphere/vSphere-non-primary-admin.ovf./vSphere/vSphere-non-primary-admin.mf  a| 
비기본 관리 노드를 배포하기 위한 템플릿 파일(".ovf")과 매니페스트 파일(".mf")입니다.



| /vSphere/vSphere-archive.ovf./vSphere/vSphere-archive.mf  a| 
아카이브 노드 배포를 위한 템플릿 파일(".ovf")과 매니페스트 파일(".mf")입니다.



| ./vSphere/vSphere-gateway.ovf./vSphere/vSphere-gateway.mf  a| 
게이트웨이 노드를 배포하기 위한 템플릿 파일(".ovf")과 매니페스트 파일(".mf")입니다.



| ./vSphere/vSphere-storage.ovf./vSphere/vSphere-storage.mf  a| 
가상 머신 기반 스토리지 노드 구축을 위한 템플릿 파일('.ovf') 및 매니페스트 파일('.mf')입니다.



| 배포 스크립팅 도구 | 설명 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 쉘 스크립트입니다.



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
'deploy-vsphere-ovftool.sh' 스크립트와 함께 사용할 구성 파일의 예.



| ./vSphere/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vSphere/configure-sga.py  a| 
StorageGRID 어플라이언스 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vSphere/storagegrid-ssoauth.py  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제



| /vSphere/configure -StorageGrid.sample.json을 참조하십시오  a| 
"configure-StorageGrid.py" 스크립트와 함께 사용할 구성 파일의 예



| /vSphere/configure -StorageGrid.blank.json 을 참조하십시오  a| 
configure-StorageGrid.py 스크립트와 함께 사용할 빈 구성 파일입니다.



| /vSphere/Extras/API-schemas  a| 
StorageGRID에 대한 API 스키마입니다.

* 참고 *: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 StorageGRID 관리 API를 사용하도록 작성한 코드가 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===
. StorageGRID 어플라이언스 기반 시스템을 복구하는 경우 적절한 파일을 선택합니다.


[cols="1a,1a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| /debs/storagegrid-webscale-images-version-SHA.deb 를 참조하십시오  a| 
어플라이언스에 StorageGRID 노드 이미지를 설치하기 위한 DEB 패키지.



| /debs/storagegrid-webscale-images-version-SHA.deb.md5 를 참조하십시오  a| 
업로드 후 패키지가 손상되지 않았는지 확인하기 위해 StorageGRID 어플라이언스 설치 프로그램에서 사용하는 DEB 설치 패키지의 체크섬입니다.

|===

NOTE: 어플라이언스 설치의 경우, 이러한 파일은 네트워크 트래픽을 방지해야 하는 경우에만 필요합니다. 어플라이언스는 기본 관리 노드에서 필요한 파일을 다운로드할 수 있습니다.
