---
permalink: maintain/fixing-missing-block-device-errors.html 
sidebar: sidebar 
keywords: storagegrid, missing block device, block device error 
summary: '시스템은 복구된 각 노드가 유효한 블록 디바이스 특수 파일 또는 블록 디바이스 특수 파일에 대한 유효한 소프트링크에 매핑되는지 확인합니다. StorageGRID가 "/etc/StorageGrid/nodes/_node-name_.conf" 파일에서 잘못된 매핑을 찾으면 누락된 블록 디바이스 오류가 표시됩니다.' 
---
= 누락된 블록 장치 오류를 수정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템은 복구된 각 노드가 유효한 블록 디바이스 특수 파일 또는 블록 디바이스 특수 파일에 대한 유효한 소프트링크에 매핑되는지 확인합니다. StorageGRID가 '/etc/StorageGrid/nodes/_node-name_.conf' 파일에서 잘못된 매핑을 찾으면 누락된 블록 디바이스 오류가 표시됩니다.

이 패턴과 일치하는 오류가 발생하는 경우:

"node_node-name_...에 대한 구성 파일 /etc/StorageGrid/nodes/_node-name_.conf 확인 중. "error:_node-name_: block_device_purpose=_path-name_""_node-name_:_path-name_not exist.

즉, '/etc/StorageGrid/nodes/_node-name_.conf'는 Linux 파일 시스템에서 지정된 경로 이름에 사용하도록 _node-name_에 사용되는 블록 디바이스를 매핑하지만 해당 위치에 유효한 블록 디바이스 특수 파일 또는 블록 디바이스 특수 파일에 대한 소프트링크가 없음을 의미합니다.

의 단계를 완료했는지 확인합니다 xref:deploying-new-linux-hosts.adoc[새 Linux 호스트를 배포합니다]. 원래 호스트에서 사용된 것과 동일한 영구 디바이스 이름을 모든 블록 디바이스에 사용합니다.

누락된 블록 디바이스 특수 파일을 복구하거나 다시 생성할 수 없는 경우 적절한 크기 및 스토리지 범주의 새 블록 디바이스를 할당하고 노드 구성 파일을 편집하여 새 블록 디바이스 특수 파일을 가리키도록 block_device_purpose 값을 변경할 수 있습니다.

Linux 운영 체제 설치 지침의 "스토리지 요구 사항" 섹션에 있는 표에서 적절한 크기와 스토리지 범주를 확인하십시오. 블록 디바이스 교체를 진행하기 전에 ""호스트 스토리지 구성""의 권장 사항을 검토하십시오.


IMPORTANT: 장애가 발생한 호스트에서 원래 블록 디바이스가 손실되었기 때문에 "BLOCK_DEVICE_"로 시작하는 구성 파일 변수에 대해 새 블록 스토리지 디바이스를 제공해야 하는 경우 추가 복구 절차를 시도하기 전에 새 블록 디바이스의 포맷이 해제되었는지 확인하십시오. 공유 스토리지를 사용 중이고 새 볼륨을 생성한 경우 새 블록 디바이스의 포맷이 해제됩니다. 확실하지 않은 경우 새 블록 스토리지 디바이스 특수 파일에 대해 다음 명령을 실행합니다.

주의:

새 블록 스토리지 디바이스에 대해서만 다음 명령을 실행합니다. 블록 스토리지에 복구 중인 노드에 대한 유효한 데이터가 계속 포함되어 있다고 생각되면 디바이스의 모든 데이터가 손실되므로 이 명령을 실행하지 마십시오.

[listing]
----
sudo dd if=/dev/zero of=/dev/mapper/my-block-device-name bs=1G count=1
----
xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS를 설치합니다]

xref:../ubuntu/index.adoc[Ubuntu 또는 Debian을 설치합니다]
