---
permalink: maintain/linux-adding-trunk-or-access-interfaces-to-node.html 
sidebar: sidebar 
keywords: add extra interface to node, trunk interface, access interface 
summary: Linux 노드를 설치한 후 추가 트렁크 또는 액세스 인터페이스를 추가할 수 있습니다. 추가한 인터페이스는 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시됩니다. 
---
= Linux: 노드에 트렁크 또는 액세스 인터페이스를 추가합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 노드를 설치한 후 추가 트렁크 또는 액세스 인터페이스를 추가할 수 있습니다. 추가한 인터페이스는 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시됩니다.

.필요한 것
* Linux 플랫폼에 StorageGRID를 설치하는 지침을 액세스할 수 있습니다.
+
** xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS를 설치합니다]
** xref:../ubuntu/index.adoc[Ubuntu 또는 Debian을 설치합니다]


* "passwords.txt" 파일이 있습니다.
* 특정 액세스 권한이 있습니다.



IMPORTANT: 소프트웨어 업그레이드, 복구 절차 또는 확장 절차가 활성 상태인 동안에는 노드에 인터페이스를 추가하지 마십시오.

.이 작업에 대해
노드를 설치한 후 Linux 노드에 하나 이상의 추가 인터페이스를 추가하려면 다음 단계를 수행하십시오. 예를 들어, 관리 또는 게이트웨이 노드에 트렁크 인터페이스를 추가하여 VLAN 인터페이스를 사용하여 다른 애플리케이션이나 테넌트에 속한 트래픽을 분리할 수 있습니다. 또는 고가용성(HA) 그룹에서 사용할 액세스 인터페이스를 추가할 수도 있습니다.

트렁크 인터페이스를 추가하는 경우 StorageGRID에서 VLAN 인터페이스를 구성해야 합니다. 액세스 인터페이스를 추가할 경우 인터페이스를 HA 그룹에 직접 추가할 수 있으며, VLAN 인터페이스를 구성할 필요가 없습니다.

인터페이스를 추가할 때 노드를 잠시 사용할 수 없습니다. 이 절차는 한 번에 하나의 노드에서 수행해야 합니다.

.단계
. 노드를 호스팅하는 Linux 서버에 로그인합니다.
. vim 또는 pico와 같은 텍스트 편집기를 사용하여 노드 구성 파일을 편집합니다.
+
'/etc/StorageGrid/nodes/_node-name_.conf'

. 파일에 항목을 추가하여 이름을 지정하고 선택적으로 노드에 추가할 각 추가 인터페이스에 대한 설명을 지정합니다. 이 형식을 사용합니다.
+
'interfaces_target_nnnn=_value_'

+
nnnn_의 경우 추가하려는 각 "interfaces_target" 항목에 대해 고유 번호를 지정합니다.

+
value_에 대해 베어 메탈 호스트의 물리적 인터페이스 이름을 지정합니다. 그런 다음 필요에 따라 쉼표를 추가하고 인터페이스에 대한 설명을 입력합니다. 이 설명은 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시됩니다.

+
예를 들면 다음과 같습니다.

+
interfaces_target_01=en256, 트렁크

+

IMPORTANT: 다른 네트워크 매개 변수를 지정하지 마십시오. 그렇지 않으면 유효성 검사 오류가 발생합니다.

. 다음 명령을 실행하여 노드 구성 파일의 변경 내용을 검증합니다.
+
'SUDO StorageGRID node validate_node-name_'

+
다음 단계로 진행하기 전에 오류 또는 경고를 모두 해결하십시오.

. 다음 명령을 실행하여 노드의 구성을 업데이트합니다.
+
'SUDO StorageGRID NODE RELOAD_NODE-NAME_'



.작업을 마친 후
* 하나 이상의 트렁크 인터페이스를 추가한 경우 로 이동합니다 xref:../admin/configure-vlan-interfaces.html[VLAN 인터페이스를 구성합니다] 각 새 상위 인터페이스에 대해 하나 이상의 VLAN 인터페이스를 구성하려면 다음을 수행합니다.
* 하나 이상의 액세스 인터페이스를 추가한 경우 로 이동합니다 xref:../admin/configure-high-availability-group.html[고가용성 그룹을 구성합니다] 새 인터페이스를 HA 그룹에 직접 추가합니다.

