---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 핫픽스를 적용하기 전에 필요한 모든 자료를 확보해야 합니다. 
---
= 핫픽스에 필요한 자료를 얻습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
핫픽스를 적용하기 전에 필요한 모든 자료를 확보해야 합니다.

[cols="1a,2a"]
|===
| 항목 | 참고 


 a| 
StorageGRID 핫픽스 파일
 a| 
StorageGRID 핫픽스 파일을 다운로드해야 합니다.



 a| 
* 네트워크 포트
* xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저]
* SSH 클라이언트(예: PuTTY)

 a| 



 a| 
복구 패키지(".zip") 파일
 a| 
핫픽스를 적용하기 전에 xref:downloading-recovery-package.adoc[최신 복구 패키지 파일을 다운로드합니다] 핫픽스 중에 문제가 발생하는 경우 핫픽스를 적용한 후 복구 패키지 파일의 새 복사본을 다운로드하여 안전한 위치에 저장합니다. 업데이트된 복구 패키지 파일을 사용하면 오류가 발생할 경우 시스템을 복원할 수 있습니다.



| Passwords.txt 파일  a| 
선택 사항이며 SSH 클라이언트를 사용하여 핫픽스를 수동으로 적용하는 경우에만 사용됩니다. 복구 패키지 .zip의 일부인 해당 패키지에 passwords.txt 파일이 포함되어 있습니다.



 a| 
프로비저닝 암호
 a| 
StorageGRID 시스템을 처음 설치할 때 암호가 생성되고 문서화됩니다. 프로비저닝 암호는 passwords.txt 파일에 나열되지 않습니다.



 a| 
관련 문서
 a| 
핫픽스 "readme.txt" 파일. 이 파일은 핫픽스 다운로드 페이지에 포함되어 있습니다. 핫픽스를 적용하기 전에 반드시 "다시 보기" 파일을 주의 깊게 검토하십시오.

|===
.관련 정보
xref:downloading-hotfix-file.adoc[핫픽스 파일을 다운로드합니다]
