---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: 로드 밸런서 서비스에 대한 끝점을 구성하려는 경우 포트 재매핑의 매핑된-대상 포트로 이미 구성된 포트를 사용하려면 먼저 기존 포트 재매핑을 제거해야 합니다. 그렇지 않으면 끝점이 적용되지 않습니다. 노드의 모든 포트 매핑을 제거하려면 재매핑된 포트가 충돌하는 각 관리 노드와 게이트웨이 노드에서 스크립트를 실행해야 합니다. 
---
= 포트 재맵을 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로드 밸런서 서비스에 대한 끝점을 구성하려는 경우 포트 재매핑의 매핑된-대상 포트로 이미 구성된 포트를 사용하려면 먼저 기존 포트 재매핑을 제거해야 합니다. 그렇지 않으면 끝점이 적용되지 않습니다. 노드의 모든 포트 매핑을 제거하려면 재매핑된 포트가 충돌하는 각 관리 노드와 게이트웨이 노드에서 스크립트를 실행해야 합니다.

.이 작업에 대해

CAUTION: 이 절차를 수행하면 모든 포트 재맵이 제거됩니다. 일부 재맵을 유지해야 하는 경우 기술 지원 부서에 문의하십시오.

로드 밸런서 엔드포인트를 구성하는 방법에 대한 자세한 내용은 StorageGRID 관리 지침을 참조하십시오.


IMPORTANT: 포트 재매핑이 클라이언트 액세스를 제공하는 경우, 가능한 경우 로드 밸런서 끝점으로 구성된 다른 포트를 사용하도록 클라이언트를 다시 구성해야 서비스 손실을 방지할 수 있습니다. 그렇지 않으면 포트 매핑을 제거하면 클라이언트 액세스가 손실되므로 적절하게 예약해야 합니다.


IMPORTANT: 베어 메탈 호스트에 컨테이너로 배포된 StorageGRID 시스템에서는 이 절차를 사용할 수 없습니다. 의 지침을 참조하십시오 xref:removing-port-remaps-on-bare-metal-hosts.adoc[베어 메탈 호스트에서 포트 리맵을 제거합니다].

.단계
. 노드에 로그인합니다.
+
.. 'ssh-p 8022 admin@node_ip' 명령을 입력합니다
+
포트 8022는 기본 OS의 SSH 포트이고, 포트 22는 StorageGRID를 실행하는 컨테이너 엔진의 SSH 포트입니다.

.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
.. 루트로 전환하려면 다음 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



. remove-port-remap.sh 스크립트를 실행합니다
. 노드를 재부팅합니다.
+
의 지침을 따릅니다 xref:rebooting-grid-node.adoc[그리드 노드 재부팅].

. 재매핑된 포트가 충돌하는 각 관리 노드와 게이트웨이 노드에서 이 단계를 반복합니다.


.관련 정보
xref:../admin/index.adoc[StorageGRID 관리]
