---
permalink: maintain/restoring-and-validating-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore grid node, restore node, validate grid node, validate node 
summary: 장애가 발생한 그리드 노드에 대해 그리드 구성 파일을 복원한 다음 그리드 구성 파일의 유효성을 검사하고 오류를 해결해야 합니다. 
---
= 그리드 노드 복원 및 검증
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
장애가 발생한 그리드 노드에 대해 그리드 구성 파일을 복원한 다음 그리드 구성 파일의 유효성을 검사하고 오류를 해결해야 합니다.

이전 호스트의 장애로 인해 '/var/local' 볼륨이 손실되지 않은 경우 호스트에 있어야 하는 모든 그리드 노드를 가져올 수 있습니다. 예를 들어, Linux 운영 체제의 StorageGRID 설치 지침에 설명된 대로 StorageGRID 시스템 데이터 볼륨에 공유 스토리지를 사용한 경우 '/var/local' 볼륨이 계속 존재할 수 있습니다. 노드를 가져오면 해당 노드 구성 파일이 호스트에 복구됩니다.

누락된 노드를 가져올 수 없는 경우 그리드 구성 파일을 다시 생성해야 합니다.

그런 다음 그리드 구성 파일을 확인하고 StorageGRID를 다시 시작하기 전에 발생할 수 있는 네트워킹 또는 스토리지 문제를 해결해야 합니다. 노드에 대한 구성 파일을 다시 생성할 때 복구 중인 노드에 사용된 교체 노드에 대해 동일한 이름을 사용해야 합니다.

노드의 '/var/local' 볼륨 위치에 대한 자세한 내용은 설치 지침을 참조하십시오.

.단계
. 복구된 호스트의 명령줄에 현재 구성된 모든 StorageGRID 그리드 노드('SUDO StorageGRID node list')를 나열합니다
+
그리드 노드가 구성되어 있지 않으면 출력이 없습니다. 일부 그리드 노드가 구성된 경우 다음과 같은 형식으로 출력이 예상됩니다.

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
호스트에서 구성해야 하는 일부 또는 모든 그리드 노드가 목록에 없는 경우 누락된 그리드 노드를 복원해야 합니다.

. '/var/local' 볼륨이 있는 그리드 노드를 가져오려면:
+
.. 가져올 각 노드에 대해 ''SUDO StorageGRID node import node -var-local-volume-path'를 실행합니다
+
StorageGRID node import 명령은 대상 노드가 마지막으로 실행된 호스트에서 완전히 종료된 경우에만 성공한다. 그렇지 않으면 다음과 유사한 오류가 발생합니다.

+
"이 노드(_node-name_)는 다른 호스트(UUID host-uuuid)가 소유한 것으로 보입니다.

+
수입은 안전하다고 확신한다면 -force 플래그를 사용하세요

.. 다른 호스트가 소유하는 노드에 대한 오류가 표시되는 경우 '--force' 플래그를 사용하여 명령을 다시 실행하여 가져오기를 완료합니다. ''SUDO StorageGRID --force node import node -var-local-volume-path'
+

NOTE: '--force' 플래그를 사용하여 가져온 모든 노드는 에 설명된 대로 그리드에 다시 참가하기 전에 추가 복구 단계가 필요합니다 xref:whats-next-performing-additional-recovery-steps-if-required.adoc[다음 단계: 필요한 경우 추가 복구 단계를 수행합니다].



. '/var/local' 볼륨이 없는 그리드 노드의 경우 노드의 구성 파일을 다시 생성하여 호스트에 복구합니다.
+
설치 지침에 있는 "'노드 구성 파일 작성'의 지침을 따르십시오.

+

IMPORTANT: 노드에 대한 구성 파일을 다시 생성할 때 복구 중인 노드에 사용된 교체 노드에 대해 동일한 이름을 사용해야 합니다. Linux 배포의 경우 구성 파일 이름에 노드 이름이 포함되어 있는지 확인합니다. 가능하면 동일한 네트워크 인터페이스, 블록 장치 매핑 및 IP 주소를 사용해야 합니다. 이러한 관행은 복구 중에 노드로 복사해야 하는 데이터 양을 최소화하여 복구 속도가 크게 향상되도록 합니다(경우에 따라 몇 주가 아닌 몇 분).

+

IMPORTANT: 노드에 대한 구성 파일을 다시 생성할 때 "BLOCK_DEVICE_"로 시작하는 구성 변수의 값으로 새 블록 디바이스(StorageGRID 노드에서 이전에 사용하지 않은 디바이스)를 사용하는 경우 의 모든 지침을 따라야 합니다 xref:fixing-missing-block-device-errors.adoc[누락된 블록 장치 오류를 수정합니다].

. 복구된 호스트에서 다음 명령을 실행하여 모든 StorageGRID 노드를 나열합니다.
+
'SUDO StorageGRID node list

. StorageGRID 노드 목록 출력에 이름이 표시된 각 그리드 노드에 대한 노드 구성 파일의 유효성을 검사합니다.
+
'SUDO StorageGRID node validate_node-name_'

+
StorageGRID 호스트 서비스를 시작하기 전에 오류 또는 경고를 해결해야 합니다. 다음 섹션에서는 복구 중에 특별한 의미가 있을 수 있는 오류에 대해 자세히 설명합니다.



xref:../rhel/index.adoc[Red Hat Enterprise Linux 또는 CentOS를 설치합니다]

xref:../ubuntu/index.adoc[Ubuntu 또는 Debian을 설치합니다]

xref:fixing-mssing-network-interface-errors.adoc[누락된 네트워크 인터페이스 오류를 수정합니다]
