---
permalink: primer/configuring-network-settings.html 
sidebar: sidebar 
keywords: network settings, configure, configuring, configuration, domain name, virtual hosted-style requests 
summary: 그리드 관리자에서 다양한 네트워크 설정을 구성하여 StorageGRID 시스템의 작동을 미세 조정할 수 있습니다. 
---
= 네트워크 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자에서 다양한 네트워크 설정을 구성하여 StorageGRID 시스템의 작동을 미세 조정할 수 있습니다.



== 도메인 이름

S3 가상 호스팅 스타일 요청을 지원하려는 경우 S3 클라이언트가 연결하는 끝점 도메인 이름 목록을 구성해야 합니다. 예를 들어 3.example.com, 3.example.co.uk, 3-east.example.com 등이 있습니다.

구성된 서버 인증서는 끝점 도메인 이름과 일치해야 합니다.



== 고가용성 그룹

고가용성(HA) 그룹을 사용하여 S3 및 Swift 클라이언트에 고가용성 데이터 연결을 제공하거나 그리드 관리자 및 테넌트 관리자에 고가용성 연결을 제공할 수 있습니다.

HA 그룹을 생성할 때 하나 이상의 노드에 대한 네트워크 인터페이스를 선택합니다. 각 HA 그룹은 선택한 노드의 공유 서비스에 대한 액세스를 제공합니다.

* 게이트웨이 노드의 인터페이스를 포함하는 HA 그룹, 관리 노드 또는 둘 다 S3 및 Swift 클라이언트에 고가용성 데이터 연결을 제공합니다.
* 관리 노드의 인터페이스를 포함하는 HA 그룹은 Grid Manager 및 테넌트 관리자에 대한 고가용성 연결만 제공합니다.


인터페이스는 그리드 네트워크(eth0), 클라이언트 네트워크(eth2) 또는 VLAN 네트워크에 속할 수 있습니다.

각 HA 그룹에 최대 10개의 가상 IP(VIP) 주소를 할당할 수 있습니다. 하나의 인터페이스를 기본 인터페이스로 지정하고 다른 인터페이스의 우선 순위를 지정합니다. Primary 인터페이스는 장애가 발생하지 않는 한 Active 인터페이스입니다. 활성 인터페이스에 장애가 발생하면 VIP 주소가 우선 순위에 따라 첫 번째 백업 인터페이스로 이동합니다. 이 인터페이스에 장애가 발생하면 VIP 주소가 다음 백업 인터페이스로 이동합니다.



== 비용 연결

링크 비용을 조정하여 사이트 간 지연 시간을 반영할 수 있습니다. 두 개 이상의 데이터 센터 사이트가 존재하는 경우 링크 비용은 요청된 서비스를 제공해야 하는 데이터 센터 사이트의 우선 순위를 지정합니다.



== 부하 분산 장치 엔드포인트

로드 밸런서를 사용하여 S3 및 Swift 클라이언트에서 수집 및 검색 워크로드를 처리할 수 있습니다. 로드 밸런싱은 여러 스토리지 노드에 워크로드와 연결을 분산하여 속도와 연결 용량을 극대화합니다.

관리 노드 및 게이트웨이 노드에 포함된 StorageGRID 로드 밸런서 서비스를 사용하려면 하나 이상의 로드 밸런서 끝점을 구성해야 합니다. 각 엔드포인트는 S3 및 스토리지 노드에 대한 Swift 요청에 대한 게이트웨이 노드 또는 관리 노드 포트를 정의합니다.



== 트래픽 분류

트래픽 분류 정책을 생성하여 특정 버킷, 테넌트, 클라이언트 서브넷 또는 로드 밸런서 엔드포인트와 관련된 트래픽을 포함하여 다양한 유형의 네트워크 트래픽을 식별하고 처리할 수 있습니다. 이러한 정책은 트래픽 제한 및 모니터링을 지원할 수 있습니다.



== VLAN 인터페이스

VLAN(Virtual LAN) 인터페이스를 생성하여 트래픽을 격리하고 파티셔닝하여 보안, 유연성 및 성능을 확보할 수 있습니다. 각 VLAN 인터페이스는 관리 노드 및 게이트웨이 노드에서 하나 이상의 상위 인터페이스와 연결됩니다. HA 그룹 및 로드 밸런서 끝점에서 VLAN 인터페이스를 사용하여 클라이언트 또는 관리 트래픽을 애플리케이션 또는 테넌트별로 분리할 수 있습니다.

예를 들어 네트워크에서 FabricPool 트래픽에는 VLAN 100을 사용하고 아카이브 애플리케이션에는 VLAN 200을 사용할 수 있습니다.

.관련 정보
* xref:../admin/index.adoc[StorageGRID 관리]
* xref:managing-tenants-and-client-connections.adoc[테넌트 및 클라이언트 연결을 관리합니다]

