---
permalink: primer/managing-tenants-and-client-connections.html 
sidebar: sidebar 
keywords: tenant, client, connect, connection 
summary: 그리드 관리자는 S3 및 Swift 클라이언트가 오브젝트를 저장 및 검색하는 데 사용하는 테넌트 계정을 만들고 관리하며 클라이언트가 StorageGRID 시스템에 연결하는 방법을 제어하는 구성 옵션을 관리합니다. 
---
= 테넌트 및 클라이언트 연결을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 S3 및 Swift 클라이언트가 오브젝트를 저장 및 검색하는 데 사용하는 테넌트 계정을 만들고 관리하며 클라이언트가 StorageGRID 시스템에 연결하는 방법을 제어하는 구성 옵션을 관리합니다.



== 테넌트 계정

테넌트 계정을 사용하면 StorageGRID 시스템을 사용하여 객체를 저장 및 검색할 수 있는 사용자 및 사용 가능한 기능을 지정할 수 있습니다. 테넌트 계정을 사용하면 S3 REST API 또는 Swift REST API를 지원하는 클라이언트 애플리케이션이 StorageGRID에 오브젝트를 저장하고 검색할 수 있습니다. 각 테넌트 계정은 S3 클라이언트 프로토콜 또는 Swift 클라이언트 프로토콜을 사용합니다.

StorageGRID 시스템에 객체를 저장하는 데 사용할 각 클라이언트 프로토콜에 대해 하나 이상의 테넌트 계정을 생성해야 합니다. 필요에 따라 시스템에 저장된 객체를 다른 엔터티로 분리하려는 경우 추가 테넌트 계정을 생성할 수 있습니다. 각 테넌트 계정에는 자체 통합 또는 로컬 그룹 및 사용자와 자체 버킷(Swift용 컨테이너) 및 객체가 있습니다.

Grid Manager 또는 Grid Management API를 사용하여 테넌트 계정을 생성할 수 있습니다. 테넌트 계정을 생성할 때 다음 정보를 지정합니다.

* 테넌트의 표시 이름(테넌트의 계정 ID가 자동으로 할당되며 변경할 수 없음)
* 테넌트 계정에서 S3 또는 Swift를 사용할지 여부를 나타냅니다.
* S3 테넌트 계정의 경우: 테넌트 계정이 플랫폼 서비스를 사용하도록 허용되는지 여부 플랫폼 서비스를 사용할 수 있는 경우 그리드 사용을 지원하도록 구성해야 합니다.
* 필요한 경우 테넌트 계정의 스토리지 할당량 -- 테넌트의 객체에 사용할 수 있는 최대 GB, 테라바이트 또는 PB입니다. 테넌트의 스토리지 할당량은 물리적 크기(디스크 크기)가 아닌 논리적 양(오브젝트 크기)을 나타냅니다.
* StorageGRID 시스템에 대해 ID 페더레이션이 설정된 경우 테넌트 계정을 구성할 수 있는 루트 액세스 권한이 있는 통합 그룹입니다.
* StorageGRID 시스템에서 SSO(Single Sign-On)를 사용하지 않는 경우 테넌트 계정이 자체 ID 소스를 사용할지 또는 그리드의 ID 소스를 공유할지 여부 및 테넌트의 로컬 루트 사용자의 초기 암호를 공유할지 여부


S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 그리드 관리자는 StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정을 활성화할 수 있습니다. 시스템에 S3 오브젝트 잠금이 설정되어 있으면 모든 S3 테넌트 계정에서 S3 오브젝트 잠금이 설정된 버킷을 생성한 다음 해당 버킷의 오브젝트 버전에 대한 보존 및 법적 보류 설정을 지정할 수 있습니다.

테넌트 계정이 생성된 후 테넌트 사용자는 테넌트 관리자에 로그인할 수 있습니다.



== StorageGRID 노드에 대한 클라이언트 접속

테넌트 사용자가 S3 또는 Swift 클라이언트를 사용하여 StorageGRID에 데이터를 저장하고 검색하기 전에 이러한 클라이언트가 StorageGRID 노드에 어떻게 연결할지 결정해야 합니다.

클라이언트 응용 프로그램은 다음 중 하나를 연결하여 개체를 저장하거나 검색할 수 있습니다.

* 관리 노드 또는 게이트웨이 노드의 부하 분산 서비스 이것은 권장되는 연결입니다.
* 게이트웨이 노드의 CLB 서비스.
+

NOTE: CLB 서비스는 더 이상 사용되지 않습니다.

* 외부 로드 밸런서가 있거나 없는 스토리지 노드


클라이언트가 로드 밸런서 서비스를 사용할 수 있도록 StorageGRID를 구성할 때 다음 단계를 수행합니다.

. 필요에 따라 고가용성(HA) 그룹을 구성합니다. HA 그룹을 생성하면 여러 관리 노드 및 게이트웨이 노드의 인터페이스가 액티브 백업 구성에 배치됩니다. HA 그룹의 가상 IP 주소를 사용하여 클라이언트 연결이 이루어집니다.
. 로드 밸런서 서비스의 끝점을 구성합니다. 관리 노드 또는 게이트웨이 노드의 부하 분산 서비스는 들어오는 네트워크 연결을 클라이언트 애플리케이션에서 스토리지 노드로 분산합니다. 로드 밸런서 끝점을 만들 때 끝점에서 HTTP 또는 HTTPS 연결을 허용하는지 여부, 끝점을 사용할 클라이언트 유형(S3 또는 Swift) 및 HTTPS 연결에 사용할 인증서(해당하는 경우)를 포트 번호로 지정합니다.
. 노드의 클라이언트 네트워크에 대한 모든 연결이 로드 밸런서 끝점에서 발생하도록 노드의 클라이언트 네트워크를 신뢰할 수 없도록 지정합니다(선택 사항).


.관련 정보
* xref:../admin/index.adoc[StorageGRID 관리]
* xref:../tenant/index.adoc[테넌트 계정을 사용합니다]
* xref:../s3/index.adoc[S3을 사용합니다]
* xref:../swift/index.adoc[Swift를 사용합니다]
* xref:exploring-tenant-manager.adoc[테넌트 관리자를 탐색합니다]
* xref:configuring-network-settings.adoc[네트워크 설정을 구성합니다]

