---
permalink: primer/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: audit message 
summary: 감사 메시지를 통해 StorageGRID 시스템의 세부 작업을 보다 잘 이해할 수 있습니다. 감사 로그를 사용하여 문제를 해결하고 성능을 평가할 수 있습니다. 
---
= 감사 메시지를 검토합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 메시지를 통해 StorageGRID 시스템의 세부 작업을 보다 잘 이해할 수 있습니다. 감사 로그를 사용하여 문제를 해결하고 성능을 평가할 수 있습니다.

정상적인 시스템 작동 중에 모든 StorageGRID 서비스는 다음과 같이 감사 메시지를 생성합니다.

* 시스템 감사 메시지는 감사 시스템 자체, 그리드 노드 상태, 시스템 전체 작업 및 서비스 백업 작업과 관련되어 있습니다.
* 오브젝트 스토리지 감사 메시지는 오브젝트 스토리지 및 검색, 그리드 노드에서 그리드 노드 전송, 확인을 포함하여 StorageGRID 내의 오브젝트 스토리지 및 관리와 관련되어 있습니다.
* S3 또는 Swift 클라이언트 애플리케이션이 오브젝트 생성, 수정 또는 검색을 요청할 때 클라이언트 읽기 및 쓰기 감사 메시지가 기록됩니다.
* 관리 감사 메시지는 관리 API에 사용자 요청을 기록합니다.


각 관리 노드는 감사 메시지를 텍스트 파일에 저장합니다. 감사 공유에는 활성 파일(audit.log)과 이전 일로부터의 압축된 감사 로그가 포함됩니다. 또한 그리드의 각 노드는 제한된 양의 감사 메시지를 로컬 로그 파일(localaudit.log)에 저장합니다.

감사 로그에 쉽게 액세스할 수 있도록 NFS 및 CIFS에 대한 감사 공유에 대한 클라이언트 액세스를 구성할 수 있습니다(CIFS는 더 이상 사용되지 않음). 관리자 노드의 명령줄에서 직접 감사 로그 파일에 액세스할 수도 있습니다.

선택적으로 관리자 노드 및 로컬 노드에 저장된 감사 정보를 외부 syslog 서버로 보낼 수 있습니다. 외부 syslog 서버를 사용하면 감사 정보를 보다 쉽게 관리하고 네트워크 트래픽을 줄일 수 있습니다. 을 참조하십시오 xref:../monitor/configure-audit-messages.adoc[감사 메시지 및 로그 대상을 구성합니다] 를 참조하십시오.

감사 로그 파일, 감사 메시지 형식, 감사 메시지 유형 및 감사 메시지 분석에 사용할 수 있는 도구에 대한 자세한 내용은 을 참조하십시오 xref:../audit/index.adoc[감사 메시지에 대한 지침]. 감사 클라이언트 액세스를 구성하는 방법에 대한 자세한 내용은 을 참조하십시오 xref:../admin/configuring-audit-client-access.adoc[감사 클라이언트 액세스를 구성합니다].

.관련 정보
* xref:../audit/index.adoc[감사 로그를 검토합니다]
* xref:../admin/index.adoc[StorageGRID 관리]

