---
permalink: sg5700/troubleshooting-connection-issues.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, connection 
summary: StorageGRID 어플라이언스 설치 중에 연결 문제가 발생하면 나열된 수정 조치 단계를 수행해야 합니다. 
---
= 연결 문제 해결(SG5700)
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 어플라이언스 설치 중에 연결 문제가 발생하면 나열된 수정 조치 단계를 수행해야 합니다.



== 제품에 연결할 수 없습니다

어플라이언스에 연결할 수 없는 경우 네트워크 문제가 있거나 하드웨어 설치가 성공적으로 완료되지 않았을 수 있습니다.

.단계
. SANtricity 시스템 관리자에 연결할 수 없는 경우:
+
.. SANtricity 시스템 관리자의 관리 네트워크에 있는 E2800 컨트롤러의 IP 주소를 사용하여 어플라이언스에 ping을 시도합니다(+'* ping_E2800_Controller_IP_ * ')
.. Ping에서 응답이 없는 경우 올바른 IP 주소를 사용하고 있는지 확인합니다.
+
E2800 컨트롤러의 관리 포트 1의 IP 주소를 사용합니다.

.. IP 주소가 올바른 경우 어플라이언스 케이블 연결 및 네트워크 설정을 확인하십시오.
+
그래도 문제가 해결되지 않으면 기술 지원 부서에 문의하십시오.

.. Ping에 성공하면 웹 브라우저를 엽니다.
.. SANtricity 시스템 관리자의 URL을 입력합니다: + ``https://_E2800_Controller_IP_*`
+
SANtricity 시스템 관리자의 로그인 페이지가 나타납니다.



. E5500SG 컨트롤러에 연결할 수 없는 경우:
+
.. E5500SG 컨트롤러의 IP 주소를 사용하여 어플라이언스에 ping을 시도합니다. + " * PING_E700SG_Controller_IP_ * "
.. Ping에서 응답이 없는 경우 올바른 IP 주소를 사용하고 있는지 확인합니다.
+
그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크에서 어플라이언스의 IP 주소를 사용할 수 있습니다.

.. IP 주소가 올바른 경우 어플라이언스 케이블 연결, SFP 트랜시버 및 네트워크 설정을 확인하십시오.
+
그래도 문제가 해결되지 않으면 기술 지원 부서에 문의하십시오.

.. Ping에 성공하면 웹 브라우저를 엽니다.
.. StorageGRID 어플라이언스 설치 프로그램의 URL을 입력합니다. + ``https://_E5700SG_Controller_IP_:8443*`
+
홈 페이지가 나타납니다.




