---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 확장 절차를 통해 새 관리 노드를 추가하면 AMS 서비스는 시스템에 연결된 후에 발생하는 이벤트 및 동작만 기록합니다. 필요에 따라 이전에 설치된 관리 노드에서 새 확장 관리 노드로 감사 로그를 복사하여 나머지 StorageGRID 시스템과 동기화할 수 있습니다. 
---
= 감사 로그를 복사합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 절차를 통해 새 관리 노드를 추가하면 AMS 서비스는 시스템에 연결된 후에 발생하는 이벤트 및 동작만 기록합니다. 필요에 따라 이전에 설치된 관리 노드에서 새 확장 관리 노드로 감사 로그를 복사하여 나머지 StorageGRID 시스템과 동기화할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 관리자 노드를 추가하는 데 필요한 확장 단계를 완료했습니다.
* "passwords.txt" 파일이 있습니다.


새 관리 노드에서 기록 감사 메시지를 사용하려면 감사 로그 파일을 기존 관리 노드에서 확장 관리 노드로 수동으로 복사해야 합니다.

[NOTE]
====
기본적으로 감사 정보는 관리 노드의 감사 로그로 전송됩니다. 다음 중 하나가 적용되는 경우 이 단계를 건너뛸 수 있습니다.

* 외부 syslog 서버를 구성했으며 이제 감사 로그가 관리 노드 대신 syslog 서버로 전송됩니다.
* 감사 메시지를 생성한 로컬 노드에만 저장하도록 명시적으로 지정했습니다.


을 참조하십시오 xref:../monitor/configure-audit-messages.adoc[감사 메시지 및 로그 대상을 구성합니다] 를 참조하십시오.

====
.단계
. 기본 관리자 노드에 로그인합니다.
+
.. 'ssh_admin@_primary_Admin_Node_IP_' 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
.. 루트로 전환하려면 다음 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



. AMS 서비스를 중지하여 새 파일인 'Service AMS stop'을 생성하지 않도록 합니다
. "audit.log" 파일의 이름을 변경하여 복사할 확장 관리 노드의 파일을 덮어쓰지 않도록 합니다.
+
"cd /var/local/audit/export" + "ls-l" + mv audit.log_new_name_.txt"

. 모든 감사 로그 파일을 확장 관리 노드에 복사:
+
S CP-p * _IP_address_:/var/local/audit/export

. '/root/.ssh/id_rsa'에 대한 암호를 묻는 메시지가 나타나면 "passwords.txt" 파일에 나열된 운영 관리자 노드의 SSH 액세스 암호를 입력합니다.
. 원래 'audit.log' 파일 복구:
+
mv _new_name_.txt audit.log'입니다

. AMS 서비스를 시작합니다.
+
'서비스 AMS 시작

. 서버에서 로그아웃합니다.
+
종료

. 확장 관리 노드에 로그인합니다.
+
.. 'ssh admin@_expansion_Admin_Node_IP_' 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
.. 루트로 전환하려면 다음 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



. 감사 로그 파일에 대한 사용자 및 그룹 설정을 업데이트합니다.
+
'cd /var/local/audit/export' + 'chown AMS-user:bycast *'

. 서버에서 로그아웃합니다.
+
종료


