---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 경우에 따라 새 스토리지 노드를 추가한 후 삭제 코딩 데이터의 균형을 재조정해야 할 수 있습니다. 
---
= 스토리지 노드를 추가한 후 삭제 코딩 데이터의 균형을 재조정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
경우에 따라 새 스토리지 노드를 추가한 후 삭제 코딩 데이터의 균형을 재조정해야 할 수 있습니다.

.필요한 것
* 새 스토리지 노드를 추가하는 확장 단계를 완료했습니다.
* 을(를) 검토했습니다 xref:considerations-for-rebalancing-erasure-coded-data.adoc[삭제 코딩 데이터의 재조정에 대한 고려사항].
+

IMPORTANT: 사이트에서 하나 이상의 스토리지 노드에 대해 * Low Object Storage * 알림이 트리거되어 권장되는 수의 새 스토리지 노드를 추가할 수 없는 경우에만 이 절차를 수행하십시오.

* 복제된 오브젝트 데이터는 이 절차에 의해 이동되지 않으며 EC 재조정 절차에서는 삭제 코딩 데이터를 이동할 위치를 결정할 때 각 스토리지 노드에서 복제된 데이터 사용을 고려하지 않는다는 점을 이해합니다.
* "passwords.txt" 파일이 있습니다.


.이 작업에 대해
EC 재조정 절차가 실행 중이면 ILM 작업 및 S3 및 Swift 클라이언트 작업의 성능에 영향을 줄 수 있습니다. 따라서 이 절차는 제한된 경우에만 수행해야 합니다.


NOTE: EC 재조정 절차는 많은 양의 스토리지를 임시로 예약합니다. 스토리지 알림이 트리거될 수 있지만 재조정이 완료되면 문제가 해결됩니다. 예약 저장 공간이 충분하지 않으면 EC 재조정 절차가 실패합니다. EC 재조정 절차가 완료되면 절차가 실패했는지 여부에 관계없이 스토리지 예약이 해제됩니다.

[NOTE]
====
EC 재조정 절차 중에 완료하는 데 24시간 이상이 필요한 경우 S3 및 Swift API 작업으로 오브젝트(또는 오브젝트 부분)가 업로드되지 않을 수 있습니다. 해당 ILM 규칙이 수집 시 Strict 또는 Balanced 배치를 사용하는 경우 장기 PUT 작업이 실패합니다. 다음 오류가 보고됩니다.

'500 내부 서버 오류'

====
.단계
. [[review_object_storage]] 재조정할 사이트의 현재 오브젝트 스토리지 세부 정보를 검토합니다.
+
.. 노드 * 를 선택합니다.
.. 사이트에서 첫 번째 스토리지 노드를 선택합니다.
.. Storage * 탭을 선택합니다.
.. Storage Used-Object Data 차트 위에 커서를 올려 놓으면 스토리지 노드에서 복제된 데이터의 현재 양과 삭제 코딩 데이터를 확인할 수 있습니다.
.. 사이트에서 다른 스토리지 노드를 보려면 다음 단계를 반복합니다.


. 기본 관리자 노드에 로그인합니다.
+
.. 'ssh admin@_primary_Admin_Node_IP_' 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
.. 루트로 전환하려면 다음 명령을 입력합니다
.. "passwords.txt" 파일에 나열된 암호를 입력합니다.
+
루트로 로그인하면 프롬프트가 '$'에서 '#'로 바뀝니다.



. 다음 명령을 입력합니다.
+
rebalance-data start--site "_site-name_""

+
""_site-name_""에 새 스토리지 노드를 추가한 첫 번째 사이트를 지정합니다. 인용문에는 사인을 묶습니다.

+
EC 재조정 절차가 시작되고 작업 ID가 반환됩니다.

. 작업 ID를 복사합니다.
. EC 재조정 절차의 상태를 모니터링합니다.
+
** 단일 EC 재조정 절차의 상태를 보려면
+
rebalance-data status--job-id_job-id_'

+
'_job-id_'의 경우 절차를 시작할 때 반환된 ID를 지정합니다.

** 현재 EC 재조정 절차 및 이전에 완료된 절차의 상태를 보려면
+
rebalance-data status

+
[NOTE]
====
rebalance-data 명령에 대한 도움말을 보려면 다음을 수행합니다.

rebalance-data-help를 선택합니다

====
** 현재 작업의 예상 완료 시간과 완료 비율을 보려면 * 지원 * > * 도구 * > * 메트릭 * 을 선택합니다. 그런 다음 Grafana 섹션에서 * EC 개요 * 를 선택합니다. Grid EC Job Ec Job Estimated Time to Completion * 및 * Grid EC Job Percentage Completed * 대시보드를 확인합니다.


. 반환된 상태에 따라 추가 단계를 수행합니다.
+
** 상태가 '진행 중'인 경우 EC 재조정 작업이 계속 실행되고 있는 것입니다. 절차가 완료될 때까지 주기적으로 모니터링해야 합니다.
** 상태가 "실패"인 경우 를 수행합니다 <<rebalance_fail,실패 단계>>.
** 상태가 '성공'이면 를 수행합니다 <<rebalance_succeed,성공 단계>>.


. EC 균형 조정 절차에서 너무 많은 로드가 생성되는 경우(예: 수집 작업이 영향을 받음) 절차를 일시 중지하십시오.
+
rebalance-data pause--job-id_job-id_'

. EC 재조정 절차를 종료해야 하는 경우(예: StorageGRID 소프트웨어 업그레이드 수행) 다음을 입력합니다.
+
rebalance-data terminate--job-id_job-id_'를 선택합니다

+

NOTE: EC 재조정 절차를 종료할 때 이미 이동된 데이터 조각은 새 위치에 그대로 남아 있습니다. 데이터가 원래 위치로 다시 이동되지 않습니다.

. [[rebalance_fail]] EC rebalance procedure의 상태가 'Failure'인 경우, 다음 단계를 따른다.
+
.. 사이트의 모든 스토리지 노드가 그리드에 연결되어 있는지 확인합니다.
.. 이러한 스토리지 노드에 영향을 줄 수 있는 알림을 확인하고 해결합니다.
+
특정 경고에 대한 자세한 내용은 모니터링 및 문제 해결 지침을 참조하십시오.

.. EC 재조정 절차(+ rebalance-data start–-job-id_job-id_')를 다시 시작합니다
.. EC 재조정 절차의 상태가 여전히 "실패"인 경우 기술 지원 부서에 문의하십시오.


. [[rebalance_success] ([재조정_성공]) EC 재조정 절차의 상태가 '성공'(선택 사항)인 경우 <<review_object_storage,오브젝트 스토리지 검토>> 사이트에 대한 업데이트된 세부 정보를 봅니다.
+
이제 삭제 코딩 데이터가 사이트의 스토리지 노드 간에 더 균형 있게 균형 있게 조정되어야 합니다.

. 둘 이상의 사이트에서 삭제 코딩을 사용하는 경우 영향을 받는 다른 모든 사이트에 대해 이 절차를 실행합니다.

