---
permalink: ilm/advantages-disadvantages-and-requirements-for-ec.html 
sidebar: sidebar 
keywords: erasure coding advantages, disadvantages, EC requirements 
summary: 오브젝트 데이터의 손실로부터 보호하기 위해 복제 또는 삭제 코딩을 사용할지 결정하기 전에 삭제 코딩의 장점, 단점 및 요구 사항을 이해해야 합니다. 
---
= 삭제 코딩의 장점, 단점 및 요구 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
오브젝트 데이터의 손실로부터 보호하기 위해 복제 또는 삭제 코딩을 사용할지 결정하기 전에 삭제 코딩의 장점, 단점 및 요구 사항을 이해해야 합니다.



== 삭제 코딩의 장점

삭제 코딩은 복제와 비교할 때 안정성, 가용성 및 스토리지 효율성을 향상시킵니다.

* * 안정성 *: 신뢰성은 내결함성의 관점에서 측정되며, 즉 데이터 손실 없이 동시에 장애가 발생할 수 있는 횟수를 나타냅니다. 복제를 사용하면 동일한 여러 복사본이 여러 노드와 사이트 전체에 저장됩니다. 삭제 코딩을 사용하면 오브젝트는 데이터 및 패리티 조각으로 인코딩되어 여러 노드와 사이트에 분산됩니다. 이 분산은 사이트 및 노드 장애 보호를 모두 제공합니다. 복제와 비교할 때 삭제 코딩은 비슷한 스토리지 비용으로 향상된 안정성을 제공합니다.
* * 가용성 *: 스토리지 노드에 장애가 발생하거나 액세스할 수 없는 경우 객체를 검색하는 기능으로 가용성을 정의할 수 있습니다. 복제와 비교할 때 삭제 코딩은 비슷한 스토리지 비용으로 향상된 가용성을 제공합니다.
* * 스토리지 효율성 *: 유사한 수준의 가용성과 안정성을 위해 삭제 코딩을 통해 보호되는 오브젝트는 복제를 통해 보호될 경우 동일한 오브젝트보다 더 적은 디스크 공간을 사용합니다. 예를 들어, 두 개의 사이트에 복제된 10MB 오브젝트는 20MB의 디스크 공간(복사본 2개)을 사용하지만 삭제 코딩 구성표 6+3을 사용하여 세 사이트에서 삭제 코딩되는 오브젝트는 15MB의 디스크 공간만 사용합니다.
+

NOTE: 삭제 코딩 오브젝트를 위한 디스크 공간은 오브젝트 크기와 스토리지 오버헤드로 계산됩니다. 스토리지 오버헤드 비율은 패리티 조각 수를 데이터 조각 수로 나눈 값입니다.





== 삭제 코딩의 단점

복제와 비교할 때 삭제 코딩에는 다음과 같은 단점이 있습니다.

* 스토리지 노드 및 사이트의 수가 증가해야 합니다. 예를 들어, 삭제 코딩 구성표 6+3을 사용하는 경우 3개의 다른 사이트에 3개 이상의 스토리지 노드가 있어야 합니다. 반면, 오브젝트 데이터만 복제하면 각 복제본마다 스토리지 노드가 하나만 필요합니다.
* 스토리지 확장의 비용 및 복잡성 증가 복제를 사용하는 배포를 확장하려면 개체 복사본이 만들어지는 모든 위치에 스토리지 용량을 추가하기만 하면 됩니다. 삭제 코딩을 사용하는 배포를 확장하려면 사용 중인 삭제 코딩 체계와 기존 스토리지 노드의 전체 용량을 고려해야 합니다. 예를 들어 기존 노드가 100% 꽉 찰 때까지 기다리는 경우 최소한 _k+m_스토리지 노드를 추가해야 하지만 기존 노드가 70% 가득 찬 경우 사이트 당 두 개의 노드를 추가하여 가용 스토리지 용량을 최대화할 수 있습니다. 자세한 내용은 을 참조하십시오 xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[삭제 코딩 오브젝트를 위한 스토리지 용량을 추가합니다].
* 지리적으로 분산된 사이트에서 삭제 코딩을 사용하면 검색 지연 시간이 늘어납니다. 원격 사이트에 삭제 코딩되고 분산된 오브젝트의 오브젝트 조각은 로컬에서 복제 및 사용할 수 있는 오브젝트(클라이언트가 연결하는 동일한 사이트)보다 WAN 연결을 통해 검색하는 데 시간이 더 오래 걸립니다.
* 지리적으로 분산된 사이트에서 삭제 코딩을 사용하는 경우 검색 및 복구를 위해 WAN 네트워크 트래픽 사용량이 증가하고, 특히 자주 검색하는 오브젝트 또는 WAN 네트워크 연결을 통한 오브젝트 복구에서 더욱 그렇습니다.
* 여러 사이트에서 삭제 코딩을 사용하면 사이트 간의 네트워크 지연 시간이 증가함에 따라 최대 오브젝트 처리량이 급격히 줄어듭니다. 이러한 감소는 StorageGRID 시스템이 개체 조각을 저장하고 검색하는 데 영향을 미치는 TCP 네트워크 처리량이 감소하기 때문입니다.
* 컴퓨팅 리소스 사용량 증가.




== 삭제 코딩 사용 시기

삭제 코딩은 다음 요구사항에 가장 적합합니다.

* 크기가 1MB를 초과하는 객체
+

IMPORTANT: 삭제 코딩은 1MB 이상의 오브젝트에 가장 적합합니다. 매우 작은 삭제 코딩 조각을 관리해야 하는 오버헤드를 방지하기 위해 200KB 미만의 오브젝트에 삭제 코딩을 사용하지 마십시오.

* 자주 검색되지 않는 콘텐츠의 장기 또는 콜드 스토리지
* 높은 데이터 가용성 및 안정성
* 전체 사이트 및 노드 장애로부터 보호
* 스토리지 효율성:
* 여러 개의 복제된 복사본이 아닌 하나의 삭제 코딩 복사본만으로 효율적인 데이터 보호가 필요한 단일 사이트 배포
* 사이트 간 지연 시간이 100ms 미만인 다중 사이트 구축

