---
permalink: ilm/creating-ilm-policy.html 
sidebar: sidebar 
keywords: create ILM policy, information lifecycle policy considerations 
summary: ILM 정책을 만들 때는 먼저 ILM 규칙을 선택하고 정렬해야 합니다. 그런 다음 이전에 수집된 개체에 대해 제안된 정책을 시뮬레이션하여 해당 정책의 동작을 확인합니다. 제안된 정책이 의도한 대로 작동하고 있다고 만족하면 이를 활성화하여 활성 정책을 생성할 수 있습니다. 
---
= ILM 정책 생성: 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 정책을 만들 때는 먼저 ILM 규칙을 선택하고 정렬해야 합니다. 그런 다음 이전에 수집된 개체에 대해 제안된 정책을 시뮬레이션하여 해당 정책의 동작을 확인합니다. 제안된 정책이 의도한 대로 작동하고 있다고 만족하면 이를 활성화하여 활성 정책을 생성할 수 있습니다.


CAUTION: 잘못 구성된 ILM 정책으로 인해 복구할 수 없는 데이터 손실이 발생할 수 있습니다. ILM 정책을 활성화하기 전에 ILM 정책 및 ILM 규칙을 주의 깊게 검토한 다음 ILM 정책을 시뮬레이션합니다. ILM 정책이 의도한 대로 작동할 것인지 항상 확인하십시오.



== ILM 정책을 생성할 때의 고려 사항

* 테스트 시스템에서만 시스템의 기본 제공 정책인 Baseline 2 Copies 정책을 사용합니다. 이 정책의 복사본 2개 만들기 규칙은 모든 사이트가 포함된 모든 스토리지 노드 스토리지 풀을 사용합니다. StorageGRID 시스템에 사이트가 두 개 이상 있는 경우 한 개체의 복사본을 같은 사이트에 둘 수 있습니다.
* 새 정책을 설계할 때는 그리드에 인제스트될 수 있는 다양한 유형의 모든 객체를 고려하십시오. 정책에 이러한 개체를 일치시키고 필요한 경우 배치할 규칙이 포함되어 있는지 확인합니다.
* ILM 정책을 최대한 단순하게 유지하십시오. 이렇게 하면 시간이 지남에 따라 StorageGRID 시스템을 변경할 때 의도된 대로 오브젝트 데이터가 보호되지 않는 잠재적으로 위험한 상황을 방지할 수 있습니다.
* 정책의 규칙이 올바른 순서로 되어 있는지 확인합니다. 정책이 활성화되면 위에서 시작하여 나열된 순서대로 새 개체와 기존 개체가 평가됩니다. 예를 들어 정책의 첫 번째 규칙이 개체와 일치하면 다른 규칙이 해당 규칙을 평가하지 않습니다.
* 모든 ILM 정책의 마지막 규칙은 필터를 사용할 수 없는 기본 ILM 규칙입니다. 개체가 다른 규칙과 일치하지 않으면 기본 규칙은 개체가 배치된 위치와 유지되는 기간을 제어합니다.
* 새 정책을 활성화하기 전에 정책이 기존 개체의 배치에 대해 적용하는 모든 변경 사항을 검토하십시오. 기존 오브젝트의 위치를 변경하면 새로운 배치가 평가되고 구현될 때 일시적인 리소스 문제가 발생할 수 있습니다.

