---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: 스토리지 풀을 편집하여 이름을 변경하거나 사이트 및 스토리지 등급을 업데이트할 수 있습니다. 
---
= 스토리지 풀을 편집합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀을 편집하여 이름을 변경하거나 사이트 및 스토리지 등급을 업데이트할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 를 사용하여 그리드 관리자에 로그인했습니다 xref:../admin/web-browser-requirements.adoc[지원되는 웹 브라우저].
* 특정 액세스 권한이 있습니다.
* 스토리지 풀 생성에 대한 지침을 검토했습니다.
* 활성 ILM 정책의 규칙에 의해 사용되는 스토리지 풀을 편집하려는 경우 변경 사항이 개체 데이터 배치에 미치는 영향을 고려했습니다.


활성 ILM 정책에 사용되는 스토리지 풀에 새 스토리지 등급을 추가하는 경우 새 스토리지 등급의 스토리지 노드가 자동으로 사용되지 않는다는 점에 유의하십시오. StorageGRID에서 새 스토리지 등급을 사용하도록 강제하려면 편집된 스토리지 풀을 저장한 후 새 ILM 정책을 활성화해야 합니다.

.단계
. ILM * > * 스토리지 풀 * 을 선택합니다.
+
스토리지 풀 페이지가 나타납니다.

. 편집할 스토리지 풀의 라디오 버튼을 선택합니다.
+
모든 스토리지 노드 스토리지 풀은 편집할 수 없습니다.

. 편집 * 을 선택합니다.
. 필요에 따라 스토리지 풀 이름을 변경합니다.
. 필요에 따라 다른 사이트 및 저장 등급을 선택합니다.
+

NOTE: 스토리지 풀이 삭제 코딩 프로필에 사용되고 변경 시 삭제 코딩 체계가 유효하지 않게 되는 경우 사이트 또는 스토리지 등급을 변경할 수 없습니다. 예를 들어, 삭제 코딩 프로필에 사용된 스토리지 풀에 현재 사이트가 하나뿐인 스토리지 평점이 포함되어 있는 경우 삭제 코딩 체계가 유효하지 않게 되므로 두 개의 사이트에 스토리지 평점을 사용할 수 없습니다.

. 저장 * 을 선택합니다.


활성 ILM 정책에 사용된 스토리지 풀에 새 스토리지 등급을 추가한 경우 새 ILM 정책을 활성화하여 StorageGRID이 새 스토리지 등급을 사용하도록 강제합니다. 예를 들어, 기존 ILM 정책을 클론 복제한 다음 클론을 활성화합니다.
