---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 스토리지 풀을 구성 및 사용할 때는 다음 지침을 따르십시오. 
---
= 스토리지 풀 생성 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀을 구성 및 사용할 때는 다음 지침을 따르십시오.



== 모든 스토리지 풀에 대한 지침입니다

* StorageGRID에는 기본 사이트, 모든 사이트 및 기본 스토리지 등급인 모든 스토리지 노드를 사용하는 기본 스토리지 풀인 모든 스토리지 노드가 포함됩니다. 새 데이터 센터 사이트를 추가할 때마다 모든 스토리지 노드 스토리지 풀이 자동으로 업데이트됩니다.
+

NOTE: 모든 스토리지 노드 스토리지 풀 또는 모든 사이트 사이트를 사용하는 것은 권장되지 않습니다. 이러한 항목은 확장에 추가한 새 사이트를 포함하도록 자동으로 업데이트되기 때문에 원하는 동작이 아닐 수 있습니다. 모든 스토리지 노드 스토리지 풀 또는 기본 사이트를 사용하기 전에 복제된 복사본 및 삭제 코딩 복사본에 대한 지침을 주의 깊게 검토하십시오.

* 스토리지 풀 구성을 가능한 한 단순하게 유지합니다. 필요한 것보다 더 많은 스토리지 풀을 생성하지 마십시오.
* 가능한 한 많은 노드를 포함하는 스토리지 풀을 생성합니다. 각 스토리지 풀에는 둘 이상의 노드가 포함되어야 합니다. 노드가 부족한 스토리지 풀은 노드를 사용할 수 없게 될 경우 ILM 백로그를 유발할 수 있습니다.
* 중복되는 스토리지 풀을 생성하거나 사용하지 마십시오(동일한 노드 중 하나 이상 포함). 스토리지 풀이 중복될 경우 오브젝트 데이터의 복제본이 동일한 노드에 저장될 수 있습니다.




== 복제된 복제본에 사용되는 스토리지 풀에 대한 지침입니다

* 각 사이트에 대해 다른 스토리지 풀을 생성합니다. 그런 다음 각 규칙의 배치 지침에 하나 이상의 사이트별 스토리지 풀을 지정합니다. 각 사이트에 스토리지 풀을 사용하면 복제된 개체 복사본이 원하는 위치에 정확하게 배치됩니다. 예를 들어, 사이트 손실 방지를 위해 각 사이트에 있는 모든 개체의 복사본이 하나씩 배치됩니다.
* 확장 시 사이트를 추가하는 경우 새 사이트의 새 스토리지 풀을 생성합니다. 그런 다음 ILM 규칙을 업데이트하여 새 사이트에 저장된 개체를 제어합니다.
* 일반적으로 기본 스토리지 풀, 모든 스토리지 노드 또는 기본 사이트, 모든 사이트를 포함하는 스토리지 풀을 사용하지 마십시오.




== 삭제 코딩 복사본에 사용되는 스토리지 풀에 대한 지침입니다

* 삭제 코딩 데이터에는 아카이브 노드를 사용할 수 없습니다.
* 스토리지 풀에 포함된 스토리지 노드 및 사이트의 수에 따라 사용 가능한 삭제 코딩 체계가 결정됩니다.
* 스토리지 풀에 사이트가 두 개만 포함된 경우 해당 스토리지 풀을 삭제 코딩에 사용할 수 없습니다. 두 개의 사이트가 있는 스토리지 풀에는 삭제 코딩 스키마를 사용할 수 없습니다.
* 일반적으로 기본 스토리지 풀, 모든 스토리지 노드 또는 기본 사이트, 삭제 코딩 프로필의 모든 사이트를 포함하는 스토리지 풀을 사용하지 마십시오.
+

NOTE: 그리드에 사이트가 하나만 포함된 경우 모든 스토리지 노드 스토리지 풀 또는 모든 사이트 기본 사이트를 삭제 코딩 프로파일에서 사용할 수 없습니다. 이 동작은 두 번째 사이트가 추가된 경우 삭제 코딩 프로필이 무효로 되는 것을 방지합니다.

* 처리량이 많은 경우 사이트 간 네트워크 지연 시간이 100ms를 초과하는 경우 여러 사이트를 포함하는 스토리지 풀을 생성하지 않는 것이 좋습니다. 지연 시간이 늘어날수록 StorageGRID에서 TCP 네트워크 처리량이 감소하기 때문에 개체 조각을 생성, 배치 및 검색할 수 있는 속도가 급격하게 줄어듭니다. 처리량 감소는 오브젝트 수집 및 검색의 최대 달성 가능 속도(Ingest 동작으로 Strict 또는 Balanced를 선택한 경우)에 영향을 미치거나 ILM 대기열 백로그(Ingest 동작으로 이중 커밋을 선택한 경우)로 이어질 수 있습니다.
* 가능한 경우 스토리지 풀에 선택한 삭제 코딩 체계에 필요한 최소 스토리지 노드 수보다 많은 수가 포함되어야 합니다. 예를 들어, 6+3 삭제 코딩 체계를 사용하는 경우 9개 이상의 스토리지 노드가 있어야 합니다. 그러나 사이트당 스토리지 노드를 하나 이상 추가하는 것이 좋습니다.
* 가능한 한 사이트 간에 스토리지 노드를 균등하게 분산합니다. 예를 들어, 6+3 삭제 코딩 체계를 지원하려면 세 개 사이트에 세 개 이상의 스토리지 노드를 포함하는 스토리지 풀을 구성합니다.




== 아카이빙된 복제본에 사용되는 스토리지 풀에 대한 지침입니다

* 스토리지 노드와 아카이브 노드를 모두 포함하는 스토리지 풀은 생성할 수 없습니다. 아카이빙된 복제본에는 아카이브 노드만 포함된 스토리지 풀이 필요합니다.
* 아카이브 노드가 포함된 스토리지 풀을 사용하는 경우 스토리지 노드가 포함된 스토리지 풀에서 하나 이상의 복제된 복사본 또는 삭제 코딩 복사본도 유지 관리해야 합니다.
* 글로벌 S3 오브젝트 잠금 설정이 활성화되어 있고 호환되는 ILM 규칙을 생성하는 경우 아카이브 노드가 포함된 스토리지 풀을 사용할 수 없습니다. S3 오브젝트 잠금을 사용하여 오브젝트를 관리하는 지침을 참조하십시오.
* 아카이브 노드의 타겟 유형이 Cloud Tiering - Simple Storage Service(S3)인 경우 아카이브 노드는 자체 스토리지 풀에 있어야 합니다. 을 참조하십시오 xref:../admin/index.adoc[StorageGRID 관리].


.관련 정보
* xref:what-replication-is.adoc[복제란]
* xref:what-erasure-coding-is.adoc[삭제 코딩이란 무엇입니까]
* xref:what-erasure-coding-schemes-are.adoc[어떤 삭제 코딩 구성인지]
* xref:using-multiple-storage-pools-for-cross-site-replication.adoc[사이트 간 복제에 여러 스토리지 풀을 사용합니다]

