---
permalink: fabricpool/best-practices-for-load-balancing.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, Layer 7, cloud tier, best practices 
summary: StorageGRID를 FabricPool 클라우드 계층으로 연결하기 전에 StorageGRID 그리드 관리자를 사용하여 하나 이상의 로드 밸런서 끝점을 구성해야 합니다. 
---
= 로드 밸런싱에 대한 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID를 FabricPool 클라우드 계층으로 연결하기 전에 StorageGRID 그리드 관리자를 사용하여 하나 이상의 로드 밸런서 끝점을 구성해야 합니다.



== 로드 밸런싱이란 무엇입니까?

데이터가 FabricPool에서 StorageGRID 시스템으로 계층화되면 StorageGRID는 로드 밸런서를 사용하여 수집 및 검색 워크로드를 관리합니다. 로드 밸런싱은 여러 스토리지 노드에 FabricPool 워크로드를 분산하여 속도와 연결 용량을 극대화합니다.

StorageGRID 로드 밸런서 서비스는 모든 관리 노드 및 모든 게이트웨이 노드에 설치되며 계층 7 로드 밸런싱을 제공합니다. 클라이언트 요청에 대한 TLS(Transport Layer Security) 종료를 수행하고 요청을 검사하며 스토리지 노드에 대한 새로운 보안 연결을 설정합니다.

각 노드의 로드 밸런서 서비스는 클라이언트 트래픽을 스토리지 노드로 전달할 때 독립적으로 작동합니다. 로드 밸런서 서비스는 가중 프로세스를 통해 더 많은 요청을 CPU 가용성이 높은 스토리지 노드로 라우팅합니다.

StorageGRID 로드 밸런서 서비스가 권장되는 로드 밸런싱 메커니즘이지만 타사 로드 밸런서를 대신 통합할 수도 있습니다. 자세한 내용은 NetApp 어카운트 담당자에게 문의하거나 를 참조하십시오 https://["TR-4626: StorageGRID 타사 및 글로벌 로드 밸런서"^].


NOTE: 게이트웨이 노드의 별도의 CLB(연결 로드 밸런서) 서비스는 더 이상 사용되지 않으며 FabricPool에서 더 이상 사용하지 않는 것이 좋습니다.



== StorageGRID 로드 밸런싱에 대한 Best Practice

일반적으로 StorageGRID 시스템의 각 사이트에는 부하 분산 서비스가 있는 두 개 이상의 노드가 포함되어야 합니다. 예를 들어 사이트에는 두 개의 게이트웨이 노드 또는 관리 노드와 게이트웨이 노드가 모두 포함될 수 있습니다. SG100 또는 SG1000 서비스 어플라이언스, 베어 메탈 노드 또는 가상 머신(VM) 기반 노드를 사용 중이든, 각 로드 밸런싱 노드에 적절한 네트워킹, 하드웨어 또는 가상화 인프라가 있는지 확인하십시오.

게이트웨이 노드 및 관리 노드가 수신 및 발신 FabricPool 요청에 사용할 포트를 정의하려면 StorageGRID 로드 밸런서 끝점을 구성해야 합니다.



== 로드 밸런서 끝점 인증서에 대한 Best Practice

FabricPool와 함께 사용할 로드 밸런서 끝점을 만들 때는 HTTPS를 프로토콜로 사용해야 합니다. TLS 암호화 없이 StorageGRID와 통신하는 것은 지원되지만 권장되지 않습니다

그런 다음 공개적으로 신뢰할 수 있는 인증서나 개인 인증 기관(CA)에서 서명한 인증서를 업로드하거나 자체 서명된 인증서를 생성할 수 있습니다. 이 인증서를 통해 ONTAP는 StorageGRID를 사용하여 인증할 수 있습니다.

가장 좋은 방법은 CA 서버 인증서를 사용하여 연결을 보호하는 것입니다. CA에서 서명한 인증서는 중단 없이 회전할 수 있습니다.

로드 밸런서 끝점에서 사용할 CA 인증서를 요청할 때는 인증서의 도메인 이름이 해당 로드 밸런서 끝점에 대해 ONTAP에 입력한 서버 이름과 일치하는지 확인합니다. 가능한 경우 와일드카드(*)를 사용하여 가상 호스트 스타일 URL을 허용합니다. 예를 들면 다음과 같습니다.

[listing]
----
*.s3.storagegrid.company.com
----
StorageGRID를 FabricPool 클라우드 계층으로 추가하는 경우 루트 및 하위 CA(인증 기관) 인증서뿐만 아니라 ONTAP 클러스터에 동일한 인증서를 설치해야 합니다.


NOTE: StorageGRID는 여러 가지 목적으로 서버 인증서를 사용합니다. 로드 밸런서 서비스에 연결하는 경우 S3 및 Swift API 인증서를 선택적으로 사용할 수 있습니다.

로드 밸런싱 끝점의 서버 인증서에 대한 자세한 내용은 다음을 참조하십시오.

* xref:../admin/configuring-load-balancer-endpoints.adoc[로드 밸런서 엔드포인트를 구성합니다]
* xref:../harden/hardening-guideline-for-server-certificates.adoc[서버 인증서에 대한 강화 지침]

