---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: 'StorageGRID를 FabricPool 클라우드 계층으로 첨부하기 전에 StorageGRID 그리드 관리자를 사용하여 고가용성\(HA\) 그룹을 구성해야 합니다.' 
---
= 고가용성 그룹에 대한 Best Practice
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID를 FabricPool 클라우드 계층으로 연결하기 전에 StorageGRID 그리드 관리자를 사용하여 고가용성(HA) 그룹을 구성해야 합니다.



== 고가용성(HA) 그룹이란 무엇입니까?

로드 밸런서 서비스를 항상 사용하여 FabricPool 데이터를 관리할 수 있도록 여러 관리 및 게이트웨이 노드의 네트워크 인터페이스를 고가용성(HA) 그룹이라고 하는 단일 엔터티로 그룹화할 수 있습니다. HA 그룹의 액티브 노드에 장애가 발생할 경우 그룹의 다른 노드가 워크로드를 계속 관리할 수 있습니다.

각 HA 그룹은 연결된 노드의 공유 서비스에 대한 고가용성 액세스를 제공합니다. 예를 들어, 게이트웨이 노드에만 있거나 관리 노드와 게이트웨이 노드 모두에 있는 인터페이스로 구성된 HA 그룹은 공유 로드 밸런서 서비스에 대한 고가용성 액세스를 제공합니다.

HA 그룹을 생성하려면 다음 일반 단계를 수행합니다.

. 하나 이상의 관리 노드 또는 게이트웨이 노드에 대한 네트워크 인터페이스를 선택합니다. 그리드 네트워크 인터페이스(eth0), 클라이언트 네트워크 인터페이스(eth2) 또는 VLAN 인터페이스를 선택할 수 있습니다.
+

IMPORTANT: VLAN 인터페이스를 사용하여 FabricPool 트래픽을 분리하려는 경우 네트워크 관리자는 먼저 트렁크 인터페이스와 해당 VLAN을 구성해야 합니다. 각 VLAN은 숫자 ID 또는 태그로 식별됩니다. 예를 들어 네트워크에서 FabricPool 트래픽에 VLAN 100을 사용할 수 있습니다.

. 그룹에 하나 이상의 가상 IP(VIP) 주소를 할당합니다. FabricPool와 같은 클라이언트 응용 프로그램은 이러한 VIP 주소를 사용하여 StorageGRID에 연결할 수 있습니다.
. 기본 인터페이스로 사용할 인터페이스를 지정하고 백업 인터페이스의 우선 순위를 결정합니다. Primary 인터페이스는 장애가 발생하지 않는 한 Active 인터페이스입니다.


HA 그룹에 둘 이상의 인터페이스가 포함되어 있고 기본 인터페이스에 장애가 발생하면 VIP 주소가 우선 순위 순서대로 첫 번째 백업 인터페이스로 이동합니다. 이 인터페이스에 장애가 발생하면 VIP 주소가 다음 백업 인터페이스로 이동합니다. 이 장애 조치 프로세스는 일반적으로 몇 초 밖에 걸리지 않으며 클라이언트 응용 프로그램에 거의 영향을 주지 않고 정상적인 재시도 동작에 의존하여 작업을 계속할 수 있을 정도로 빠릅니다.

장애가 해결되고 더 높은 우선 순위 인터페이스를 다시 사용할 수 있게 되면 VIP 주소가 사용 가능한 가장 높은 우선 순위 인터페이스로 자동 이동됩니다.



== 고가용성(HA) 그룹에 대한 모범 사례

FabricPool용 StorageGRID HA 그룹을 생성하는 모범 사례는 다음과 같이 워크로드에 따라 다릅니다.

* 운영 워크로드 데이터에 FabricPool를 사용할 계획이라면 데이터 검색이 중단되지 않도록 최소 2개의 로드 밸런싱 노드를 포함하는 HA 그룹을 생성해야 합니다.
* FabricPool 스냅샷 전용 볼륨 계층화 정책 또는 비 운영 로컬 성능 계층(예: 재해 복구 위치 또는 NetApp SnapMirror ® 대상)을 사용하려는 경우 하나의 노드만 사용하여 HA 그룹을 구성할 수 있습니다.


다음 지침은 Active-Backup HA에 대한 HA 그룹 설정(한 노드는 활성 상태이고 한 노드는 백업)에 대해 설명합니다. 그러나 DNS 라운드 로빈 또는 Active-Active HA를 사용하는 것이 좋습니다. 이러한 기타 HA 구성의 이점에 대한 자세한 내용은 를 참조하십시오 xref:../admin/configuration-options-for-ha-groups.adoc[HA 그룹에 대한 구성 옵션].
