---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, best practices, encryption, compressions, tiering, AFF, consistency 
summary: FabricPool와 함께 사용하도록 StorageGRID 시스템을 구성할 때는 데이터 저장 방식에 영향을 줄 수 있는 전역 옵션을 설정하지 않아야 합니다. 
---
= 기타 StorageGRID 및 FabricPool 모범 사례
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool와 함께 사용하도록 StorageGRID 시스템을 구성할 때는 데이터 저장 방식에 영향을 줄 수 있는 전역 옵션을 설정하지 않아야 합니다.



== 오브젝트 암호화

StorageGRID를 구성할 때 다른 StorageGRID 클라이언트에 데이터 암호화가 필요한 경우 선택적으로 글로벌 * 저장된 개체 암호화 * 설정을 활성화할 수 있습니다(* 구성 * > * 시스템 * > * 그리드 옵션 *). FabricPool에서 StorageGRID로 계층화된 데이터는 이미 암호화되므로 StorageGRID 설정을 활성화할 필요가 없습니다. 클라이언트측 암호화 키는 ONTAP의 소유입니다.



== 오브젝트 압축

StorageGRID를 구성할 때 전역 * 저장된 개체 압축 * 설정을 사용하지 마십시오(* 구성 * > * 시스템 * > * 그리드 옵션 *). FabricPool에서 StorageGRID로 계층화된 데이터는 이미 압축된 상태입니다. 저장된 개체 압축 * 을 사용하면 개체의 크기가 더 작아지지 않습니다.



== 정합성 보장 레벨

FabricPool 버킷의 경우 권장되는 버킷 정합성 수준은 "재기록 후"입니다. "사용 가능" 정합성 수준은 권장되지 않습니다. 을 참조하십시오 xref:../tenant/changing-consistency-level.adoc[정합성 보장 수준을 변경합니다].



== FabricPool 계층화

StorageGRID 노드에서 NetApp AFF 시스템에서 할당된 스토리지를 사용하는 경우 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않은지 확인합니다. 예를 들어 StorageGRID 노드가 VMware 호스트에서 실행 중인 경우 StorageGRID 노드의 데이터 저장소를 백업하는 볼륨에 FabricPool 계층화 정책이 설정되어 있지 않은지 확인합니다. StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 사용하지 않도록 설정하면 문제 해결과 스토리지 작업이 간소화됩니다.


IMPORTANT: FabricPool를 사용하여 StorageGRID 관련 데이터를 StorageGRID 자체로 계층화하지 마십시오. StorageGRID 데이터를 StorageGRID로 다시 계층화하면 문제 해결과 운영 복잡성이 늘어납니다.
