---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: 'FabricPool를 사용하여 데이터를 StorageGRID에 계층화하려는 경우 StorageGRID 정보 라이프사이클 관리\(ILM\) 규칙을 만들기 위한 요구사항과 FabricPool 데이터 관리를 위한 ILM 정책을 이해해야 합니다. FabricPool 데이터에 적용되는 ILM 규칙이 중단되지 않도록 해야 합니다.' 
---
= FabricPool 데이터에 StorageGRID 정보 수명 주기 관리 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool를 사용하여 데이터를 StorageGRID에 계층화하려는 경우 StorageGRID ILM(정보 수명 주기 관리) 규칙을 생성하기 위한 요구사항과 FabricPool 데이터를 관리하기 위한 ILM 정책을 이해해야 합니다. FabricPool 데이터에 적용되는 ILM 규칙이 중단되지 않도록 해야 합니다.


IMPORTANT: FabricPool에는 StorageGRID ILM 규칙 또는 정책에 대한 지식이 없습니다. StorageGRID ILM 정책이 잘못 구성된 경우 데이터 손실이 발생할 수 있습니다. 을 참조하십시오 xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다] 자세한 ILM 지침을 참조하십시오.

ILM 규칙 및 ILM 정책이 FabricPool 데이터 및 비즈니스 요구 사항에 적합한지 확인하려면 다음 지침을 검토하십시오. StorageGRID ILM을 이미 사용 중인 경우 이러한 지침을 충족하기 위해 활성 ILM 정책을 업데이트해야 할 수 있습니다.

* 복제 및 삭제 코딩 규칙을 조합하여 클라우드 계층 데이터를 보호할 수 있습니다.
+
가장 권장되는 모범 사례는 비용 효율적인 데이터 보호를 위해 사이트 내에서 2+1 삭제 코딩을 사용하는 것입니다. 삭제 코딩은 더 많은 CPU를 사용하지만 복제에 비해 스토리지 용량이 훨씬 적습니다. 4+1 및 6+1 구성표는 2+1 구성표보다 적은 용량을 사용합니다. 그러나 그리드 확장 중에 스토리지 노드를 추가해야 하는 경우 4+1 및 6+1 구성표는 유연하지 않습니다. 자세한 내용은 을 참조하십시오 xref:../expand/adding-storage-capacity-for-erasure-coded-objects.adoc[삭제 코딩 오브젝트를 위한 스토리지 용량을 추가합니다].

* FabricPool 데이터에 적용되는 각 규칙은 삭제 코딩을 사용하거나 적어도 두 개의 복제된 복사본을 만들어야 합니다.
+

IMPORTANT: 특정 기간 동안 복제된 복사본을 하나만 생성하는 ILM 규칙은 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.

* FabricPool 클라우드 계층 데이터가 만료되거나 삭제될 ILM 규칙을 사용하지 마십시오. 각 ILM 규칙의 보존 기간을 "Forever"로 설정하여 StorageGRID ILM에서 FabricPool 개체가 삭제되지 않도록 합니다.
* FabricPool 클라우드 계층 데이터를 버킷에서 다른 위치로 이동할 규칙을 만들지 마십시오. ILM 규칙을 사용하여 아카이브 노드를 사용하여 FabricPool 데이터를 테이프에 아카이빙하거나 클라우드 스토리지 풀을 사용하여 FabricPool 데이터를 다른 오브젝트 저장소로 이동할 수 없습니다.
+

NOTE: FabricPool에서 클라우드 스토리지 풀 타겟의 객체를 검색하는 지연 시간이 추가되었기 때문에 클라우드 스토리지 풀을 사용할 수 없습니다.

* ONTAP 9.8부터 객체 태그를 생성하여 계층형 데이터를 쉽게 분류하고 정렬할 수 있습니다. 예를 들어, StorageGRID에 연결된 FabricPool 볼륨에만 태그를 설정할 수 있습니다. 그런 다음 StorageGRID에서 ILM 규칙을 만들 때 개체 태그 고급 필터를 사용하여 이 데이터를 선택하고 배치할 수 있습니다.




== FabricPool 데이터에 대한 ILM 정책의 예

이 간단한 예제 정책을 자신의 ILM 규칙 및 정책의 시작 지점으로 사용합니다.

이 예제에서는 콜로라도주 덴버의 단일 데이터 센터에 4개의 스토리지 노드가 있는 StorageGRID 시스템에 대한 ILM 규칙 및 ILM 정책을 디자인한다고 가정합니다. 이 예의 FabricPool 데이터는 '배풀버킷'이라는 이름의 버킷을 사용합니다.


CAUTION: 다음 ILM 규칙 및 정책은 예일 뿐입니다. ILM 규칙을 구성하는 방법은 여러 가지가 있습니다. 새 정책을 활성화하기 전에 제안된 정책을 시뮬레이션하여 콘텐츠가 손실로부터 보호되도록 의도한 대로 동작하는지 확인합니다. 자세한 내용은 을 참조하십시오 xref:../ilm/index.adoc[ILM을 사용하여 개체를 관리합니다].

.단계
. 이름이 * den * 인 스토리지 풀을 생성합니다. 덴버 사이트를 선택합니다.
. 이름이 * 2와 1 * 인 삭제 코딩 프로필을 만듭니다. 2+1 삭제 코딩 체계와 * den * 스토리지 풀을 선택합니다.
. 'fabricpool-bucket'의 데이터에만 적용되는 ILM 규칙을 생성합니다. 이 예제 규칙은 삭제 코딩 복사본을 만듭니다.
+
[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
FabricPool 데이터에 2개 이상의 삭제 코딩



 a| 
버킷 이름
 a| 
배합통

FabricPool 테넌트 계정에서도 필터링할 수 있습니다.



 a| 
고급 필터링
 a| 
객체 크기(MB)가 0.2 MB를 초과합니다.

* 참고: * FabricPool는 4MB 객체만 쓰지만 이 규칙은 삭제 코딩을 사용하므로 객체 크기 필터를 추가해야 합니다.



 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
0일째부터 영원히



 a| 
유형
 a| 
삭제 코딩



 a| 
위치
 a| 
DEN(2 + 1)



 a| 
수집 동작
 a| 
균형

|===
. 첫 번째 규칙과 일치하지 않는 개체의 복제된 복사본 2개를 생성하는 ILM 규칙을 생성합니다. 기본 필터(테넌트 계정 또는 버킷 이름) 또는 고급 필터를 선택하지 마십시오.
+
[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
2개의 복제 복사본



 a| 
버킷 이름
 a| 
_없음_



 a| 
고급 필터링
 a| 
_없음_



 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
0일째부터 영원히



 a| 
유형
 a| 
복제됨



 a| 
위치
 a| 
수



 a| 
사본
 a| 
2



 a| 
수집 동작
 a| 
균형

|===
. 제안된 ILM 정책을 생성하고 두 규칙을 선택합니다. 복제 규칙에서는 필터를 사용하지 않으므로 정책의 기본(마지막) 규칙일 수 있습니다.
. 테스트 오브젝트를 그리드에 수집.
. 테스트 개체를 사용하여 정책을 시뮬레이션하여 동작을 확인합니다.
. 정책을 활성화합니다.


이 정책이 활성화되면 StorageGRID는 다음과 같이 오브젝트 데이터를 배치합니다.

* 'fabricpool-bucket'의 FabricPool에서 계층화한 데이터는 2+1 삭제 코딩 방식을 사용하여 삭제 코딩됩니다. 데이터 조각 2개와 패리티 조각 1개가 서로 다른 스토리지 노드 3개에 배치됩니다.
* 다른 모든 버킷의 모든 객체가 복제됩니다. 두 개의 복제본이 생성되고 두 개의 서로 다른 스토리지 노드에 배치됩니다.
* 삭제 코딩 및 복제된 복사본은 S3 클라이언트에서 삭제할 때까지 StorageGRID에서 유지됩니다. StorageGRID ILM은 이러한 항목을 삭제하지 않습니다.

